### ISSUE TITLE
0.2.1 not populating breadcrumb view

### ISSUE THREAD

**Issue by weeyizhi** [SkepticMystic/breadcrumbs#10]
Obsidian version: 0.12.4
Breadcrumbs plugin: 0.2.1
Dataview: 0.3.13

My breadcrumb view is empty now. Tried clean reinstall of the plugin and also disabling and re-enabling the plugin.
![image](https://user-images.githubusercontent.com/7296340/122698386-d157cc80-d279-11eb-8fb2-b79a577ae3f9.png)

Ther are some error logs (also, I noticed that the plugin says "loading plugin" instead of "loading Breadcrumbs plugin". This is what I get when I start Obsidian. I think it might be due to dataview not having populated its index yet. Don't think there's much that can be done until Dataview provides an API to check if indexing is done.
![image](https://user-images.githubusercontent.com/7296340/122698559-1ed43980-d27a-11eb-8594-6b44968716c3.png)

This is what I get when I disable and re-enable the plugin, and switch file. I believe this is the actual issue:
![image](https://user-images.githubusercontent.com/7296340/122698631-42977f80-d27a-11eb-81fc-32233f9e6dc7.png)

**Comment by SkepticMystic** [comment]
Yes, it seems this happens onLoad. But if you click around a bit, change to different notes, then the breadcrumb trail and matrix get a chance to redraw and it should start working. This is a bug, which I'll try to fix, but a hacky fix is just to change notes

**Comment by weeyizhi** [comment]
The `foreach` issue is fixed on 0.2.3. I'm now able to get the view to populate with breadcrumb and matrix.
I'll leave it up to you if you want to close this or keep it open to keep track of the "cannot read property 'page' of undefined" problem with dataview.

**Comment by SkepticMystic** [comment]
Awesome, thanks for the feedback. I will close this one and add the dataview index loading issue to #9
