### ISSUE TITLE
FR: Allow yaml frontmatter in hierarchy note

### ISSUE THREAD

**Issue by chickenborn** [SkepticMystic/breadcrumbs#100]
![image](https://user-images.githubusercontent.com/9512860/130330503-68417045-6890-4129-967a-ac4b052c7d79.png)

**Comment by chickenborn** [comment]
![image](https://user-images.githubusercontent.com/9512860/130330746-8f6a95c0-ff6a-4272-b848-661525e10cd3.png)

**Comment by chickenborn** [comment]
I think I found the issue. The whole plugin doesn't work, if there is a code block in one of the hierarchy files.

**Comment by chickenborn** [comment]
Or even metadata seems to break it for me.

**Comment by SkepticMystic** [comment]
Hey @chickenborn :) It sucks that the hundredth issue was a bug 😂 but it is what it is 😋 
Yes, for now, the hierarchy note feature is relatively delicate. It can't have anything in it besides markdown list items `- [[Note]]` and blank lines. As you've seen, everything else will break it

**Comment by chickenborn** [comment]
> sucks that the hundredth issue was a bug 😂
Oh very sorry for that :P 

Now that I know the reason of the error, I have no big issue that there is currently no other content allowed, I just have a workflow that doesn't fit the current Breadcrumbs Hierarchy setup.

I have lots of index files (generated with the zoottelkeeper plugin) but I need to index them all by hand in the breadcrumbs menu so that's not a viable option.

**Comment by SkepticMystic** [comment]
@chickenborn in 0.10.44 you can now have yaml frontmatter in a hierarchy note!
Meaning the hierarchy note can be part of the hierarchy 😋 

![image](https://user-images.githubusercontent.com/70717676/130332105-1f126b9c-c988-47b0-868c-afe9393037bd.png)

CC @zcysxy @keithadams @BricoleurSoul @bodiequirk

**Comment by chickenborn** [comment]
That's great news, thanks!

**Comment by keithadams** [comment]
> Meaning the hierarchy note can be part of the hierarchy 😋

Genius! Worthy of the 100th issue 🥳
