### ISSUE TITLE
FR: Free-Form Edit Mode in Breadcrumbs Visualization Graph

### ISSUE THREAD

**Issue by globaldeejays** [SkepticMystic/breadcrumbs#107]
Fully free-form mode where you can rearrange the nodes (like in simplistic mindmap software), without any modalities like force or distance etc. whatsoever. 
And then, ideally a button to save that exact state and be able to load it (manually or by default, I'm ok with either but personally I'd love it to stay in free form mode and open where I left off last time). 
Also next-level-ideal would be if you could save states by a name and be able to load the one you want. That would enable a lot of creativity and playing with different spatial organisations, being able to save them all separately, then maybe ditching the ones you don't like and saving the ones you do, instead of just having a single state-save.

Other Obsidian users requesting such a feature:
https://forum.obsidian.md/t/save-node-positions-in-graph-view-edit-and-preview-toggle/1423

Another possible way to implement this would be to potentially have a hybrid mode where certain nodes are locked in space, while others still behave based on force parameters and such, e.g. if you have a key node you want to lock somewhere on the graph, and it has like 20 child nodes, instead of having to arrange the 20 nodes manually in a circle around the locked node, the 20 nodes could just organize themselves around the locked node in a force-based way, so it stays aesthetically clean even if you add 10 more child nodes to the key locked node. So essentially, the main idea of this FR could perhaps be implemented by being able to make certain nodes fully free form while others keep behaving as they did in the mode they were in (e.g. Force-based, hierarchical etc) so that the mode is retained for all the nodes except the ones that are marked free form by the user. This would enable a flexible hybrid mode with the best of both worlds. Of course then, having just a single free form node would require saving state in order to have it still be there next time. In such an implementation, an option to make all nodes free form, all at once, would also be important especially in large vaults.

Thanks for the great plugin and all the support!

**Comment by SkepticMystic** [comment]
@globaldeejays in the latest beta release, you can use Juggl with Breadcrumbs! This gives you very fine-grained control over the BC graph. If you want to play around with it, you'll need to install it manually from here: https://github.com/SkepticMystic/breadcrumbs/releases/tag/2.39.3

**Comment by globaldeejays** [comment]
@SkepticMystic awesome, thanks for letting me know! Can't wait to try it, I literally remembered and thought about this FR yesterday, so this is a pleasant surprise 😄

**Comment by HEmile** [comment]
You'll be able to do what you describe to some degree. if you create a code block, you can then rearrange and lock nodes into place, and save these as a workspace. See https://juggl.io/Features/Workspace+mode/Workspace+mode for more info. You won't directly be able to load in the complete graph like in the visualization mode, though.

**Comment by SkepticMystic** [comment]
I'm currently working on a rebuild, and don't think I'll add support for this (I likely won't be adding back the Visualisation view).
Please read here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
If it would really help your workflow, I can consider this again in the new release.
