### ISSUE TITLE
Link all notes in this folder to the folder index note

### ISSUE THREAD

**Issue by lkadre** [SkepticMystic/breadcrumbs#112]
It would be very helpful to be able to quickly link all notes within a folder to a folder note or index note. That would quickly incorporate them into the hierarchy and give a good overview of the vault. 

As mentioned in Discord:

> Breadcrumbs can definitely be used to replicate a folder structure. But only if the metadata is there already (or the hierarchy note). It needs some way to know which notes go where in the hierarchy, you know?

The suggestion, which would solve the problem and quickly input the missing metadata, would be:

> 1. A command that says, "Link all notes in this folder to the folder index note". Something like parent: [[Folder 1 Index]]

Thank you!
(And [here](https://discord.com/channels/686053708261228577/707816848615407697/879997728019595284) is a link to the Discord conversation, if it helps!)

**Comment by SkepticMystic** [comment]
@enjolrs I'm gonna try get this working.
For now, I will work with the requirement that the Folder Index Note be named after the folder

**Comment by SkepticMystic** [comment]
@enjolrs one issue that immediately comes up is that the Breadcrumbs index is refreshed from scratch every time.
So if you run the command `Link all notes in this folder to the folder index note` once, then those notes won't be part of the hierarchy anymore after pressing `Refresh Index`... So I think there needs to be a way to give a list of folders where you want this behaviour to happen, you know what I mean?
So you could give a list, like `['FolderA', 'FolderB']`, and Breadcrumbs would link all those child notes everytime

**Comment by SkepticMystic** [comment]
@lkadre This is implemented in 1.9.0 :D
