### ISSUE TITLE
Link all notes with this tag to the index note for that tag

### ISSUE THREAD

**Issue by lkadre** [SkepticMystic/breadcrumbs#113]
Also mentioned was the possibility of linking tags to a sort of index note, as an easier way to bulk-create readable metadata and incorporate files into the hierarchy.

In some cases, people might have to create notes specifically for this purpose, especially if they don't have many "single concept" notes (a la Wikipedia articles), mas many times they already have a sort of index note or MOC relating to a topic and this would help to quickly link back through them as well.

Discord highlights:

> my concept of automation would be something like, “every note under this folder points back to the folder index” and tying tags to a.. master note that could be queried and the plugin could read the query? [..]

> A command that says, "Link all notes with this tag to the index note for that tag". For example parent: [[Tag 1 Index]]
> Keeping in mind that you would have to tell Breadcrumbs which note is the Folder Index note, and which note is the Tag Index note

> for example, i already have a note called “Aesthetics” on the concept, and also a tag “#aesthetics” for related notes. it’d be fantastic to link them together because i know that every note with that tag has something to do with it, even if not necessarily linked

Thank you!
(And [here](https://discord.com/channels/686053708261228577/707816848615407697/879997728019595284) is a link to the Discord conversation, if it helps!)

**Comment by SkepticMystic** [comment]
Thank you for making these detailed issues 😄 
I'll work on these when I can.

I think these are related to #111

**Comment by SkepticMystic** [comment]
@lkadre This is now possible in 1.10.1!
Check out the wiki page: https://github.com/SkepticMystic/breadcrumbs/wiki/Alternative-Hierarchies#tag-indices
