### ISSUE TITLE
FR: Ability to SHIFT + Click Links to Open in a New Pane

### ISSUE THREAD

**Issue by bodiequirk** [SkepticMystic/breadcrumbs#115]
Breadcrumbs has become the default navigation of my Obsidian vault and I cannot imagine it without it anymore.

The only setting missing would be to SHIFT + Click a link to open a new pane.

If you could add SHIFT+Clicking to open a new pane, that would be awesome!

**Comment by SkepticMystic** [comment]
Can confirm, finally working!
