### ISSUE TITLE
FR: Import parent and child into obsidian graph

### ISSUE THREAD

**Issue by veradrawer** [SkepticMystic/breadcrumbs#116]
Having the obsidian graph updated with the relationships we're setting in the metadata feels like the obvious next step.

Current workaround: Manually adding a duplicate of the links so Obsdian updates the graph.

Thank you

**Comment by SkepticMystic** [comment]
Gonna close this out. But given that Breadcrumbs already supports the proposed yaml link syntax, it should start working as soon as Licat adds support
