### ISSUE TITLE
This note has no real or implied parents

### ISSUE THREAD

**Issue by skorphil** [SkepticMystic/breadcrumbs#118]
Just got `This note has no real or implied parents` on every page

**Comment by SkepticMystic** [comment]
@skorphil I'll need a little bit more info from you, but we can get it working!
Do you have Discord? It may be easier to debug from there, my handle is @SkepticMystic :)
If not, we can do it from here

**Comment by tinyheero** [comment]
Hi @SkepticMystic,

I am having the exact same issue. It used to work, but somewhere along the way of the updates it is no longer giving me any breadcrumbs. I am currently running:

* Obsidian version: 0.12.15
* Breadcrumbs version: 0.10.61

The developer's console isn't revealing anything strange either as it just says "loading breadcrumbs plugin".

**Comment by SkepticMystic** [comment]
Hey @tinyheero :)
Do you get any errors when pressing Refresh Index?
If not, can you enable Super Debug Mode, then Refresh Index, and see if you get any errors in the nested console logs

**Comment by tinyheero** [comment]
Hi @SkepticMystic,

Thanks for the reply :) 

No errors from what I can see. I've attached two screenshots:

1. Showing it in edit mode with `parent: ` in the YAML file

    ![edit_mode](https://user-images.githubusercontent.com/3268173/132192383-1c9d306d-444b-4a91-b488-a0d1dd0f30c8.png)

2. Showing it in preview mode with the "This note has no real or implied parents" text:

    ![preview_mode](https://user-images.githubusercontent.com/3268173/132192445-32ffe666-47d8-4c72-be71-d9e52b1871a1.png)

The Obsidian developer console is shown (on the right) in both cases with no errors (at least based on what I can see and my understanding of how to read the console).

**Comment by SkepticMystic** [comment]
Hmmmm ok, everything looks fine there.
Can you send me the content of the `data.json` file in the `{Vault}/.obsidian/plugins/Breadcrumbs/` folder. (It's just your settings all in one place)

**Comment by tinyheero** [comment]
Here it is:

```
{
  "userHierarchies": [],
  "indexNote": [
    ""
  ],
  "hierarchyNotes": [
    ""
  ],
  "hierarchyNoteDownFieldName": "",
  "hierarchyNoteUpFieldName": "",
  "refreshIndexOnActiveLeafChange": false,
  "useAllMetadata": true,
  "parseJugglLinksWithoutJuggl": false,
  "dvWaitTime": 5000,
  "refreshIntervalTime": 0,
  "defaultView": true,
  "showNameOrType": true,
  "showRelationType": true,
  "filterImpliedSiblingsOfDifferentTypes": false,
  "rlLeaf": true,
  "showTrail": true,
  "hideTrailFieldName": "hide-trail",
  "trailOrTable": 3,
  "gridDots": false,
  "dotsColour": "#000000",
  "gridHeatmap": false,
  "heatmapColour": " #705dcf",
  "showAll": false,
  "noPathMessage": "This note has no real or implied parents",
  "trailSeperator": "→",
  "respectReadableLineLength": true,
  "visGraph": "Force Directed Graph",
  "visRelation": "Parent",
  "visClosed": "Real",
  "visAll": "All",
  "wikilinkIndex": true,
  "aliasesInIndex": false,
  "debugMode": false,
  "superDebugMode": true
}
```

**Comment by SkepticMystic** [comment]
Oh yeah, there's the problem! 😅 you need to set up your hierarchies first. You can read about that in the wiki [here](https://github.com/SkepticMystic/breadcrumbs/wiki/Hierarchies).
Let me know if you come right

**Comment by tinyheero** [comment]
Ah I am a fool! 

I don't recall having to do this before. Or maybe I did, deleted it, and I completely forgot about it. In any case, it works now! 

Thanks so much. Enjoy the much deserved coffee (https://Ko-fi.com/home/coffeeshop?txid=e8812933-7fe2-49a3-9492-9d29a350bb08&mode=public&img=ogiboughtsomeone) :)

**Comment by SkepticMystic** [comment]
The multiple hierarchies feature is still relatively new, and it was a breaking change, so that's understandable!
Glad it's working again though :) and thank you for the support!
