### ISSUE TITLE
FR: list view as an alternative to matrix view

### ISSUE THREAD

**Issue by weeyizhi** [SkepticMystic/breadcrumbs#12]
The matrix view is great, but for cases where I'm using small screens, my sidebars tend to be smaller, and I would prefer using a list view in that case. I would like to suggest a setting to toggle between list and matrix view. 

The list view would be just like the backlink plugin's list:
![image](https://user-images.githubusercontent.com/7296340/122757629-697da200-d2ca-11eb-8b01-bdb41764b196.png)

But instead of `links` and `unmentioned links`, it would have
- top/root
- parents
- siblings
- children
And all of these would be collapsible like the ones in backlink.

Thanks so much for the amazing work!

**Comment by SkepticMystic** [comment]
Very good idea! I can definitely try get that working :)

**Comment by SkepticMystic** [comment]
This should be working as of 0.2.0, and some bug fixes are coming in 0.2.1
