### ISSUE TITLE
Failed to install plugin "Breadcrumbs"

### ISSUE THREAD

**Issue by VictorHendricus** [SkepticMystic/breadcrumbs#120]

**Comment by dbarenholz** [comment]
@VictorHendricus Can you give a little more information on what precisely fails?

For instance:

1. What steps did you take to install?
2. At which step do you get unexpected (=failing) behaviour?

**Comment by VictorHendricus** [comment]
I did just regular installation from community plugins tab in obsidian. After I click install button it says "Installing plugin Breadcrumbs" and then says "Failed to install plugin Breadcrumbs". I also tried downloading from github directly and it saw the addon, but when I tried to enable it, it said "Failed to load plugin Breadcrumbs"

**Comment by sdnnvs** [comment]
Same problem here. First, I tried to update the plugin from version 0.10.49 to 0.10.50, resulting in an inability to install. I uninstalled version 0.10.49, and even so, I couldn't install version 0.10.50. Only the message that the plugin cannot be installed appears.

**Comment by dbarenholz** [comment]
I believe that @SkepticMystic's automatic release system is broken then; As you can see (https://github.com/SkepticMystic/breadcrumbs/runs/3454252870) the last commit is still building. So my guess: Obsidian immediately updates their index with "hey, we have a new version" even though this new version is not quite there yet.

**Comment by VictorHendricus** [comment]
That makes sense

**Comment by SkepticMystic** [comment]
Yeah, that's exactly what's happening...
I've got to manually release for now

**Comment by brimwats** [comment]
![image](https://user-images.githubusercontent.com/49103046/131259944-5d071362-6077-4306-a0f1-c935daeb6bba.png)


just came here to confirm and show the console

**Comment by SkepticMystic** [comment]
@brimwats @VictorHendricus @sdnnvs it should be working now on 0.10.51 :)

**Comment by sdnnvs** [comment]
> @brimwats @VictorHendricus @sdnnvs it should be working now on 0.10.51 :)

Yes, working now... great job... thx...

**Comment by VictorHendricus** [comment]
Yeah it works, nice job, this add on would be very helpful for my system, thanks.

**Comment by SkepticMystic** [comment]
Gonna close this out, glad it's working again
