### ISSUE TITLE
FR: allow recognition of hierarchy based on Johnny decimal style file name

### ISSUE THREAD

**Issue by hieu6** [SkepticMystic/breadcrumbs#122]
based on brainstorm of the feature in the following discussion
 https://github.com/SkepticMystic/breadcrumbs/discussions/106#discussioncomment-1264105

an example of decimal notation that we can setup in a hierarchy note

![Screenshot_20210901-025244.png](https://user-images.githubusercontent.com/72253321/131651502-0978ee2e-b05a-4527-8347-41dee9c19de6.png)

🌻

**Comment by SkepticMystic** [comment]
Thanks for the issue @hieu6 
Are you aware of the differences between this system and the Folgezettel system (#360)?
It would be really helpful if you can summarise the rules for Johnny decimal here, and possibly contrast them with the other
