### ISSUE TITLE
FR: Display Alias (or user-specified field) instead of note name

### ISSUE THREAD

**Issue by veradrawer** [SkepticMystic/breadcrumbs#124]
I was wondering if it could be possible for breadrumbs to display the declared note title instead of what the filename is so its consistent with Dataview.

Current preview of a sidebar:
![imagen](https://user-images.githubusercontent.com/75331117/132099382-ab0c61ba-6b50-442f-b3a2-538fd527420e.png)

**Comment by SkepticMystic** [comment]
@veradrawer  What is the 'declared note title'? Do you mean it's alias?

**Comment by veradrawer** [comment]
Pardon me if this isn't standard, but I tought that "title" was the stablished.

![imagen](https://user-images.githubusercontent.com/75331117/132102310-4ce0cf90-86ae-4172-abe1-b8be4eb5d975.png)

**Comment by SkepticMystic** [comment]
Ahh I see! I'm not familiar with that as a "standard". I know pandoc uses it, and some other tools, too. But I don't think it's treated differently in Obsidian (the way `tags` or `alias` is).
I think showing the `alias` of a note is a reasonable FR. I suppose this could pretty easily be extended to show the `title` instead

**Comment by SkepticMystic** [comment]
@veradrawer I've implemented this in 0.10.70! There is now a setting under `General Options` to give a list of field names to check for as aliases or titles. Let me know if this works as intended :)
Currently, it only applies to the l/m view, not the trail/grid view
