### ISSUE TITLE
Failing to Install on Mobile

### ISSUE THREAD

**Issue by brimwats** [SkepticMystic/breadcrumbs#125]
I got an update failure so I tried uninstalling/reinstalling but now it's failing to install period 🤔

**Comment by SkepticMystic** [comment]
Hmmm ok.. I suspect this is an issue with the latest release not building properly (again...), not with mobile specifically. 
Thanks for noting this, I'll push a new one later today and check that it works

**Comment by SkepticMystic** [comment]
@brimwats can you try out the latest release and let me know if you still face this issue?

**Comment by brimwats** [comment]
works now! thanks ☺️
