### ISSUE TITLE
Fail to use "create a global index to the clipboard" and "write breadcrumbs to current file"

### ISSUE THREAD

**Issue by vizance** [SkepticMystic/breadcrumbs#126]
Hello,

I try to use "create a global index to the clipboard" and "write breadcrumbs to current file" but fail. Below are the detailed error logs.

I have no idea why these errors happen...

Thank you.

## create a global index to the clipboard

<img width="555" alt="CleanShot 2021-09-06 at 11 38 18@2x" src="https://user-images.githubusercontent.com/29624657/132157410-37d63c2b-b1aa-422f-9d95-81ffbb143e69.png">

## write breadcrumbs to current file

<img width="548" alt="CleanShot 2021-09-06 at 11 41 32@2x" src="https://user-images.githubusercontent.com/29624657/132157648-435a0f55-1664-4899-9635-c5ed66e84ba7.png">

<img width="437" alt="CleanShot 2021-09-06 at 11 41 47@2x" src="https://user-images.githubusercontent.com/29624657/132157674-97ddbd6a-4bb8-47ac-a25e-143d7edd94bf.png">

---

Here is my Hierarchy setting.

<img width="781" alt="CleanShot 2021-09-06 at 11 43 17@2x" src="https://user-images.githubusercontent.com/29624657/132157754-e53f30f6-8cff-4cb7-a038-7caf398ac761.png">

<img width="1061" alt="CleanShot 2021-09-06 at 11 43 25@2x" src="https://user-images.githubusercontent.com/29624657/132157763-52d16abc-7eb2-4b37-8ef6-bf84ce2549fa.png">

**Comment by SkepticMystic** [comment]
@vizance thanks for the issue report!

1. For the Create Index function, where are you running it from? I think that error happens when you aren't focused on a markdown note (you can't be focused on the graph view, for example).
2. You have to have the MetaEdit plugin enabled for that feature to work. I should add a notice for that. Thanks for checking :)

**Comment by vizance** [comment]
@SkepticMystic thanks for your response. 

Below are my error logs.

> 1. For the Create Index function, where are you running it from? I think that error happens when you aren't focused on a markdown note (you can't be focused on the graph view, for example).

I focus on a markdown note and run the command agin but still fail. Below is the error log.

<img width="551" alt="CleanShot 2021-09-06 at 17 46 36@2x" src="https://user-images.githubusercontent.com/29624657/132197336-194d49fa-04af-4237-9f34-53f5628c0929.png">

<img width="394" alt="CleanShot 2021-09-06 at 17 44 33@2x" src="https://user-images.githubusercontent.com/29624657/132197046-c7a05e01-8553-49a6-83d7-4f9db677df1e.png">


> 2. You have to have the MetaEdit plugin enabled for that feature to work.

I install the MetaEdit plugin and run `write breadcrumbs to current file` again but fail. Below is the error log.

<img width="548" alt="CleanShot 2021-09-06 at 17 46 18@2x" src="https://user-images.githubusercontent.com/29624657/132197295-d8b26f89-617d-464e-9958-90acc6279f95.png">

<img width="446" alt="CleanShot 2021-09-06 at 17 46 00@2x" src="https://user-images.githubusercontent.com/29624657/132197246-b9bf17ae-b8d3-49f7-b604-e1c654d3b37a.png">

**Comment by SkepticMystic** [comment]
Both of those errors come from `currGraphs` being undefined. Which usually means you just need to Refresh Index and try again.
Can you let me know if that works?

**Comment by vizance** [comment]
Hi @SkepticMystic 

I've refreshed index and try again, but found there is no reaction or error log when I use `write breadcrumbs to current file ` and `Copy a Global Index to the clipboard` now. 

I just recorded a gif.

![CleanShot 2021-09-06 at 21 49 50](https://user-images.githubusercontent.com/29624657/132227545-d334a664-bc85-4bc5-8946-751031e0a289.gif)

Should I open Super Debug Mode ?

note : I've updated to v.0.10.61

**Comment by SkepticMystic** [comment]
@vizance can you message me on Discord. It'll be easier to work from there. My handle is @SkepticMystic there too :)

**Comment by vizance** [comment]
hi @SkepticMystic 

Just send a DM to you on Discord : )

**Comment by SkepticMystic** [comment]
Gonna close this out, fixed it over Discord.
Thank you for the bug report :)
