### ISSUE TITLE
Bug: file listings in matrix view are in desc order

### ISSUE THREAD

**Issue by veradrawer** [SkepticMystic/breadcrumbs#127]
The elements listed in the matrix view appear in descending order, I don't know if this is intended but I was told to post it here.

![imagen](https://user-images.githubusercontent.com/75331117/132234647-f2658d42-516e-4059-a8ec-1d8e2ac3f1e6.png)

Thanks as always!

**Comment by SkepticMystic** [comment]
Haha for now, the entries are not sorted.
I _think_ they appear in the same order that they appear in the note

**Comment by SkepticMystic** [comment]
I'm gonna close this as the FR for sorting already exists: #92
