### ISSUE TITLE
FR: Only us selected fields when Writing Breadcrumbs to Current File

### ISSUE THREAD

**Issue by BricoleurSoul** [SkepticMystic/breadcrumbs#130]
For the proposed auction,  Use a comma-delimited field (or checkbox) to define which hierarchies  to "Write Implied Breadcrumbs to the current file"

For example, if A has parent: [[B]], then this feature would write the following to B when run:

---
child: ['A']
---

**IF AND ONLY IF** for parent: [[B]] there is an entry in the Hierarchies setting indicating that auto updating of the YAML field should occur. This could be   by either a checkbox next to each hierarchy or via new field composed of  comma-separated names of the hierarchy where the insert is to be executed,

Ie. I might want child: ['A'] only to be inserted where the parent hierarchy value is "complex-system" or where the parent value is "multidisciplinary" but not for any of the other 4 hierarchies I have defined.

**Comment by SkepticMystic** [comment]
Very much agree with this functionality.
I will make it more granualar to choose specifc fields within each hierarchy, as opposed to entire hierarchies

**Comment by SkepticMystic** [comment]
I should be able to add this quite easily given the issue #128 was relatively simple to implement

**Comment by SkepticMystic** [comment]
@BricoleurSoul added in 0.10.69. Will you let me know if it works for you as expected?

**Comment by BricoleurSoul** [comment]
test with a new hierarchy set up specially for the purpose ... and three notes created especially for purpose
(the Bric's Belt and Suspenders Safety rule)
and all instances worked exactly as intended (up | sideways| down) values all updated in YAML when write called from command prompt for each of the three records...

**Comment by BricoleurSoul** [comment]
Thanks for the granularity!

**Comment by SkepticMystic** [comment]
Good stuff :D 
I'll keep this issue open a little longer, but I think it should just be working.

**Comment by BricoleurSoul** [comment]
I think you can close issue - two weeks now and no issues found! Thx.
