### ISSUE TITLE
V. 10.67 broken

### ISSUE THREAD

**Issue by enjolrs** [SkepticMystic/breadcrumbs#134]
The latest update seems to have broken something at the plugin. I'm attaching the console log in case it helps.
[obsidian.md-1631169609500.log](https://github.com/SkepticMystic/breadcrumbs/files/7134081/obsidian.md-1631169609500.log)

**Comment by SkepticMystic** [comment]
@enjolrs weird... I've not seen that error before about unit locals...
I think that is an issue with dataview.
Do you use dates in dataview fields?

**Comment by enjolrs** [comment]
You're right! I turned off dataview and the hierarchies from the hierarchy note still exist.

Sorry to keep bothering you, I'm not a programmer so I'm never sure which plugin is causing issues.

**Comment by enjolrs** [comment]
And it seems to have been fixed! Sorry again for the bother.

**Comment by SkepticMystic** [comment]
No worries, glad to hear it's working again!
It isn't always obvious where the error comes from
