### ISSUE TITLE
Thebrain-like view

### ISSUE THREAD

**Issue by link-ding** [SkepticMystic/breadcrumbs#135]
The Breadcrumbs plugin is very similar to thebrain in its concept of building relationships between different knowledge through parents, children, and siblings. So I hope you can add a visualisation View similar to thebrain. What Thebrain's visualisation view is shown below. Thanks for creaing this amzing plugin. I have been waiting this for a long time.

![image](https://user-images.githubusercontent.com/49264539/134849653-2e01a247-1733-4b93-9e79-4dc7f20ccacf.png)
![image](https://user-images.githubusercontent.com/49264539/134849920-2031d0ca-e813-4e7e-8fea-c2c0b733d5d3.png)

**Comment by SkepticMystic** [comment]
Hey @link-ding, thanks for the post.
If I'm understanding correctly, this is the same information that's already shown in the [list/matrix view](https://github.com/SkepticMystic/breadcrumbs/wiki/Relationships-Implied) (see the image in the link), just visualised in a different way?

**Comment by link-ding** [comment]
> Hey @link-ding, thanks for the post.
> If I'm understanding correctly, this is the same information that's already shown in the [list/matrix view](https://github.com/SkepticMystic/breadcrumbs/wiki/Relationships-Implied) (see the image in the link), just visualised in a different way?

Thanks for quick reply!! Yes that is what I am talking about.

**Comment by dleeftink** [comment]
Maybe can be powered by [D3-dag](https://www.npmjs.com/package/d3-dag)?

**Comment by SkepticMystic** [comment]
I feel that the new Juggl Codeblocks fulfil this FR enough.
Checkout the latest beta release here (you'll have to install it manually): https://github.com/SkepticMystic/breadcrumbs/releases/tag/2.41.0
You can read the docs on BC codeblocks here: https://github.com/SkepticMystic/breadcrumbs/wiki/Codeblocks
Juggl blocks work the same as `type: tree`, except you use `type: juggl`

**Comment by HEmile** [comment]
Probably the Juggl view in Settings -> Views -> Trail/grid/Juggl view is most similar to this request
