### ISSUE TITLE
Bug: Nodes are added using their basename instead of path. Conflict ensues

### ISSUE THREAD

**Issue by vitaly** [SkepticMystic/breadcrumbs#136]
I have several `journal` directories, one per client

this plugin mixes the notes from different journal, but sharing the same file namr

e.g if I have `Client A/journal/2021-10-01` that sets `client:: [[Client A]]` and `client B/journal/2021-10-01` that sets `client:: [[Client B]]`, then both of those notes will have both clients as their `project` (Real).

I enabled the debug logs, and from the looks of it, it only uses the file name for the indexing, ignoring the path.

**Comment by SkepticMystic** [comment]
There is sort of a limitation here, you see.
I only have as much information as is in the wikilink brackets `[[info]]`. So if I only know that `date:: [[2021-10-01]]`, then that's all I've got to go off of.
There is an option to have the full file path in the brackets, which is something I can try account for. But this will take me some time to work out the kinks

**Comment by zsviczian** [comment]
I just bumped into this issue. Why not use `getFirstLinkpathDest(linkpath: string, sourcePath: string): TFile` when indexing the vault?

**Comment by shixinzi** [comment]
Problem still exists?

**Comment by wiebe** [comment]
I can confirm this still exists, i am running into this same issue even when i specify the full path.

**Comment by gbeine** [comment]
I have the same issue currently.
I have multiple files with the same name in different folders.
Even though I alwas use the whole path in the up/next relations, the result is a reference to the wrong file.

**Comment by jonnymauser76** [comment]
Hi guys,
any news on this one? After using my vault for quite a while with daily notes in subfolder together with events for that day in respective notes, I increasingly encounter notes with identical names in different subfolders. Is there any workarround or fix for this?

**Comment by SkepticMystic** [comment]
This is one of the longest-standing issues, so I think it's a good place to mention that I'm working on rebuilding Breadcrumbs.
This issue is resolved in the beta release, so you can start using it today.
But please do read more before upgrading: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md

I'll keep this issue open until the new version is live

**Comment by SkepticMystic** [comment]
Now that I've officially announced V4 on the Discord server, I'm going to finally consider this issue closed :) Again, checkout the V4 changes for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
