### ISSUE TITLE
FR: Show NTs and RTs in note

### ISSUE THREAD

**Issue by brimwats** [SkepticMystic/breadcrumbs#137]
I have a landing page that all my notes point to:
![image](https://user-images.githubusercontent.com/49103046/135724091-d24fe5d3-097f-4dd9-98c6-460fe12b28b9.png)

it does say `This note has no real or implied parents ` which is right, but i would love to see the Real NTs and RTs "in-note" and not just in matrix view if possible. Can they be allowed into notes via a toggle or something?

**Comment by SkepticMystic** [comment]
Interesting...
How would they look in the path view?
As an alternative, how about a dataview query?
```
List
Where nt = this.file.link or contains(nt, this.file.link)
```

**Comment by brimwats** [comment]
dv would work, i just hardly use or understand it 😅

i'm thinking about this and the more I do the more I think it might not be possible or it would be out of scope. originally I thought something like 
![image](https://user-images.githubusercontent.com/49103046/135725228-c16b701a-7197-4976-a019-b04555f167a7.png)

but that might be weird!

**Comment by SkepticMystic** [comment]
@brimwats does this plugin do what you're looking for? :)
https://github.com/Robin-Haupt-1/Obsidian-Map-of-Content

**Comment by brimwats** [comment]
it might! thanks
