### ISSUE TITLE
FR: Point to a folder of hierarchy notes to read all of them, instead of writing out each hierarchy note name individually

### ISSUE THREAD

**Issue by pdlife** [SkepticMystic/breadcrumbs#138]
"Hierarchy Note(s)
A list of notes used to create external Breadcrumb structures."

About this setting.

I think it would be better to apply to all notes, or set all notes in a folder. So that it can determine the parent and child of a note through the list. Instead of "parent:: [[]], child:: [[]]"

**Comment by SkepticMystic** [comment]
Hey @pdlife :)
I'm not sure I understand. Hierarchy notes do this: https://github.com/SkepticMystic/breadcrumbs/wiki/Hierarchy-Notes, right.
Are you instead asking for something like #112?
Or something completely different?

**Comment by HananoshikaYomaru** [comment]
@pdlife If you want to put store hierarchy notes in a folder you need to specify the path to the folder such that the names of different notes won't be mixed up. For example, 

`hierarchy/obsidian, hierarchy/javascript, hierarchy/mathematics, hierarchy/Root, hierarchy/awesome books, hierarchy/Computer Science`

I write a script to automatically generate the hierarchy note string. Whenever I add a refactor my note, add or remove a hierarchy note, I just need to copy and paste that string.

**Comment by SkepticMystic** [comment]
@HananoshikaYomaru do you mind sharing the script? :)
Maybe I can add that as a feature!

**Comment by HananoshikaYomaru** [comment]
Sure, all my hierarchy notes is in the `hierarchy` folder. 

And I have the following `dataviewjs` script

`dv.paragraph(dv.pages('"hierarchy"').file.name.map (name => "[[hierarchy/" + name + "]]").join(", "))`

This line will generate a string that I can directly copy and paste into the hierarchy note field.

**Comment by SkepticMystic** [comment]
I've added this in the latest release :)
You can enter a folder name (ending with `/`) to use all the child notes in that folder as hierarchy notes

**Comment by HananoshikaYomaru** [comment]
that will be absolutely convenient!!!
