### ISSUE TITLE
Filter duplicates in implied siblings

### ISSUE THREAD

**Issue by HEmile** [SkepticMystic/breadcrumbs#139]
If there are multiple paths that show two notes are implied siblings, that sibling shows up multiple times in the Breadcrumbs matrix. This happens for instance when multiple authors write multiple papers together. This clutters up the matrix. Ideally, one would only see a single appearence.

![image](https://user-images.githubusercontent.com/1289165/135850648-5d9f3c53-63ff-4bb4-aa1a-65a6b007e20b.png)

**Comment by SkepticMystic** [comment]
Thanks Emile. I see where the issue is in the code, just need to think of a good way to fix it

**Comment by SkepticMystic** [comment]
@HEmile does this still happen? I think I addressed it

**Comment by HEmile** [comment]
Pretty sure you did yeah. Can't remember noticing it for a while!
