### ISSUE TITLE
[Feature] Hover preview for links

### ISSUE THREAD

**Issue by kometenstaub** [SkepticMystic/breadcrumbs#14]
It would be cool if the links supported hover preview.

Explanation from @lishid:
https://discord.com/channels/686053708261228577/840286264964022302/850078594768044093

Implementation from Murf:
https://discord.com/channels/686053708261228577/840286264964022302/849801819169488896

More implementation examples:
https://github.com/search?q=workspace.trigger%28%27hover-link%27%2C+%7B&type=code

**Comment by SkepticMystic** [comment]
This is definitely something I'll work on 🙂 Thanks for the input and the references

**Comment by kometenstaub** [comment]
implemented as of 0.5.0
