### ISSUE TITLE
[feature request] Support custom formatter for "writeBCtoFile"

### ISSUE THREAD

**Issue by HananoshikaYomaru** [SkepticMystic/breadcrumbs#140]
Current WriteBCtoFile create the properties in metadata. In this way, the links don't work on graph view. I want to generate the breadcrumbs that make it work for graph view. I am not sure if such an operation exists now but I think a custom formatted will solve it.

**Comment by SkepticMystic** [comment]
I think I'll add the option to write to file as a Dataview inline field. It will just be added directly under the yaml (or at the top of the note if there is no yaml)
