### ISSUE TITLE
Bug: 10.74 breaks matrix/list and breadcrumbs

### ISSUE THREAD

**Issue by BricoleurSoul** [SkepticMystic/breadcrumbs#142]
Neither breadcrumbs nor matrix/list panel show entries after upload of 10.74.  Sorry just caught but unable to do detail study until late this evening.... restore to 10.73 and all works. Does the new entry for csv path have to have value even if not using the feature?

**Comment by Victor-IT** [comment]
Yup, noticed this behavior right after the update.

**Comment by jundaychan** [comment]
same here

**Comment by SkepticMystic** [comment]
Thanks everybody. Sorry for the trouble. I haven't been able to work on it yet. Can someone please check if there are any errors in the console when this happens?

**Comment by SkepticMystic** [comment]
Oops, this got closed automatically. 
@BricoleurSoul @gfidias @jundaychan @Victor-IT can you let me know if this is resolved in 0.10.75?

**Comment by gfidias** [comment]
resolved 👍

**Comment by BricoleurSoul** [comment]
Haven't tested the new functionality yet, but the issue in 10.74 certainly resolved.
