### ISSUE TITLE
FR: Quick "insert" and "remove" command in the hierarchy notes

### ISSUE THREAD

**Issue by HananoshikaYomaru** [SkepticMystic/breadcrumbs#143]
I used hierarchy notes to organize my tree. There is a problem when my notes get complicated. I think it would be nice if I can call a command such that I can search through the hierarchy and pick a proper position to `insert` the current notes. 

Same for the `remove` command.

**Comment by SkepticMystic** [comment]
I think I get what you're looking for.
I'm not exactly sure how this would work though. So you have your hierarchy note open, you run the cmd, and then what?

**Comment by HananoshikaYomaru** [comment]
Maybe I explain it this way. I am using hierarchy notes to organize my breadcrumb but I am looking for a way to insert my current note to the tree WITHOUT opening the hierarchy note. I have around 20 hierarchy notes and each hierarchy note is big. I don't want to go into the file and disturb my workflow just to insert a note.

This might sound a bit contradictory. But I think hierarchy notes are better for long term management breadcrumbs tree but not good for quick insertion and removal. 

# A possible solution
Inline declaration for breadcrumb is nice. It allows quick insertion and removal from the breadcrumbs tree. But as the hierarchy notes have the advantage for management, what if we could sync two methods of declaration. That is : 

1. whenever you change inline declaration, hierarchy notes change as well 
2. whenever you change the hierarchy note, inline declaration change as well

But clearly, this is not an easy task, but this is the ultimate solution that I can think of.

**Comment by SkepticMystic** [comment]
Yes, that would be ideal, to have everything all synced up... I could try doing that sometime

**Comment by SkepticMystic** [comment]
@HananoshikaYomaru check out 2.7.0 and the `Adjust Hierarchy Note` modal :)
You can quickly jump to an item, or add/remove items from any hierarchy note anywhere in Obsidian

**Comment by SkepticMystic** [comment]
@HananoshikaYomaru I'm gonna consider the initial FR to be closed. 
I know you would eventually like there to be even more functionality, can you open another FR for that specifically?
