### ISSUE TITLE
FR: Show all notes that are not in the hierarchy 

### ISSUE THREAD

**Issue by HananoshikaYomaru** [SkepticMystic/breadcrumbs#144]
I have thought to use a graph filter to filter the notes that are not linked to my hierarchy notes but as the number of hierarchy notes increases, this becomes not feasible. 
Any thought to achieve this?

**Comment by SkepticMystic** [comment]
Hey :)
I guess you can use the Dataview plugin for this! If you field names are `up`, `same`, `down`, then the following dataview query will show notes not connected to your hierarchy (or atleast most of them):

```
list 
where !up AND !same AND !down
```

**Comment by SkepticMystic** [comment]
This is working in 1.4.0!
There is a new "Ducks View" which shows notes not in the hierarchy.
It doesn't open by default, so you have to run the cmd to open it
