### ISSUE TITLE
plugin is inactive until manually refreshed

### ISSUE THREAD

**Issue by SirSceptalot** [SkepticMystic/breadcrumbs#146]
The plugin doesn't show the breadcrumb navigation bar or any content in the breadcrumbs matrix side pane until the "Refresh Index" button is used.

Note from SkepticMystic on Discord:

> I think the issue is that I wait a hardcoded amount of time before trying to open the Breadcrumbs view. If the metadataCache hasn't finished loading yet, then BC fails.
> I actually fixed a very similar problem in Graph Analysis today, so I'm sure it could be applied to BC, too

**Comment by SkepticMystic** [comment]
@SirSceptalot can you please check on 0.11.0 if this still happens :)

**Comment by SirSceptalot** [comment]
I've tested on various machines, and don't see this happening anymore.
Top notch!
