### ISSUE TITLE
FR: Displaying node names in breadcrumb visualization view.

### ISSUE THREAD

**Issue by sudotachy** [SkepticMystic/breadcrumbs#147]
It would be great to have the same viewing functionality as the obsidian graph in relation to the names displayed. 
1 - when you minimize the view, the names of the nodes disappear, but reappear when you "zoom in"
2- when in the "minimized view" the names disappear, but when hovering over the nodes, names of the particular file (currently present) as well as the all the names of the connected nodes can be seen. _Currently only the **name** of the node that is hovered over can be seen, along with the nodes directly connected to the hovered node (without the name)_

Having a transparent background for the names would also be swell! (to allow viewing other node names over each other)

Thanks for the game changing plugin! and taking the time to read this!

**Comment by SkepticMystic** [comment]
Thanks @sudotachy, I can certainly try implementing this once I work on the Vis View again :)

**Comment by sudotachy** [comment]
Thank you!

**Comment by SkepticMystic** [comment]
@sudotachy if you checkout the latest beta release, there are now two ways to visualise your BC hierarchy using Juggl!
You'll need to install it manually from here: https://github.com/SkepticMystic/breadcrumbs/releases/tag/2.39.3.
Checkout it out and let me know what you think

**Comment by SkepticMystic** [comment]
I'm currently working on a rebuild, and don't think I'll add support for this.
Please read here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
If it would really help your workflow, I can consider this again in the new release.
