### ISSUE TITLE
Breadcrumb trail on top of file not updating [bug?]

### ISSUE THREAD

**Issue by ben1mit** [SkepticMystic/breadcrumbs#150]
Updates are not reflected in the breadcrumbs trail, and it still shows "this note has no real or implied parents". 
It updates correctly in the panel to the right. Closing and reopening the file did not help. 
Everything has previously worked correctly for some of the other notes in the hierarchy

<img width="1363" alt="Skjermbilde 2021-11-05 kl  13 17 15" src="https://user-images.githubusercontent.com/48367359/140510515-d04abe5e-c0b1-4c34-8e21-61edcb51f435.png">

**Comment by SkepticMystic** [comment]
Thanks ben1mit. The new release definitely has some bugs, but I'm struggling to pin them down. Do you get any errors in the console? (`Ctrl + Shift + I`).
Otherwise, I recommend downgrading till I can fix it

**Comment by Thaza-Kun** [comment]
I also experience similar issues. Breadcrumbs totally not showing on my reading notes where I have multiple parents but it shows up on my index notes where there is only one. (I checked other reading notes, it shows up if it have one parent). 

![Obsidian_9KKo6VFLjA](https://user-images.githubusercontent.com/61819672/140601461-908b827c-13da-4cd7-bd99-fc30990a03a7.png)
Fig 1: No breadcrumbs

![Obsidian_krkvZ2AdBh](https://user-images.githubusercontent.com/61819672/140601466-189a91b0-f924-4eb3-b326-5db88d487fcf.png)
Fig 2: Have breadcrumbs

Here is the console log when I refresh the index. `rawItem.path.split` seems to be the problem since that is the one showing up.
![image](https://user-images.githubusercontent.com/61819672/140601685-66754b06-db0c-4cdf-bb75-6cf450ce6632.png)
Fig 3: With console log.

**Comment by SkepticMystic** [comment]
@ben1mit @Thaza-Kun can you please test 0.11.7 and let me know if this is resolved :)
There was a significant change to how Dataview returns results from its API, so I've had to add in some extra wrangling steps, but seems to be working on my end

**Comment by ben1mit** [comment]
upgraded to 0.11.8 (the latest available from obsidian menu), and the exact same issue is present. 
For some reason the console doesn't open when I hit Ctrl + Shift + I, so I find it difficult to show you error messages. 
the problem is also present when just linking in the yaml frontmatter.

**Comment by Thaza-Kun** [comment]
@SkepticMystic, I have updated to 0.11.8. The Breadcrumbs path has now rendered correctly on my end. Thank you for the fix.

![image](https://user-images.githubusercontent.com/61819672/141145189-2267d9d1-d7c1-4232-b915-5f1ca5f6efc9.png)

**Comment by SkepticMystic** [comment]
@ben1mit thanks for the feedback. I'd really need to see what errors appear to be able to fix this issue. Maybe try again another time and see if the console appears.

**Comment by ben1mit** [comment]
using cmd + alt + I did the trick for opening  the console.
The  case is still that it shows up fine in the matrix/list view, just not in the trail view.  
I get this error message, hope it is of any help in solving the issue: 
<img width="520" alt="Skjermbilde 2021-11-11 kl  00 34 45" src="https://user-images.githubusercontent.com/48367359/141210581-31aaaff2-ae0d-4f15-9458-e583ce1f3463.png">

**Comment by SkepticMystic** [comment]
Thanks! That's helpful. You see where it says `VMI:961:37905`? Can you click that and send a screenshot of what appears? that'll tell me exactly where the code bugs out

**Comment by ben1mit** [comment]
This is what appeared when I clicked VM961:37905: 
<img width="700" alt="Skjermbilde 2021-11-11 kl  10 18 07" src="https://user-images.githubusercontent.com/48367359/141271531-db61f305-5a9d-41c3-b6f2-11757734e229.png">

This is strange, seeing as I actually have an  index note: 
<img width="629" alt="Skjermbilde 2021-11-11 kl  10 19 31" src="https://user-images.githubusercontent.com/48367359/141271786-66bfb839-7cf8-474e-81ac-a425f96b238b.png">

The hierarchy note is set:
<img width="524" alt="Skjermbilde 2021-11-11 kl  10 26 20" src="https://user-images.githubusercontent.com/48367359/141272991-bce46a06-dd01-470c-9de4-8c993f16a831.png">

and the root indexes index is at the root of the herarchy. 

I also noticed this strange thing, the root index seems to think it is its own parent, without me having set that anywhere:
<img width="897" alt="Skjermbilde 2021-11-11 kl  10 21 57" src="https://user-images.githubusercontent.com/48367359/141272193-6b4d29c4-1a16-43d9-8b73-de75cbcee582.png">

I also got a ton of bugs during start up
before initialize graphs: 
<img width="569" alt="Skjermbilde 2021-11-11 kl  10 31 18" src="https://user-images.githubusercontent.com/48367359/141273894-92600210-4e20-467f-bdcb-60b1b3ac6bb1.png">

<img width="582" alt="Skjermbilde 2021-11-11 kl  10 31 48" src="https://user-images.githubusercontent.com/48367359/141273961-275be205-c327-45e1-80a3-03ca4404d064.png">

and within draw trail i still get the same message:
<img width="597" alt="Skjermbilde 2021-11-11 kl  10 32 22" src="https://user-images.githubusercontent.com/48367359/141274060-1354b458-ad65-4484-94cd-8d7ab4c13372.png">

**Comment by SkepticMystic** [comment]
@ben1mit can you please check the latest version and see if this still occurs

**Comment by ben1mit** [comment]
The latest version available from the plugin menu seems to be 0.11.8, which is the same as the one I tested previously. 
If you release a newer version I can upgrade and test wether it works

**Comment by SkepticMystic** [comment]
@ben1mit ahh right, sorry.
There is a beta version of [1.4.0](https://github.com/SkepticMystic/breadcrumbs/releases/tag/1.4.0) out. You can manually install it from there if you want to try. Be warned, you _might_ need to reset your hierarchies to get everything working, as it was a breaking change in some cases

**Comment by SkepticMystic** [comment]
@ben1mit the beta has now been released publicly, so 1.8.0 is available on the community plugin page :)

**Comment by ben1mit** [comment]
wonderful! updated to the newest version (1.10.1) and it seems the problem is solved
