### ISSUE TITLE
Breadcrumbs - Dataview conflict

### ISSUE THREAD

**Issue by gfidias** [SkepticMystic/breadcrumbs#152]
(cntd from #149)
Breadcrumbs not working when dataview is enabled.

**Comment by gfidias** [comment]
Conflict with dataview still there after updating to breadcrumbs v0.11.6.

**Comment by SkepticMystic** [comment]
@gfidias @veradrawer can you test out 0.11.7 and let me know if this issue is fixed :)

**Comment by gfidias** [comment]
Working 👍
