### ISSUE TITLE
Bug: About Inline Dataview Field Separator

### ISSUE THREAD

**Issue by zcysxy** [SkepticMystic/breadcrumbs#153]
When I try to assign a note with multiple parents, `parent:: [[A]] [[B]]` works but `parent:: [[A]], [[B]]` doesn't. Seems like the separator `,` breaks something.

**Comment by SkepticMystic** [comment]
@zcysxy can you test out 0.11.7 and let me know if this issue is fixed :)

**Comment by zcysxy** [comment]
@SkepticMystic Yeah it's fixed, thanks for the quick fix!
