### ISSUE TITLE
FR: Set all outgoing links of note as children

### ISSUE THREAD

**Issue by ben1mit** [SkepticMystic/breadcrumbs#154]
I currently use a set of index notes to keep a hierarchical order to my notes.
It would be very nice if it were possible to just add one field in the frontmatter of these notes saying that all links from this file are to be considered its children. (and ignore headings and other text). 
Having a field in the settings in which you can list these kind of index notes would also do the trick.  
All the index notes are tagged as "index", so being able to set this setting for all notes with a particular tag would be a big convenience (but not a necessity)

**Comment by SkepticMystic** [comment]
Thanks for the FR @ben1mit.
Can you please share an example of a note you use as an index? I don't quite understand the use case

**Comment by ben1mit** [comment]
Of course

For instance I have a note named "programming index" that contains everything related to programming
within that note I would have links to for instance the notes:
- toolchains index
- programming languages index
- programming projects index
- communication protocols index

within for instance the note "communication protocols" i would have links to notes about
- usart
- parallell bus
- rs232
- i2c 
- spi

And the note on usart would then not be an index-note, but a content note, containing reflections about that protocol etc. 
It would be nice breadcrumb trail on top of the usart-note to see where I fit it into the bigger picture.
(the breadcrumb trail on top of usart would then be "programming index-> communication protocols")

This kind of structure could be achieved by using hierarchy notes the way breadcrumbs generally does. 
However i find that having nested notes fits my workflow much better, because then I am able to slice stuff up and rearrange stuff in a much more modular way. It would also allow me to consider wether some the notes in the index are reflections of the same thing, and write down reflections on the topic as a whole/the individual notes linked to from the index, within the index note itself. 
and also it is the way my vault is structured now, so just adding "set all outgoing notes as children" in the frontmatter of my index notes would save me a lot of work. Even more work would be saved if I could do this on a tag-basis (because I have tagged all my index-notes as such) but I understand if that is too much work.

There is also usecase for daily/weekly/monthly/yearly notes, because my month-notes link to weeks and my week-notes link to days, and the week notes also contain a summary of the week. (so periodic notes also have this index-structure)

this particular way of having a map of content appears to me to be something that is used a bit within the zettelkasten community, and for me it is certainly a structure that has worked well, but would be vastly improved byhaving a breadcrumb trail.

**Comment by ben1mit** [comment]
it seems this feature request is quite similar to #160 which apparently is already functionality that exists.
considering that all my indexes are connected to a root index, setting this as my "central note/home note" would solve my issue/feature request. 
However it seems I have some problems with doing that, since I get the message "alteast one of the notes is not in your vault" when I try to set a note as home note. I also tried setting it without the quotation marks, but then it did not work either.
It might be that I have misunderstood how to use this setting. Nothing happens in the console when I set a home note.
If you want I can open a different issue for this, seeing as that problem is unrelated to my original feature request

<img width="733" alt="Skjermbilde 2021-11-24 kl  10 56 05" src="https://user-images.githubusercontent.com/48367359/143216029-7b8076d8-0e11-4738-9891-6580a22ba55a.png">

**Comment by SkepticMystic** [comment]
@ben1mit the original FR is now possible in 1.12.2. Simply add `BC-link-note: fieldName` to the yaml of a note, and all outgoing links from the note will be added to the graph with `currentNote -fieldName-> outgoingNote` :)

Please do add a bug report for the issue posted below. I will fix that

**Comment by ben1mit** [comment]
thanks. This is great, and I appreciate it.
After updating to 1.14.0  this works.

However I then got problems with the trail not showing up. 
I submitted a new issue for that, #170
