### ISSUE TITLE
Feature request: 2 more hierarchy types - previous and next

### ISSUE THREAD

**Issue by mikkovedru** [SkepticMystic/breadcrumbs#156]
Sometimes I not only need to indicate that 2 notes are siblings, but to also indicate the order of their relationship, that one comes before the other.

Examples:
- With actual people. Especially historical figures.
- With historical events.
- With various processes with stages (it's important in which order black widow handles the husband business)
- With notes and books. It's important to indicate that notes for Chapter 2 come only after the notes for Chapter 1

When you think you will realize how useful the indication of the order would be.

If you like the idea and are willing to accept help, I can participate in the theoretical design of this added ordering system.

**Comment by HEmile** [comment]
That is an interesting idea! I would probably appreciate this as well. Am i right in understanding you would like to define partially ordered relations? https://en.wikipedia.org/wiki/Partially_ordered_set

**Comment by mikkovedru** [comment]
It's kinda up to the design choices on what kind of order/preorder set to make, how easy or complicated. Like, one of the complications is that there is a state of partial information: the breadcrumbs plugin doesn't require every note to have every possible relation defined (and is inferring some relations) nor does it have the functionality of inferring a relation and updating all the appropriate notes involved. Maybe this should be implemented at some point?

Anyway, instead of being technical from the start, I prefer to keep it grounded, by showing examples of the potential use cases. 

Here are a few other use cases:
1. I have a group/MOC for all my forum and social media posts. I might even have a subcategory by the source. Somebody might even make a subject subsubcategory ("Conversations about Obsidian"). In any case, there is a bunch of notes with separate comments. Maybe some of them can be topically added into one single note, but at some point, there is a need for separation. And at that point, it would be very convenient to have a link to the next post/comment in that forum, or that topic, or that particular discussion. Or why not have all 3 options to go to! :-)
2. News. The various development of the story (e.g. different stages of the trial).
3. Course work, study. No matter how small/precise/granular I make the folder/tag system, there still will be enough notes/material for it to be a mess if just kept together as is in one big pile without any MOCs and directional information. Traversing the data should be not only painless, but actually enjoyable. It should be like cruising (optimally after reading each article I should be able to choose to go forward, go deeper, turn left or right, or go back on the subject).

The already classic "How to take smart notes" book tells about several ways to organize one's notes. The one that Niklas Luhmann used, utilized the possibility given by the physical note cards, the ability to put one note after or before the other. This is convenient in many ways, for example when organizing knowledge into logical sequences, to work on book/research/article and later combine them into one.
![image](https://user-images.githubusercontent.com/2521942/142314080-c6bfc281-e17a-4527-a475-05e79302fd85.png)

Up until now, Obsidian didn't really have this possibility. The feature I propose for the breadcrumbs plugin is going to change that.

The only problem I see is how to handle and visualize the missing connections, what and how to infer the missing relations.

What do you think, @HEmile ?

**Comment by SkepticMystic** [comment]
I definitely intend to add this feature :)
I'm working on a big internal refactor atm, and I got slowed down by the change in Dataview. But I'll get to this and other FRs

**Comment by SkepticMystic** [comment]
@HEmile @mikkovedru @bricoleurSoul This has been implemented in the latest beta release!!
It is a breaking change, so you will need to reset your hierarchies in the settings and add them back again.
Let me know if you're open to testing it out on your side 🙂 You just need to manually install the latest release from this branch here: https://github.com/SkepticMystic/breadcrumbs/releases/tag/1.0.5

**Comment by BricoleurSoul** [comment]
All ready volunteered in private thread in discord (you come before my email 😏) so that is definite “I’m all in” …

David

**Comment by SkepticMystic** [comment]
Gonna consider this implemented. Please open new issues for specific bugs related to this feature :)
