### ISSUE TITLE
FR: Show on live preview mode!

### ISSUE THREAD

**Issue by brimwats** [SkepticMystic/breadcrumbs#157]
It could be that I have some setting wrong, but I was looking for breadcrumbs to show up on live preview mode. :)

**Comment by brimwats** [comment]
for the record/debugging, it *does* appear in transcluded LP notes: 

![image](https://user-images.githubusercontent.com/49103046/142937065-947ace51-2ae9-4ab7-9353-19ea3c6acca3.png)

**Comment by SkepticMystic** [comment]
Thanks for the FR Bri!
I'll definitely try do this now that the other features are out :)

**Comment by HEmile** [comment]
I'd also be happy with the option to have it in the editor, not just the live preview :)

**Comment by SkepticMystic** [comment]
@brimwats @HEmile this is working in 1.8.0 :)
Edit mode works alot better than live preview. You'll see there are some limitations in LP:
- Width is wider than readable line width
- Trail view is stickied to top of note, even when scrolling

I'll try iron these out, but the basic functionality is there.
