### ISSUE TITLE
Mobile version not working

### ISSUE THREAD

**Issue by joellti** [SkepticMystic/breadcrumbs#158]
It appears the mobile version (0.11.8) of this plugin is not working for me. As soon as I click "Refresh Index", I got following error logs in developer tool's console. I set up a test vault with only two notes in it (one as parent and the other as child) and I got the same result. The desktop version works well so I hope the same for mobile version because I have the same vault synced on both platforms.

```
TypeError: Cannot read property 'types' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6408:46)
    at Array.forEach (<anonymous>)
    at getFieldValues (eval at <anonymous> (app.js:1), <anonymous>:6404:23)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6493:47)
    at Array.forEach (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6492:34)
    at Array.forEach (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6491:28)
    at Array.forEach (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6486:25)
```

**Comment by joellti** [comment]
Did another test with version 0.10.75 on mobile (Android) and it's working so I guess it stops working somewhere between 0.10.75 and 0.11.8. Just FYI

**Comment by SkepticMystic** [comment]
Thank you @joellti :)
Indeed, the versions between those two were all filled with bugs! There was a change in the way Dataview returns data, so I had to account for that

**Comment by joellti** [comment]
No problem, if you need me to collect any additional data feel free to let me know :)

**Comment by SkepticMystic** [comment]
Thanks alot @joellti  :)
I've been working on a whooole bunch of changes in a new beta release.
It would be great to hear your experience if you're willing to try it!
You'll have to manually install from [here](https://github.com/SkepticMystic/breadcrumbs/releases/tag/1.4.0). You can read the changelog for this branch over [here](https://github.com/SkepticMystic/breadcrumbs/blob/nextPrev/CHANGELOG.md)

**Comment by joellti** [comment]
Yes I tried 1.1.1 yesterday and unfortunately it's still not working on mobile. I didn't capture the console logs this time but the behavior is the same as with 0.11.8.

**Comment by joellti** [comment]
Just tried 1.4.0 and it fails to be enabled with following console error logs:

app.js:1 
        
       Plugin failure: breadcrumbs SyntaxError: Unexpected token '?'
    at eval (<anonymous>)
    at app.js:1
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1
