### ISSUE TITLE
Hierarchy notes prevent a successful index refresh

### ISSUE THREAD

**Issue by natalie-foust** [SkepticMystic/breadcrumbs#159]
I've been having a major problem with hierarchy notes that seems to have persisted for a while (I recently upgraded from 0.10.75 to 0.11.8 and am having the problem in both versions). Bascially, my hierarchy notes seem to reach a point where **if I add one more note to my hierarchy notes, Breadcrumbs cannot refresh its index.** Once I remove the new note I can instantly refresh again. This happens regardless of which note is added or removed.

I *can* still add those same exact files to my breadcrumbs, I just can't do thru any of my hierarchy notes. For example, even tho my hierarchy notes seem to be "full" and won't accept any more children, if I declare the parenthood in the frontmatter, I can refresh my index without issue. 

Unfortunately, I turned on debug and super debug mode and I am not seeing any errors when I attempt a refresh. If you would like a blank copy of my notebook to test with I'm happy to provide.

This may be related to https://github.com/SkepticMystic/breadcrumbs/issues/150 but I didn't see any mention of if their problem was caused by a failure to refresh or the quantity of notes so I opted to make this issue.

**Comment by SkepticMystic** [comment]
@natalie-foust Thank you very much for the bug report. I will try investigating this.
I have completely overhauled how hierarchy notes are processed under the hood, so could you try out 1.8.0 and let me know if this still happens? You can see all the changes in the wiki page [here](https://github.com/SkepticMystic/breadcrumbs/wiki/Hierarchy-Notes)

**Comment by natalie-foust** [comment]
I'm sorry for my late reply but yes, I just got it updated and it totally seems to be working without a problem! Great work and thanks for the reply!
