### ISSUE TITLE
FR: Generate the Index like the MoC Plugin does

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#160]
The MoC Plugin basically generates its index purely via wikilinks already existing in notes. The trick is to define a central note, and the MoC plugin then creates a hierarchy based on shortest path(s) of a note the that central note.

I think a similar approach could be implemented by Breadcrumbs as well. The major advantage for this would be that it requires far less setup. I was thinking of using breadcrumbs, but defining yaml frontmatter or an index note is *so* much work in a bigger vault, while using a network of already existing wikilinks is almost no work (only need to setup a central note from which all clusters in your graph are linked to). And knowing that you also did the graph Analysis plugin, you probably have the code for stuff like shortest path calculation anyway? :o

**Comment by SkepticMystic** [comment]
Haha Breadcrumbs is actually very well set up to do this already!
There is already a setting to define a "Central Note" 😋 
I'll definitely work on this

**Comment by SkepticMystic** [comment]
@chrisgrieser perhaps for the time being, this feature and the one below it can fill the gap for you!
https://github.com/SkepticMystic/breadcrumbs/wiki/Alternative-Hierarchies#folder-indexes

**Comment by chrisgrieser** [comment]
could you add some documentation for `BC-traverse-note` to the wiki? It seems to be part of the public Breadcrumbs release, but isn't listed in the alternative structure yet.

As far as I can tell, there aren't any serious bugs anymore, and I'd like to dive into it, but I am not sure what exactly I can configure right now :)

**Comment by SkepticMystic** [comment]
I'll consider this closed now. I've added a section to the wiki for traverse notes :)
