### ISSUE TITLE
Bug: NotFoundGraphError on first init

### ISSUE THREAD

**Issue by mkasu** [SkepticMystic/breadcrumbs#161]
In 1.7.8, I get this issue when Breadcrumbs first initializes (e.g., when restarting Obsidian) for the note which currently happens to be open. I think it tries to evaluate the graph before the init finishes.

<img width="989" alt="Screenshot 2021-11-23 at 14 43 53" src="https://user-images.githubusercontent.com/798036/142976697-549effe2-1468-4373-bb97-c94f0e53a600.png">

**Comment by SkepticMystic** [comment]
For now, I just make it silently fail, and return an empty Graph. So you still have to manually Refresh Index, but atleast no errors.
I'll still try come up with a better solution, though

**Comment by SkepticMystic** [comment]
I've found a better workaround for this. Still not perfect, but BC should try build the graph twice if it hadn't finished previously

**Comment by SkepticMystic** [comment]
@mkasu do you still get this bug?

**Comment by SkepticMystic** [comment]
I believe this is resolved
