### ISSUE TITLE
Bug: Incomplete trails in 1.7.8

### ISSUE THREAD

**Issue by mkasu** [SkepticMystic/breadcrumbs#162]
On many of my notes I see incomplete trails, especially when having multiple paths to the home note.

E.g., If theres two paths to the home note:
`A -> B -> C -> D`
`A -> B -> E`

It would display as
`C -> D`
`A -> B -> E`

It seems it fails to find the correct path at the merging point of multiple paths, and then only shows the last full path and the other ones being cut off.

**Comment by SkepticMystic** [comment]
Thank you! Fixed in 1.7.9 :)
