### ISSUE TITLE
Breadcrumbs trail not working after update to 1.8.1

### ISSUE THREAD

**Issue by Victor-IT** [SkepticMystic/breadcrumbs#163]
Seems it broken again after 1.8.1 update.

**Comment by SkepticMystic** [comment]
Do you get any errors?
Do you have Live Preview enabled?
Can you try on 1.9.0 and let me know

**Comment by Victor-IT** [comment]
See no errors alerts.
Tried both mode "live on/off"
Current 1.10.1 version don't work too.

**Comment by Victor-IT** [comment]
Oh, found how to enable console to see errors.
![image](https://user-images.githubusercontent.com/26308124/143077790-e605fa03-d969-4061-9c19-1fc84e6a5217.png)

**Comment by SkepticMystic** [comment]
Ahh thank you, that error message helps alot.
I think it should be relatively simple to fix.

**Comment by SkepticMystic** [comment]
@Victor-IT @BricoleurSoul I think this is fixed in 1.10.2. Hard to tell because I couldn't reproduce, but I now have a safety check to ensure this will ensure

**Comment by Victor-IT** [comment]
Show in edit mode ON:
The title of the parent index note has been truncated.
![image](https://user-images.githubusercontent.com/26308124/143189645-28176d81-f5da-4308-9668-58a192427433.png)
![image](https://user-images.githubusercontent.com/26308124/143190001-ce555f1b-1f92-470a-8aa1-d00e7b662c62.png)

**Comment by Victor-IT** [comment]
In both mode - trail not working in preview.
