### ISSUE TITLE
Bug: Trail in edit view is truncated in some cases

### ISSUE THREAD

**Issue by Victor-IT** [SkepticMystic/breadcrumbs#166]
Show in edit mode ON:
The title of the parent index note has been truncated.
![image](https://user-images.githubusercontent.com/26308124/143189645-28176d81-f5da-4308-9668-58a192427433.png)
![image](https://user-images.githubusercontent.com/26308124/143190001-ce555f1b-1f92-470a-8aa1-d00e7b662c62.png)

In both mode - trail not working in preview.
![image](https://user-images.githubusercontent.com/26308124/143190581-685afa19-40aa-4d28-a250-5bbbf169d5ed.png)
![image](https://user-images.githubusercontent.com/26308124/143190693-cbeec431-283d-4b31-83ce-3f7d8c3924b2.png)
![image](https://user-images.githubusercontent.com/26308124/143190729-ec09618f-fe3d-4cee-960f-0cff09ce077c.png)

_Originally posted by @Victor-IT in https://github.com/SkepticMystic/breadcrumbs/issues/163#issuecomment-977587097_

**Comment by SkepticMystic** [comment]
@Victor-IT can you try 1.10.3

**Comment by Victor-IT** [comment]
Yay! Works now in both mode. But in edit still truncated INDEX title
![image](https://user-images.githubusercontent.com/26308124/143193501-d6701547-7387-430c-99a3-b07d69ee849c.png)
![image](https://user-images.githubusercontent.com/26308124/143193724-c939f0b8-4dee-4159-b486-b6cfa4ca7dae.png)

**Comment by SkepticMystic** [comment]
Good stuff!
About the truncation:
1. Do you have `Respect Readable Line Width` enabled under `Trail/Grid View` settings?
2. Do you have `Readable Line Width` enabled under Obsidian Editor settings?

**Comment by Victor-IT** [comment]
Tried enable/disable these settings - no result. Truncation still in effect.

**Comment by SkepticMystic** [comment]
Thanks for checking. I will have to investigate further

**Comment by ben1mit** [comment]
I also have this issue, although only in preview
