### ISSUE TITLE
FR: Command for toggling trail/grid in edit/lp mode

### ISSUE THREAD

**Issue by HEmile** [SkepticMystic/breadcrumbs#167]
Hi! It is super useful to have the trail/grid in edit mode, but sometimes it is a bit too large and unpredictable in size in my vault. That gets in the way of editing. It would be great if (like backlinks in edit mode), there is a toggle using a command so it is quicker to change this option.

**Comment by SkepticMystic** [comment]
Good suggestion! I can totally do that :)
