### ISSUE TITLE
In the link to csv, allowing filenames with [[ ]]

### ISSUE THREAD

**Issue by jakeoung** [SkepticMystic/breadcrumbs#169]
For the linking to csv function, I actually use a md file instead of a csv file, so that I can edit in obsidian. Could you consider supporting filenames with [[ ]] ?

For example, it supports something like:
```
file, up
[[test]], [[testP]]
```

In implementation, maybe we can just remove [[ or ]] characters. The reason I ask for is that when I change the note title, it will automatically reflect the change (when my file is a md file). I would very appreciate if you could support it!

**Comment by SkepticMystic** [comment]
This is now possible in 1.14.0 :)
