### ISSUE TITLE
bug: trail not working in 1.14.0

### ISSUE THREAD

**Issue by ben1mit** [SkepticMystic/breadcrumbs#170]
After I updated to 1.14.0 the trail is not showing up anymore. (just "this has no real or implied parents")
the view in the sidebar is working well.
After changing to trace mode, this is what happens in the console when attempting to draw the trail:

<img width="366" alt="Skjermbilde 2021-11-25 kl  11 03 03" src="https://user-images.githubusercontent.com/48367359/143420888-6992212e-47c4-4685-80c6-f0e8e65454f3.png">

the paths arr seems to be the correct path, but it doesn't get shown at the top of the file

**Comment by SkepticMystic** [comment]
Thanks for the detailed report. I'll have to see what's going on there... So you do get the `No Path Found` message, but it doesn't show parents even though it should?

**Comment by ben1mit** [comment]
I'm a bit uncertain what you mean by "no path found message", but I hope the picture below illustrates the problem well
<img width="1397" alt="Skjermbilde 2021-11-25 kl  13 09 22" src="https://user-images.githubusercontent.com/48367359/143439225-b727487a-133a-44ce-a13b-705161f9fa1f.png">

**Comment by SkepticMystic** [comment]
That does help, thank you!

**Comment by SkepticMystic** [comment]
Do you mind sending me the results of `app.plugin.plugins.breadcrumbs.settings`

**Comment by ben1mit** [comment]
where do I find that?

**Comment by SkepticMystic** [comment]
So open the console, then copy paste that cmd into the bottom line where you can enter code, `Enter` to run it, then just copy paste the result here

**Comment by ben1mit** [comment]
I get this:
<img width="615" alt="Skjermbilde 2021-11-25 kl  13 17 12" src="https://user-images.githubusercontent.com/48367359/143440300-a9f44a46-ad5d-41be-a7e1-64b9e1371a16.png">
however if I go into breadcrumbs menu and ask it to console log the settings I get  the following: 
CSVPaths: ""
HNUpField: ""
aliasesInIndex: false
alphaSortAsc: true
altLinkFields: []
debugMode: "TRACE"
defaultView: true
dotsColour: "#000000"
dvWaitTime: 5000
fieldSuggestor: true
filterImpliedSiblingsOfDifferentTypes: false
gridDots: false
gridHeatmap: false
heatmapColour: " #ffb86c"
hideTrailField: "hide-trail"
hideTrailFieldName: "hide-trail"
hierarchyNoteDownFieldName: "child"
hierarchyNoteUpFieldName: "parent"
hierarchyNotes: []
indexNote: ["root indexes index"]
indexNotes: ["book index"]
limitTrailCheckboxStates: {parent: true}
limitWriteBCCheckboxStates: {parent: true, sibling: true, child: true}
noPathMessage: "index not connected"
orderField: "order"
parseJugglLinksWithoutJuggl: false
refreshIndexOnActiveLeafChange: false
refreshIntervalTime: 0
refreshOnNoteChange: false
respectReadableLineLength: true
rlLeaf: true
showAll: false
showAllPathsIfNoneToIndexNote: false
showBCs: true
showBCsInEditLPMode: true
showGrid: false
showNameOrType: true
showPrevNext: true
showRelationType: false
showTrail: true
showWriteAllBCsCmd: false
superDebugMode: true
trailOrTable: 1
trailSeperator: "→"
useAllMetadata: true
userHiers: [{…}]
visAll: "All"
visClosed: "Real"
visGraph: "Force Directed Graph"
visRelation: "Parent"
wikilinkIndex: true
writeBCsInline: false

so there seems to be a lot of stuff that is set to false

**Comment by SkepticMystic** [comment]
Oh sorry, I made a typo. But yes, this is exactly what I need, thanks :)

**Comment by SkepticMystic** [comment]
@ben1mit it isn't showing trails because you have an index note set to `"Book index"`. 
If you have an index not set, then the trail only show paths going up to that index note. There are two solutions here:

1. Remove the index note to always show all paths
2. Toggle the setting `showAllPathsIfNoneToIndexNote` to `true`, to show all paths if none to the index note are found

**Comment by ben1mit** [comment]
Removed the index note, and that did not help. However suggestion 2 did help, thanks

**Comment by SkepticMystic** [comment]
Unfortunately, I can't reproduce the behaviour you experienced... I'm glad the workaround resolves it though
