### ISSUE TITLE
More space around trail view

### ISSUE THREAD

**Issue by ben1mit** [SkepticMystic/breadcrumbs#171]
This is a relatively minor aestethic thing, and could propably be solved on the user end by some custom css, but it would be nice with some more air around the breadcrumbs trail. As you see from the picture it is pretty mashed into the yaml preview and the title of the note, so adding a few pixels of spacing around the trail might be very nice.

<img width="696" alt="Skjermbilde 2021-11-25 kl  13 57 30" src="https://user-images.githubusercontent.com/48367359/143445790-b310db47-91c5-437c-b773-58e2b1a6cf50.png">

**Comment by SkepticMystic** [comment]
Sure, I agree it could use a bit more space. I've added a little bit of a gap, but you can add more with:
```css
div.BC-trail {
    margin-bottom: 10px;
}
```

**Comment by ben1mit** [comment]
I am unfamiliar with using css snippets in obsidian. 
I tried saving a file containing the code you pasted above, named "breadcrumb_air.css" within the folder vault/.obsidian/snippets
however it does not show up under snippets when i try to reload them from within the settings menu.
Am I doing it wrong, or should it work?

**Comment by SkepticMystic** [comment]
That _should_ work, yeah... I'm not sure what the issue is there
