### ISSUE TITLE
Index refresh fails when BC-link-note has a non-existing link type

### ISSUE THREAD

**Issue by minkkinen** [SkepticMystic/breadcrumbs#172]
I noticed that the index fails to refresh when a note has the metadata field BC-link-note with a non-existing link type. This happened because I changed the name of the downward direction for one of the hierarchies. It just says "Breadcrums graph is not initialized yet. Please Refresh index.". Everything works again when I update the BC-link-note field to the new name.

**Comment by SkepticMystic** [comment]
I can't recreate this behaviour. It's possible the breaking change to 2.0.0 yesterday has resolved this issue

**Comment by minkkinen** [comment]
Yeah, that's likely. I also realized after opening this issue that it looked like I had messed up my hierarchies somehow more generally. I reset all of my hierarchies and it worked again. The recent update probably changed the behavior so this issue might not be relevant.

**Comment by SkepticMystic** [comment]
Cool cool, thanks for checking :)
