### ISSUE TITLE
FR: Add Trail View to Sidebar

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#176]
On top of the Matrix and/or List view would be useful when you have scrolled down a document and therefore cannot see the trail anymore.

**Comment by kometenstaub** [comment]
If you try it on the insider build in live preview, it stays at the top all the time.

**Comment by SkepticMystic** [comment]
I feel like the updated Tree View (previously Down View) satisfies this FR. You can choose to show the `up` trail, which shows the same info as the trail view

**Comment by chrisgrieser** [comment]
Yep, all the new additions pretty much satisfy this <3
