### ISSUE TITLE
Turn off index refreshed message

### ISSUE THREAD

**Issue by gudstrand** [SkepticMystic/breadcrumbs#177]
I am edting a bunch of notes and adding hierarchies for breadcrumbs. The "index refreshed" message keeps flashing on the screen with every change, is there a way to turn off informational messages?

**Comment by SkepticMystic** [comment]
Sure thing, it's been added and will be available in the next release :)

**Comment by gudstrand** [comment]
Wow! Thank you, that was so fast!  :-)
