### ISSUE TITLE
not compatible with Obsidian build-in aliases feature

### ISSUE THREAD

**Issue by zhao414** [SkepticMystic/breadcrumbs#178]
I'm using YAML to create the relationship.

Note A.md looks like the following
```
---
aliases: note-A
---
This is note A
```

Then in note B, when I'm creating a relationship in a note B, with help of the add internal link command to look up the A.md, I can type "A" to get a internal link as : 
```
[[A]]
```
So the YAML will be 
```
up: [[A]]
```
And in this case, BC works fine.

However, Obsidian also allows me to type "note-A" to get a internal link as:
```
[[A|note-A]]
```
And in this case, the YAML will looks like:
```
up: [[A|note-A]]
```
This internal link [[A|note-A]] is understood by the Obsidian, i.e. it points to the A.md. However, the BC will take [[A|note-A]] as a link to A|note-A.md and make a wrong relationship.

Is there an option to ask BS to ignore the aliases when there is a "|" in the link name?

**Comment by SkepticMystic** [comment]
Huh, this definitely used to work. The bug must have been introduced in a new release. I'll see what I can do

**Comment by SkepticMystic** [comment]
This should be fixed in 2.1.0 :)

**Comment by zhao414** [comment]
Do you mean 2.10.0?

**Comment by SkepticMystic** [comment]
Well, it was 2.1.0 at the time :yum: but it should still apply in later versions
