### ISSUE TITLE
Not Working on Mobile

### ISSUE THREAD

**Issue by JepheDelPhuego** [SkepticMystic/breadcrumbs#180]
Will not work on mobile. No error messages, just shows up blank.

**Comment by SkepticMystic** [comment]
![](https://media.discordapp.net/attachments/707816848615407697/914961786288082944/3D8BB889-0AF1-45EE-ABD4-B393070C212A.png?width=325&height=702)

![](https://media.discordapp.net/attachments/707816848615407697/914961786489425960/1415E6A4-5DA0-4E53-A632-AA537886612D.png?width=325&height=702)

**Comment by dancemonkey** [comment]
Same here, YAML that works on desktop shows nothing on mobile.

**Comment by SkepticMystic** [comment]
@JepheDelPhuego @dancemonkey can you please let me know if your mobile is Android or iOS, as well as the last version of Breadcrumbs that worked for you on mobile

**Comment by JepheDelPhuego** [comment]
@SkepticMystic yeah I'm on Android 12 and my Breadcrumbs is version 2.4.0

**Comment by SkepticMystic** [comment]
@JepheDelPhuego what version of Breadcrumbs last worked on mobile for you?

**Comment by JepheDelPhuego** [comment]
@SkepticMystic tbh I couldn't tell you. I've had Breadcrumbs downloaded for awhile but didn't activate it until like the day before I tried it on mobile so it basically has never worked on mobile for me.

**Comment by SkepticMystic** [comment]
Fair enough, thank you for the feedback

**Comment by JepheDelPhuego** [comment]
No problem!

**Comment by mgmeyers** [comment]
Not sure if this is helpful, but I'm getting some more specific errors from the android emulator:

<img width="715" alt="Screen Shot 2021-12-03 at 11 11 54 AM" src="https://user-images.githubusercontent.com/2694747/144659510-09643b9d-c2e9-437c-90e6-1a495fd5fcc7.png">

**Comment by SkepticMystic** [comment]
@mgmeyers thank you!
It seems like an issue with leaves, then (The `NotFoundGraphError` is different).
This helps alot, I'll see what I can do

**Comment by dancemonkey** [comment]
I'm using Breadcrumbs for the first time on mobile. iOS 15.1.1. I get SOME connections made in the matrix view on the sidebar, but no views at all show up at the top of the page itself. It's pretty spotty, for instance my daily note has a parent, a next, and a previous, but I created a new page and set the daily note as ITS parent, but that relationship isn't showing up in the matrix at all. 

It's all showing fine on desktop as far as the matrix in the sidebar, hitting refresh makes all the connections show up in the matrix.

**Comment by cwhommes** [comment]
Breadcrumbs on mobile devices with IOS is not working in conjunction with Dataview. I am using Obsidian mobile 1.0.5, Breadcrumbs 2.9.0. and Dataview 0.4.21. On my desktop (WIndows) Breadcrumbs and Dataview work together flawlessly. On mobile devices only when turning off dataview. I have experimented with changing the 'Dataview Wait Time' but that does not solve this problem. Any suggestions?

**Comment by seishonagon** [comment]
Added data point:
not working on Obsidian mobile 1.0.5 (iOS) with Breadcrumbs 2.11.0, no dataview
I get "This note has no real or implied parents"

However, same vault synched on obsidian sync shows hierarchy with no issues. (except that the top level not, even if it's flagged in the settings as the main index, still has the "This note has no real or implied parents"

**Comment by dancemonkey** [comment]
I haven’t gone deep into it but next/prev definitely work, I’ll set up some more hierarchies and get back into it. Thanks! Looking forward to really using this to its full potential.

**Comment by cwhommes** [comment]
@SkepticMystic Thank you so much for fixing the plugin. It works like a charm. You made my day 🙏

**Comment by seishonagon** [comment]
> @JepheDelPhuego @dancemonkey @mgmeyers @cwhommes @seishonagon I believe I have resolved the main issue. BC is working on mobile for me! Please give it a try on your side when you are able (version 2.12.1), and let me know if you experience any other issues

It does seem to work well. The only remaining issue I have, which may be separate, is that my home index note gets a « this note has no real or implied parent »

**Comment by SkepticMystic** [comment]
@seishonagon that is a different issue, yeah. Can you add a bug for that. I agree that it shouldn't show on the home note
