### ISSUE TITLE
BUG: Wrong CSS Class Assignment in Matrix View

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#181]
Probably I was able to notice it quicker due to my custom CSS of Breadcrumbs; I noticed that the last update seems to have introduced a bug the Breadcrumb CSS.

The first square separates puts the h4 and h6 into one div, the second square puts them into two different divs. The result is that any custom styling done by themes isn't applied consistently anymore, leading in my theme to this visual bug:
<img width="658" alt="Untitled" src="https://user-images.githubusercontent.com/73286100/144032359-779c6864-a0cd-46ba-90ba-9ae2504cce41.png">
<img width="363" alt="Untitled 2" src="https://user-images.githubusercontent.com/73286100/144032366-5a38ae82-631a-42cc-a383-bda64d673a4e.png">

**Comment by SkepticMystic** [comment]
Fixed :)
