### ISSUE TITLE
FR: CSS Class for empty state of views

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#183]
similar to Vanilla Obsidian, it would be useful if breadcrumbs applied a separate CSS class for "empty" views (nothing to display in the sidebar, or `This note has no real or implied parents` in the trail view.)

This would enable theme designers like me to apply separate styling for those cases. :)

**Comment by SkepticMystic** [comment]
Oh good idea!
I'm gonna make it `div.BC-empty-view`

**Comment by SkepticMystic** [comment]
Added in 2.3.0
