### ISSUE TITLE
[BUG]: Giant Hook in Down view

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#185]
Not exactly sure what is going on here, but a giant hook icon appears in the down view panel?! (I switched to default theme at it still occurs)

<img width="585" alt="Screenshot 2021-11-30 13 39 40" src="https://user-images.githubusercontent.com/73286100/144049001-38cb4d88-eeed-42f4-87e1-a128f849ba31.png">

**Comment by SkepticMystic** [comment]
Hahahaha this must have been quite startling.
It happens because Graph Analysis uses the same styling for icons. So when I forgot to add the styles in BC, I still saw the correct size icon because GA was installed.
This is fixed in the latest release
