### ISSUE TITLE
[BUG]: Wrapping for Down View missing

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#188]
The down view is missing some wrapping and for some reason I not really understand, the "usual suspects" for solving this via CSS (`white-space`) does not work either. I think it's due to the horizontal scrollability or something? 🤔 

Anyway, It'd great if the content was visible without scrolling :)

<img width="362" alt="Screenshot 2021-11-30 15 38 20" src="https://user-images.githubusercontent.com/73286100/144067728-7d1a8490-7a48-4355-8a22-a191a1e935cc.png">

**Comment by SkepticMystic** [comment]
Hahaha you can't win, huh - I made it not wrap by request of someone else.
Doesn't `white-space: unset;` work?
I can make this optional

**Comment by chrisgrieser** [comment]
lol, haha, yeah sure, make one or the other simply optional, that's fine :P

(that one is also fixable via css, but it looked like a bug to me, so I was trying to think all the breadcrumbs users who not use my theme at the same time, too 🙃 )

**Comment by SkepticMystic** [comment]
An option has been added. Will be live in the next release (no wrapping by default 😋)
