### ISSUE TITLE
[BUG] Notes with certain characters (` - `) get truncated and broken links in Down view

### ISSUE THREAD

**Issue by emilyeserven** [SkepticMystic/breadcrumbs#189]
<img width="323" alt="Screen Shot 2021-11-30 at 11 52 42 AM" src="https://user-images.githubusercontent.com/13713374/144091577-1d196e86-5f76-49b0-b015-677daa33006a.png">

The above is showing with a note called `2021-11-08 - Frontend Dev Team Checkup`. 

I tried changing the name to other things, and they were not truncated the same way. (ex: `2021-11-08 + Frontend Dev Team Checkup`, `2021-11-08 _ Frontend Dev Team Checkup`, and `2021-11-08 . Frontend Dev Team Checkup` all worked.)

This doesn't occur in any of the other Breadcrumb views, just this one.

EDIT: As an aside, thank you so much for this new Breadcrumb Down view! I was literally thinking about how I wanted something like it yesterday while integrating Breadcrumbs into my vault. :)

**Comment by SkepticMystic** [comment]
Thank you for noting this bug, @emilyeserven  :)
It should be resolved in the next release
