### ISSUE TITLE
[BUG]: Dated notes don't work with Prev/Next in YAML

### ISSUE THREAD

**Issue by derekvan** [SkepticMystic/breadcrumbs#190]
Dated notes in YAML don't work with prev/next, although they do work in Dataview fields in the note. 

e.g.,

````
---
next: ['2021-12-02']
prev: ['2021-11-30']
up: ['2021-W49']
---
````

In the above case, the "up" field is represented in the list view, but the dated notes are listed as "same" not "prev" or "next"

**Comment by SkepticMystic** [comment]
Thanks for the bug report. Having spoken to the DV dev, a fix currently isn't possible, but should be in the next DV release

**Comment by derekvan** [comment]
quick note: if I change that YAML to this, it works (that is, if I add `.md` to the end of the link name):

````
---
next: ['2021-12-04.md']
prev: ['2021-12-02.md']
week: ['2021-W49']
---
````

**Comment by Triquetra** [comment]
I can confirm this is still an issue. I'm using DataView 0.5.41, Breadcrumbs 3.4.1, and Obsidian 0.15.6 on Windows 11. Putting next/prev in YAML does not produce a Next/Previous trail view. However, entering the same content as DV fields in the body does produce the Next/Previous trail view.

**Comment by SkepticMystic** [comment]
@derekvan can you check if this is still an issue in V4 (also considering the new Properties system in Obsidian)

**Comment by derekvan** [comment]
@SkepticMystic I stopped using those explicit fields in my notes long ago. However, the "jump to next neighbor by field:next" works on my dated notes, dated YYYY-MM-DD with that option turned on in the breadcrumbs settings. Does that answer your question?

**Comment by SkepticMystic** [comment]
Ok cool, that's helpful to know. I'll close this as complete in v4, then. For anyone coming to this issue, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
