### ISSUE TITLE
FR: support dendron style flexible hierarchies

### ISSUE THREAD

**Issue by h0uter** [SkepticMystic/breadcrumbs#194]
Hi,

I would like to use your plugin to navigate hierarchies based on dot indexed filenames.
(and eventually see these hierachies in a hierarchichal graph view)
As inspired by [dendron](https://wiki.dendron.so/notes/4bb85c39-d8ac-48ad-a765-3f2a071f7bc9/)

To give a short example:

`math.matrix.sparse` is a note about sparsity in the context of matrices.
I also have a higher level `math.matrix` note and above that a `math` note.

Similarly I have a `math.signal.fourier-transform` note whose parent is `math.signal`.
In this way a note can function both as a folder and a file.

Another plugin is also looking into this with from a different perspective [obsidian-structure](https://github.com/dobrovolsky/obsidain-structure)

cheers!

**Comment by SkepticMystic** [comment]
Interesting idea, I think the functional part of parsing the dendron would be relatively simple.
First issue is, how do I know where to look for files that should be parsed as such?
I think parsing ever file is unecessary, but what other means should I use? Maybe all notes in a folder?

**Comment by h0uter** [comment]
Cool!

Well I have all my notes as top level files in root, so if it is implemented so that we can select any folder including the root folder that would work for that usecase.

I guess you want to avoid filtering all files for files that have more than one `.` in the filename,
and then filtering again for an exact match of the part preceding the `.`
AKA how to distinguish top level dendron-style notes from non-hierarchical notes.

example: 
filter for `.` > 2  and find `math.matrix`
then filter again for exact match of `math` and find the `math.md` root dendron

**Comment by SkepticMystic** [comment]
@h0uter I've introduced this in 2.9.0 :)
It turned out to work pretty quickly when using all files, I made some optimisations.
To enable it, go to settings, and check under the `Alternative Hierarchies` dropdown. The settings should explain how to use it, but let me know if you have trouble.

**Comment by andrey-jef** [comment]
> @h0uter I've introduced this in 2.9.0 :) It turned out to work pretty quickly when using all files, I made some optimisations. To enable it, go to settings, and check under the `Alternative Hierarchies` dropdown. The settings should explain how to use it, but let me know if you have trouble.

Thanks for implementing this feature. However, I'm still not activate it successfully.
I'm using Obsidian v0.12.9, Breadcrumbs v2.9.0

This is what I did to activate structures with dendron-type notes
1. activate Breadcrumbs in `Community Plugins`
2. Open `Settings for Breadcrumbs Plugin`, click `Add new hierarchy`
3. Go to `Alternative Hierarchies`, enable the option `Add Dendron notes to graph`
4. Go to `Breadcrumbs` on the right side pane, click `Refresh index`

But nothing still happen as expected in the `Breadcrumbs` right side pane. Could you please show me where do I need to adjust?

**Comment by SkepticMystic** [comment]
@andrey-jef that sounds right.
There was a bug (#213) which I've just closed, that might have been affecting you too.
Please upgrade to 2.9.1 and give it a try again

**Comment by emillienemann** [comment]
@SkepticMystic thank you so much! That works really well. Is there any way to pin the view inside of my sidebar and be able to indent certain categories in the hierarchy?
