### ISSUE TITLE
wiki issue

### ISSUE THREAD

**Issue by brimwats** [SkepticMystic/breadcrumbs#197]
I followed the notes in the wiki for breadcrumbs

```
Go to a note you want to act as the index, and add BC-folder-note: true to it's metadata. This will take all other notes in that folder, and have them point upwards to that folder note.

By default, it will use the first up field name it can find. But you can also specify which up field name to use by adding BC-folder-note-up: fieldName to the folder note's metadata.
```

when i hit "refresh index" it logged an error about a deprecated value—thought i'd let you know!

**Comment by brimwats** [comment]
while I'm here (and to avoid filing another github issue), perhaps a wiki page on breadcrumbs CSS would be useful? 

the css you gave me

```
/* Trail CSS */
.breadcrumbs-trail .breadcrumbs-link {
	font-size: 10px;
	color: var(--base00);
}

/* Matrix CSS */
.breadcrumbs-matrix li,
.breadcrumbs-list li {
	font-size: 10px;
}
.breadcrumbs-trail-grid { 
	font-size: 10px;
}

```

does not seem to work in live preview.

**Comment by SkepticMystic** [comment]
@brimwats thanks for noting the wiki issue, I have changed it to the latest behaviour :)

**Comment by SkepticMystic** [comment]
And yes, the CSS will have broken. I changed the classes used. I can add a section in the wiki about the CSS that can be used :)
