### ISSUE TITLE
FR: "Ignore" option?

### ISSUE THREAD

**Issue by brimwats** [SkepticMystic/breadcrumbs#198]
I am still working on my hierarchies (always am!).

Because I use templater and quickadd pretty heavily I have a lot of fields that are essentially like `**↔ RT: [[<%tp.file.cursor()%>]]**` or `**NT⤵:: [[<% tp.file.cursor(3) %>]]** `

As you might imagine this leads to a lot of breadcrumbs links to "<% tp.file.cursor(3) %>"— is there a way to tell BC to ignore these?

**Comment by SkepticMystic** [comment]
Hahaha right... I agree this would be useful. Just need to think of an efficient way to implement it

**Comment by brimwats** [comment]
my initial thought, which might just be irrelevant is regex code (I was thinking of Another Quick Switcher's implementation, but i'm sure lots of plugins use regex with large amounts of files). could that be run on the final list that BC assembles?
