### ISSUE TITLE
Matrix on mobile no longer showing implied siblings

### ISSUE THREAD

**Issue by dancemonkey** [SkepticMystic/breadcrumbs#199]
The most recent update seems to have removed the implied siblings from matrix view, either that or a new toggle was added in settings that I’m not seeing. 

For instance my daily notes folder has a parent index note that is showing on the matrix as a real parent, but before the update I could also see all of the other daily notes in that folder as implied siblings. That is no longer the case. 

On iOS 15.1.1, Obsidian 1.0.5

**Comment by SkepticMystic** [comment]
Thank you for noting this.
Can you please check if 2.7.1 resolves it? There was a general bug preventing it from working on desktop, too.
@bodiequirk this should have fixed the issue you experienced earlier :)

**Comment by dancemonkey** [comment]
That did fix it, Matrix on mobile is showing implied siblings again. Thank you!
