### ISSUE TITLE
Context dependent index note

### ISSUE THREAD

**Issue by SkepticMystic** [SkepticMystic/breadcrumbs#20]
Based on the "type" of the note, it could have a different index (and therefore a different path entirely).

Maybe have a setting where the user specifies which note types lead to which indices:
```js
{ 
'#Type/Finance': '010 Finance',
'#Type/Hobby': '020 Hobby'
 }
 ```
 
- [ ] Can an object key be a string?

**Comment by tami5** [comment]
Yes that seems to be the best option. If the index is category/index.md. But in may case the indexes are organized in one directory.

Hmmm, maybe the user should define a root, default to `/`.

Then a setting to post process 
{

On another note, it might great if we can support the value being a number. So when it's a number the path to the directory will be `${root}`

**Comment by SkepticMystic** [comment]
Just getting my thoughts down. 
The function which finds a path up to `indexNote` already has the capability to find a path to _anywhere_. When drawing the trail, I should choose the most appropriate index based on the current note.
Technically, the user could provide a list of all indexes, and I could calculate _all_ the paths up to each once, then jsut pick the shortest.

**Comment by SkepticMystic** [comment]
@tami5 When you're able, will you also let me know if this works :)
You can now give a comma-separated list of different index notes, and the breadcrumbs trail will simply show the shortest of all the paths

**Comment by tami5** [comment]
> @tami5 When you're able, will you also let me know if this works :)
> You can now give a comma-separated list of different index notes, and the breadcrumbs trail will simply show the shortest of all the paths

Okay that's interesting take on the issue, again it definitely support hierarchical structure.

But in my case, I have all my index in a separate directory, and in my notes I have a field which hint to that file name in that directory :D, I'm even considering adding other field then type to donate a note being a part of index in another directory.

In all cases, your implementation is definitely for a wider use cases. I'll take a look later into this challenge. I can mentally frame it as "field index base", the yaml field control what index file it should be part of.
