### ISSUE TITLE
Bug: Hierarchies on mobile not indexed

### ISSUE THREAD

**Issue by selfire1** [SkepticMystic/breadcrumbs#200]
Hi! As discussed on Discord on mobile hierarchies are broken for me.

![Screenshot_20211204-183043~2.jpg](https://user-images.githubusercontent.com/70809675/144719601-8e606382-4774-4f7f-b3fd-e518c446baa0.jpg)

Neither in the index on the top nor in the breadcrumbs parents appear.

**Comment by veradrawer** [comment]
I'm experiencing this as well, I though it was on my side. Maybe a conflict?

**Comment by SkepticMystic** [comment]
@selfire1 @veradrawer please check if this still happens on 2.12.1, there was a significant bug on mobile I believe is now resolved

**Comment by veradrawer** [comment]
Can confirm it works! Good job!
