### ISSUE TITLE
Failed to load plugin breadcrumbs

### ISSUE THREAD

**Issue by mimishahzad** [SkepticMystic/breadcrumbs#201]
Hi! I love this plugin a lot for Obsidian,  but for some reason I get the following error in the console when I try to enable it... this has started happening recently (maybe 2 days ago?) Would you happen to know what the issue could be? Thank you so much for your time! 

``` json
VM197:formatted:1872 Plugin failure: breadcrumbs TypeError: Class extends value undefined is not a constructor or null
    at anonymous (eval at <anonymous> (app.js:1), <anonymous>:27528:41)
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
eval @ VM197:formatted:1872
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
(anonymous) @ app.js:1
e @ VM197:formatted:48231
```

**Comment by SkepticMystic** [comment]
Ohhh that's a weird one...
In the console, if you click `VM197`, can you send a screenshot of the code that appears

![image](https://user-images.githubusercontent.com/70717676/144756344-c9386fec-197d-43ee-aff1-ef1274c7f4c3.png)

**Comment by mimishahzad** [comment]
Hi! Thank you so much for looking into this! I appreciate it a lot! 
![image](https://user-images.githubusercontent.com/34081810/144757901-c3a78b90-b792-4c1a-9cc2-a7082f7e022e.png)
This is what I get formatted ↑ 
this is without the formmating: 
![image](https://user-images.githubusercontent.com/34081810/144757936-fa4558b0-aa42-4d9f-84ff-9a8d35fc2043.png)

**Comment by SkepticMystic** [comment]
Ooooff... this is a very ambiguous bug.
Are you using desktop or mobile?

**Comment by mimishahzad** [comment]
This is the first I’ve heard of it too… I’m on desktop on Mac if that helps a little 😅

**Comment by SkepticMystic** [comment]
@mimishahzad I haven't targeted this bug directly, but can you try 2.12.1 and let me know if this still occurs

**Comment by mimishahzad** [comment]
@SkepticMystic, so sorry about this, it started working again for some reason I should have closed this to begin with. Thank you for reaching out though, this plugin is amazing ☺️
