### ISSUE TITLE
FR: command to jump to next or prev note that can be given hotkeys

### ISSUE THREAD

**Issue by derekvan** [SkepticMystic/breadcrumbs#202]
Now that I have "next/prev" working for a bunch of my notes, would love to be able to assign a hotkey to a command that automatically navigated to the next or previous. I recognize that other folks might have multiple hierarchies with different next/prev labels, so this might be complicated. I'd be happy with an option that allowed me to assign the correct hierarchy to the command, or just automatically assigned it to the topmost hierarchy. 

Thanks for considering!

**Comment by SkepticMystic** [comment]
That's a great idea!
For now, I've added a command to `Jump to first {Direction}`. It works for up, down, next, and prev.
It just jumps to the first one it can find.
Can you please add another FR to add an option to specify which fields to filter by :)
