### ISSUE TITLE
FR: Option to specify default field to use for `BC-tag-note-field`

### ISSUE THREAD

**Issue by avirosso** [SkepticMystic/breadcrumbs#205]
Maybe this is a bug (or I missed something ...):

I've built only one hierarchy, based on tag structure, using "BC-tag-note:" in note's metadata (the Breadcrumb Stats showes 1599 Nodes and 1624 Read Edges)

The problem is, breadcrumbs plugin 'reverses' the directions up and down:
- In the "Breadcrumbs Down" pane' I see a list of links/note up in the hierarchy (the parent, the parent of first parent etc)
- In the "Breadcrumbs Matrix" pane first (on top) the child-Links are shown, at last (at the end) the parent-link is shown.
- The command "Breadcrumbs: Jump to the first 'down'" jumps up to the parent of the actual note (to the note with the "BC-tag-note:" for the tag). The  command "Breadcrumbs: Jump to the first 'up'" jumps down to the (alphabetically last) child-note.

**Comment by SkepticMystic** [comment]
Can you send an example of how you set it up?
It may just be that you need to add `BC-tag-note-field: someField` to that note.
If you don't add that BC just looks for the first `up` field it can find

**Comment by avirosso** [comment]
I have only one hierarchy defined, so there is only one 'up field' (called 'Up')

If I add "BC-tag-note-field: someField" to the note (I think correct is: "BC-tag-note-up: Up"), there is no change.

See  screenshots (simple example) attached (hope it helps)

Thanks
![A - Hierarchy definition](https://user-images.githubusercontent.com/95497044/145072428-83260178-62b4-49aa-b943-f4d53be28757.png)
![B - Parent](https://user-images.githubusercontent.com/95497044/145072434-5a41087d-e158-4b61-8448-ac74ab154739.png)
![C- Child](https://user-images.githubusercontent.com/95497044/145072437-08e953a4-caba-4a75-8eec-954849178ebc.png)
!

**Comment by SkepticMystic** [comment]
Try adding `BC-tag-note-field: Down`

**Comment by avirosso** [comment]
OK - this works! (thanks)

But: This is a strange behaviour (and should actually work without this "BC-tag-note-field: Down" - or?)

Do I now have to add this "BC-tag-note-field: Down" to all my notes with "BC-tag-note:" as a workaround (hundreds of notes)? 

Or will there be a 'fix' (new plugin version) for this strange problem?

Thanks!

**Comment by SkepticMystic** [comment]
Well, it is the intended behaviour. Some users might argue that it should use the first `up` field it finds. I guess I agree that the first `down` field makes the most sense. But it would be a breaking change. Maybe I can add a setting for this, so that you can choose the default field for tag-notes to use

**Comment by DevJake** [comment]
I'd appreciate this too. When I create a sort of 'index' note that references to all other notes with a given tag, I would expect it to refer to them as children notes, not parents. Setting a default for this field would be great as without `BC-tag-note-field: child`, they all default to parents.

I'm still trying to get to grips with the plugin, and so I'm not entirely sure why it would default to `parent`? 

Many thanks.

**Comment by SkepticMystic** [comment]
@avirosso @DevJake I've just added an option to choose a default field for tag-notes. Under `Alternative Hierarchies > Tag Notes` :)
