### ISSUE TITLE
Bug: Items in matrix sorted by filename, not by specified field name

### ISSUE THREAD

**Issue by veradrawer** [SkepticMystic/breadcrumbs#206]
Hi, I've seen that sorting has been added, nice! I've found that the matrix view does work as intended, except when defining a field for the title, like 'alias' or so.

For example, I get this matrix view in the `_index` file:

![imagen](https://user-images.githubusercontent.com/75331117/145093637-12693d41-1aec-4327-bfd5-e95b07d0cdae.png)

Strange. I check out the options, and everything is checked as intended.
Later, I realized that the sorting is happening by filename, not by the displayed name.

![imagen](https://user-images.githubusercontent.com/75331117/145093989-7af98e77-7138-488a-b79c-7149754071bf.png)

**Comment by SkepticMystic** [comment]
Ahh you're absolutely right, thanks for noting!
This should be an easy fix

**Comment by SkepticMystic** [comment]
Fixed in 2.9.3 :)
