### ISSUE TITLE
FR: Sorting toggle button in matrix view

### ISSUE THREAD

**Issue by veradrawer** [SkepticMystic/breadcrumbs#208]
When I'm navigating notes I benefit from using an alphabetically ordered list, most of the time.
The daily notes are an exception of this.

![imagen](https://user-images.githubusercontent.com/75331117/145095128-b71bf715-abd2-4d13-bfb8-76a563aed262.png)
_“Yup, I'd love to have at hand the first daily note at all times!”_

Jokes aside, I believe any other option would be overkill (defining sorting type by relationship. for example).
Having a button next to reload to toggle the sorting order does the trick.

**Comment by SkepticMystic** [comment]
I've added this in 2.9.3 :)
