### ISSUE TITLE
Dataview separator?

### ISSUE THREAD

**Issue by that0n3guy** [SkepticMystic/breadcrumbs#209]
I often use a single line like so: 
`Prev:: [[June Mastermind - Scalable]] | Next:: [[August 2021 Mastermind Founders Board - Scalable]]`
I've done it in my dailies for a long time `← [[2021-12-07]] | [[2021-12-09]] →`

Is there away to make it so the pipe `|` is recognized as a separator between the data items?

Right now, a line like: `Prev:: [[June 2021]] | Next:: [[August 2021]]` would read both the june and august pages as "prev".

**Comment by SkepticMystic** [comment]
I get you.
Currently, I just take the info that Dataview gives me. To parse it again like this would take alot of computation time - I don't think I'll add support for this. I think the best place it could be done is in Dataview itself, perhaps post a FR there

**Comment by that0n3guy** [comment]
Thanks!
