### ISSUE TITLE
FR: Sortable Matrix View

### ISSUE THREAD

**Issue by that0n3guy** [SkepticMystic/breadcrumbs#210]
I have my notes setup with a "next::" in them:
![image](https://user-images.githubusercontent.com/113870/145237786-fba84cd0-e63b-4b48-b09f-fe8e449adb15.png)

Every previous note points just to the next one.   The previous is implied.

When I go to the parent, I don't see the order showing up by relationship.  You can see this is alphabetical:
![image](https://user-images.githubusercontent.com/113870/145237976-7d5ab080-b2bf-4365-9eed-2a84ba2da8aa.png)

it shoudl show more like: 
```
May
June
July
August
...
```

**Comment by SkepticMystic** [comment]
Ahh this is interesting...
It'll take some thought, but I'll consider trying to implement this

**Comment by SkepticMystic** [comment]
I've added this in the latest release, available via the BRAT plugin under the V4 beta. See the top link in the README for more info
