### ISSUE TITLE
Should it work in Linux?

### ISSUE THREAD

**Issue by kmaustral** [SkepticMystic/breadcrumbs#211]
I can't generate Breadcrumbs on my Linux version 0.13.7 on a Chromebook. I receive a notice that the index is refreshed but the Matrix view is empty. The same configuration works fine with this vault on the Windows app. 

Are there special options that should be enabled for Linux?

**Comment by SkepticMystic** [comment]
Huh, it _should_ work on Linux.
Sometimes you have to refresh the index a couple times for it to work.
Did you have it working on a different OS before?

**Comment by SkepticMystic** [comment]
@kmaustral can you test 2.12.1 and let me know if this still occurs?
I'm not sure what causes this bug for you, but I think a different change I made may affect this
