### ISSUE TITLE
Trail view does not respect the assigned alias YAML field, but Matrix view does

### ISSUE THREAD

**Issue by blackace72** [SkepticMystic/breadcrumbs#212]
In the settings, the **Fields used for Alternative note names (Aliases)** section says the alias will be used "in *both* the list/matrix view, and trail/grid view". However, only the matrix view is showing the alias of a parent note, while the trail view is not (and they should be the same). 

I set the field to be `bctitle`. The parent note has the YAML `bctitle: foo`. I have tried putting in child's YAML `up: [[bar|foo]]`, and also tried just `up: [[bar]]`, but that didn't affect it. I am not sure if I am doing something wrong. Thanks.

**Comment by SkepticMystic** [comment]
Thanks for the report!
I don't think you're doing anything wrong, I think just forgot to make it work in the trail view :yum: I'll fix that when I get a chance

**Comment by SkepticMystic** [comment]
@blackace72 this should be working in the latest version :)
