### ISSUE TITLE
A bug on the alternative hierarchy

### ISSUE THREAD

**Issue by jakeoung** [SkepticMystic/breadcrumbs#213]
I have a note `set` and want to make another note `set.relation` a child of `set`. I enabled the option of the alternative hierarchy.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/2376897/145635318-a9e1a29a-a2be-4558-884c-7bc9079fb99e.png">

If I have a child in my note, it doesn't show (top), but if I remove the child, it appears (bottom).

---
For test, if I just add in the yaml `child:aa` it works, but `child: ['a']` doesn't work

**Comment by SkepticMystic** [comment]
Hey @jakeoung :)
This should be resolved in 2.9.1, please give it a try and let me know

**Comment by jakeoung** [comment]
Hey. It is fixed:) Thanks a lot :) This new feature is very useful to me!
