### ISSUE TITLE
Trim notes’ name in Breadcrums sidepane for Alternative Hierarchy

### ISSUE THREAD

**Issue by andrey-jef** [SkepticMystic/breadcrumbs#214]
With the v2.9.1, Breadcrumbs now can visualize and navigate the notes with hierarchy from a Dendron vault. Thanks so much for you work
![image](https://user-images.githubusercontent.com/81280428/146038914-8bd76252-6c70-494e-8521-ffdfecb214dd.png)

In Breadcrumbs plugin on right side pane
Example: i am currently at hierarchy note `notes.reading.textbook`
I wanna know if it is possible to display the note's name as `textbook` only, instead of full hierarchy? Similar naming behavior for `up`, `same`, `down` hierarchy level

**Comment by SkepticMystic** [comment]
I can definitely add an option for that!

**Comment by SkepticMystic** [comment]
Added in 2.9.3

**Comment by andrey-jef** [comment]
Omg. Thanks for implementing so fast. I gotta look at your script to learn how did you do the trim part 😍

**Comment by SkepticMystic** [comment]
Haha sure thing :)
You can check out the commit that added the feature here: https://github.com/SkepticMystic/breadcrumbs/commit/16defd6b1e186b34449c9b34fb6487cdc2e1ba27
