### ISSUE TITLE
Bug: Hierachy notes overflow into the next hierarchy note

### ISSUE THREAD

**Issue by natalie-foust** [SkepticMystic/breadcrumbs#216]
This is a minor bug that comes from user misconfiguration, but I figured I would let you know anyway. Just seems to be some unexpected behavior that is easily fixable on the user-side for now but could perhaps lead to bigger headaches later. Happened in version 2.9.2

**The Problem:** When a hierarchy note ends with an item without any children, the first item in the _next_ hierarchy note is made its child. 

### Example
_**Step 1.** Declare Note-X and Note-Y as Hierarchy Notes. Note-Y comes immediately after Note-X in the comma separated list._
`file: .obsidian/plugins/breadcrumbs/data.json`
```json
  "hierarchyNotes": [
    "...",
    "Note-X",
    "Note-Y",
    "..."
  ]
```
_**Step 2.** Create the hierarchy notes `Note-X` and `Note-Y`. By user error the last entry in `Note-X` does not have any children._

`file: Note-X`
```yaml
- [[Note-A]]
  - [[Note-B]]
  - [[Note-C]]
- [[Note-D]]
```

`file: Note-Y`
```yaml
- [[Note-E]]
  - [[Note-F]]
```
_**Result:** Note-D will be made the parent of Note-E and the user likely will have no idea why this is._

**Comment by SkepticMystic** [comment]
Ahh I think I see where the issue is. Thank you for such a detailed bug report :)

**Comment by SkepticMystic** [comment]
Please let me know if this still happens on 2.9.3
