### ISSUE TITLE
[BUG]: `BC-tag-note` is case sensitive + points in the wrong direction

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#219]
Both issues are recorded here, `BC-tag-note` seemingly makes all notes with the tag point *down* to the note, instead of up, and it seems to be case sensitive, while Obsidian doe snot care about case when it comes to tags.

https://user-images.githubusercontent.com/73286100/146679486-876b2613-3ca8-4528-9c3c-7ef8dc9413f1.mov

**Comment by SkepticMystic** [comment]
Regarding the direction issue, this has been addressed in a previous post. You need to use the `BC-tag-note-field:` key to indicate the direction. I agree that the default is not intuitive, but there is the option to specify a field.

About case-sensitivity, yeah that's a bug! Thanks :)

**Comment by chrisgrieser** [comment]
then the wiki might be a bit outdated. It [says there](https://github.com/SkepticMystic/breadcrumbs/wiki/Alternative-Hierarchies#tag-notes) that adding `BC-tag-note-up:`, but after your comment here I tried out a bunch of options till I figured out that its `BC-tag-note: down` I need to add 😅

**Comment by chrisgrieser** [comment]
okay, now I am a bit confused. it seems that whatever I do, `BC-tag-note` always points up instead of down? Am I missing something or what exactly is the proper syntax? 🤔 

https://user-images.githubusercontent.com/73286100/146688765-1ae21c6b-37df-4f16-9907-ed50b1d9e210.mov

**Comment by SkepticMystic** [comment]
@chrisgrieser the syntax to override the default tag-note direction is `BC-tag-note-field: field`

**Comment by chrisgrieser** [comment]
thank you, that finally did it! Now I can finally properly set up my hierarchies! 😭
