### ISSUE TITLE
Threading Mode

### ISSUE THREAD

**Issue by crazymedguy** [SkepticMystic/breadcrumbs#221]
Hello, I was wondering if it would be possible to implement this idea.

1. Firstly, I create a note. For example, I write about what a Zettelkasten is, that it's a card system that uses slip boxes.
2. Next I would like to automatically create a sibling note, and have a link automatically created on this first note. Perhaps by pressing a keyboard shortcut (ctrl-shift-right), or a slash command (/next)?
3. When entering the second note, it would already have an automated "prev" metadata populated with the previous note. 

I also wonder if this can be implemented to explore other types of relationships, not just siblings. For example:
* to create a child, ctrl-shift-down or /down
* to create a parent, ctrl-shift-up or /up
* to create same, ctrl-shift-. or /same
* to create a previous sibling, ctrl-shift-left or /prev
* to create an orphan, ctrl-shift-/ or /new

This would create almost like a gamification interface which is seamless, and also doeable on Mobile through slash commands. Almost like driving through your notes in real-time.

**Comment by SkepticMystic** [comment]
Ahh I like this idea alot!
Shouldn't be too hard, I'll get to it when I can :)

**Comment by crazymedguy** [comment]
> Ahh I like this idea alot! Shouldn't be too hard, I'll get to it when I can :)

That's awesome :))) I'm confident a lot of people will love this mode - they just don't know it yet. 🙌🙌

**Comment by SkepticMystic** [comment]
@crazymedguy @omarali-koy this has been added in 2.14.0! Let me know how it works for you.
There will be a few new commands called `Create a new '<field>' from the current note`. It will create a new note as the <field> of the previous note, as per the FR. It writes to both the old and new note. It uses the setting `Write BCs to file > Write BCs inline` to determine whether the fields are written to yaml, or as Dataview inline fields.

**Comment by crazymedguy** [comment]
Super grateful for this mode! Been playing around with them and some feedback - would it be possible to open up "newly created" notes in a new side-by-side panel? For example, if I'm going Andy Matuschak style, I would then have a trail of notes going >>>>. Just thinking out loud. Or some kind of navigation GPS UI that lets me know where I am in a 'train of thought' would be really cool.

**Comment by SkepticMystic** [comment]
Hmmm I can definitely do that. I wonder what the best way to implement it will be, because I know some users will prefer to open the new note in the current pane, instead of splitting as you suggest.
So I think I'll make a setting for it, `Thread into current pane or new pane`.
