### ISSUE TITLE
Use createFragment in setDesc in SettingTab

### ISSUE THREAD

**Issue by kometenstaub** [SkepticMystic/breadcrumbs#222]
For the descriptions in the settings you often use `inline code`. [`setDesc`](https://github.com/obsidianmd/obsidian-api/blob/c148c24b30dc68d9835820b4169b95d3a038a0f6/obsidian.d.ts#L2746) accepts either a `string` or a `DocumentFragment`. Currently, you use `string`. This does not resolve the `inline code` as code but renders it as normal text. [(Example)](https://github.com/SkepticMystic/breadcrumbs/blob/0ff1ae4f18e17ded3e59ab799df74804608ea289/src/BreadcrumbsSettingTab.ts#L169)

To render it correctly, you'd need to use [`createFragment`](https://github.com/obsidianmd/obsidian-api/blob/c148c24b30dc68d9835820b4169b95d3a038a0f6/obsidian.d.ts#L163).

See [this](https://github.com/kometenstaub/linked-data-helper/blob/a16342ed67cc7ea5a5beee9d5493c2c422a85faf/src/settings.ts#L80) for an example.

**Comment by SkepticMystic** [comment]
Haha you're right, I'll use that instead!

**Comment by SkepticMystic** [comment]
I've changed _most_ of the relevant settings to use a documentFragment instead
