### ISSUE TITLE
[FR] Reorder Matrix View

### ISSUE THREAD

**Issue by ConnorMeyers** [SkepticMystic/breadcrumbs#224]
- Feature Request - 
The ability to reorder the cells of the matrix view. Currently, the matrix is ordered according to the static hierarchy order of (⬆️ ↔️ ⬇️ ➡️ ⬅️). My desire is to reorder these (e.g.: ⬆️ ⬇️ ↔️...) 

- Motivation -
My notes end up having a lot of siblings, and the child-parent relationship is more valuable to me than the sibling relationship. I often have to scroll to view the children of a note in the matrix view.

**Comment by SkepticMystic** [comment]
I can try implement this, yeah :)

**Comment by SkepticMystic** [comment]
@ConnorMeyers I've added this in the latest release. You'll see the setting to change order under `Matrix/List View` settings.
Does this make sense? I know it could be more intuitive, but it works. This current order completely reverses the default order:
![image](https://user-images.githubusercontent.com/70717676/147857386-c202080f-89a6-4a8e-9b31-deed64c090a3.png)

**Comment by kazerniel** [comment]
@SkepticMystic Hey, I found this thread because I can't see in Breadcrumbs V4 how to reorder the fields in matrix view. Could you help please? :)
