### ISSUE TITLE
Minor Bug: Tooltips occur in the wrong direction

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#225]
When breadcrumbs is in the *left* sidebar, tooltips still occur to the left, with this result. 
<img width="318" alt="Screenshot 2021-12-28 12 40 06" src="https://user-images.githubusercontent.com/73286100/147562771-171a1e85-b556-4784-98a2-f012c3bcde6b.png">

This can probably be easily fixed with changing the aria label direction if in the left sidebar?

**Comment by SkepticMystic** [comment]
Thanks! I'll fix that now
