### ISSUE TITLE
FR: Matrix - Option to only show real relationships

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#226]
(would want that feature in rl as well lol)

currently, we can only turn off implied siblings across different parent-hierarchy types. However, I would like to have a feature to turn off implied relationships entirely in the Matrix View.

**Comment by SkepticMystic** [comment]
Yeah, I can do that

**Comment by SkepticMystic** [comment]
I've added this in 2.20.0 :)

**Comment by chrisgrieser** [comment]
Thanks 🥳
