### ISSUE TITLE
breadcrumbs matrix does not show inline metadata

### ISSUE THREAD

**Issue by crazymedguy** [SkepticMystic/breadcrumbs#227]
when we have `up:: [[page]]` it doesn't show up in the breadcrumbs matrix - but it works when you have YAML frontmatter. Not sure if this is a bug?

**Comment by crazymedguy** [comment]
Just realised it was more of the lag than a real bug.

**Comment by SkepticMystic** [comment]
Yeah, must've just been the time it takes Dataview to index the new entry
