### ISSUE TITLE
Create new *child* doesn't work twice on the same file

### ISSUE THREAD

**Issue by omarali-koy** [SkepticMystic/breadcrumbs#228]
I tried to create a new child note from a file.
- It worked the first time just fine.
- The issue is when I try to repeat the action on the same file.

The problem is that the file name already exists.
![image](https://user-images.githubusercontent.com/54885196/147856375-107b4bb0-5843-41c1-a808-1d7448b428fb.png)

An easy fix is to create a new note with numbering at the end. Works similarly when creating new notes:
- untitled
- untitled 1
- untitled 2

**Comment by SkepticMystic** [comment]
A bug indeed! Thanks omarali-koy, I'll fix this soon :)

**Comment by SkepticMystic** [comment]
Fixed in latest :)
