### ISSUE TITLE
Suggestions for threading mode

### ISSUE THREAD

**Issue by crazymedguy** [SkepticMystic/breadcrumbs#229]
Hello, thank you for opening up so many possibilities in Obsidian with this plugin. Some ideas/suggestions for the new Threading mode (which is phenomenal btw):

* Moving the text cursor to the next line after inserting an inline attribute. Currently the text cursor by default stays at the front of the note, so there are added steps to need to go to the end of the inline attribute `prev: [[page]]` and hit Enter. This would reduce a lot of friction too.
* I've been thinking about the automatic naming convention of newly created threads. Because after going a few levels deep, you tend to end up with "next of next of next of next of... page" 🤣
  * An idea that came up was the core plugin in Obsidian - a Zettelkasten prefixer that puts it in `YYYYMMDDHHmm`
  * Or maybe `page-a` → `page-b` → `page-c`? Would be relevant especially for prev → next relationships.
* Would also be cool if we could see an entire linear sequence of next-prevs in a thread (like a forum thread / twitter-thread / etc).

**Comment by mikkovedru** [comment]
> * I've been thinking about the automatic naming convention of newly created threads. Because after going a few levels deep, you tend to end up with "next of next of next of next of... page"

Perhaps some kind of number scheme can be used. Like "next(3)", "2nd next", or similar.

**Comment by SkepticMystic** [comment]
@mikkovedru @crazymedguy I've implemented Threading Templates. Have a look in settings, under `Commands > Threading`.
I also add an incrementing value to the name if a note with that name already exists

**Comment by crazymedguy** [comment]
Amazing! Thank you :)

**Comment by SkepticMystic** [comment]
@crazymedguy you can now use a custom date format, and the cursor will start at the end of the new note, instead of the beginning :)

**Comment by SkepticMystic** [comment]
Regarding your last point:
> Would also be cool if we could see an entire linear sequence of next-prevs in a thread (like a forum thread / twitter-thread / etc).

Can you make a separate FR for this?

**Comment by SkepticMystic** [comment]
Oops, I forgot to push the changes. The new release should now have custom date templates, and the cursor starts at the end of the new file
