### ISSUE TITLE
FR: Templater Templates in Threading Mode

### ISSUE THREAD

**Issue by shabegom** [SkepticMystic/breadcrumbs#232]
I'm getting into Breadcrumbs with the new threading mode.

I like that I can define a template for a note title, but what I would **love** is to be able to define a templater template that would fire when I created a new threaded note.

Bonus points if I can define different templates for parent, sibling, child etc.

My first use case would be to use a suggester modal to enter a new name for the note. I don't see myself using the auto-generated names.

I'm sure I could think of other fun use cases for this.

**Comment by SkepticMystic** [comment]
Haha that's awesome to hear!

Hmmm, I like these ideas alot. First thing, does Templater expose an API to insert and resolve a template? That would make this alot easier. 

I can definitely allow for different templates for different directions. I wonder what is easiest, to have settings where the user says "This direction uses this templates", or to allow the user to choose a template each time the cmd runs.

I also appreciate that you don't find the template names useful, me too. Perhaps there can be a setting, which, if enabled, pops up a modal to choose a name first? But having Templater would allow this, too

**Comment by shabegom** [comment]
Wow, fast response!

1. I _think_ if the setting to trigger template on new note creation is turned on then it should run as soon as the threaded note is made. In buttons I have a janky method that fires the "Replace Templater" command: `app.commands.executeCommandById( "templater-obsidian:replace-in-file-templater")`

2. I would want to set the template in the settings and not have to select each time, similar to setting a Daily Notes Template. I think it would be less friction. If say I have different types of child notes, I could use templater commands to insert different data.

3. I like the modal idea as an alternative for renaming. Another approach would be to put the cursor in the note name with the existing text selected. Then all I would have to do is type in a new name and hit enter to get going.

I think the auto-generated names could be useful for folks who are doing some form of atomic note structure where knowing something is a child is useful. I'm trying to use this as a way to branch off from my daily note and so I usually have a topic in mind.

**Comment by SkepticMystic** [comment]
Ok, so I'm working on the Templates for each direction feature. But there is a bit of ambiguity. Currently, the Threading command inserts a breadcrumb pointing to the previous note, right `down:: [[Previous]]`. But where should that appear in the template? There is no right answer. So, I'm gonna check the template for `{{BC-Thread-Crumb}}` (case-insensitively), and add the breadcrumb there.
What are your thoughts, @shabegom?

**Comment by SkepticMystic** [comment]
@shabegom so a couple new features :D
You can now choose a template for each direction
![image](https://user-images.githubusercontent.com/70717676/147910382-d7783d32-79f3-4046-b68b-d53f1c737ad9.png)

And, if you leave the note name template blank, then the mouse will focus on the note name input el for you to immediately change the note name.

**Comment by shabegom** [comment]
Amazing!!! Thank you!

**Comment by SkepticMystic** [comment]
@shabegom 

1. Ahh indeed, I'll add a check to make it only run once.
2. For this, if you add `{{BC-thread-crumb}}` to the Templater template, it will be resolved the way you're wanting

**Comment by SkepticMystic** [comment]
Gonna close this out. Thanks for the suggestions, and please do post further FRs or bugs that come up :)
