### ISSUE TITLE
See entire next-prev sequence

### ISSUE THREAD

**Issue by crazymedguy** [SkepticMystic/breadcrumbs#234]
> Would also be cool if we could see an entire linear sequence of next-prevs in a thread (like a forum thread / twitter-thread / etc).

New thread as requested!

**Comment by crazymedguy** [comment]
Was thinking that it could be simply embeds on a parent page:

Parent
![[A]]
![[B]]
![[C]]
![[D]]

Where A => B => C => D

Would be pretty cool indeed, and have it auto-populate as the 'thread' becomes longer. I'm not too sure what to do with forks though

**Comment by SkepticMystic** [comment]
@crazymedguy @chaecramb I've added Breadcrumbs codeblocks in the latest release :D
There is a whole bunch of potential here, and one thing it can do is show a thread of next/prev notes!
Go to the "first" note in the thread, and add:

````
```breadcrumbs
type: tree
dir: next
```
````

Let me know how this works :)

**Comment by crazymedguy** [comment]
Just tried it out - was wondering if it would be possible to present them as a flat threaded structure (like the forum here) instead of a continuously indenting structure, because threads can get quite long too

**Comment by SkepticMystic** [comment]
@crazymedguy I was also thinking that. One downside is that a flat structure doesn't show forks, so that meaning is lost. But I will make it optional.
If you add `flat: true` to the codeblock, it will be flat

**Comment by SkepticMystic** [comment]
This has been added in 2.24.0 :)

**Comment by crazymedguy** [comment]
You could make it collapsible maybe? :) 
Like a reddit thread with a [+]

**Comment by SkepticMystic** [comment]
@crazymedguy haha I like both of these ideas. Can you make separate FRs for both 😅

**Comment by SkepticMystic** [comment]
@crazymedguy checkout the latest version :D
If you add `content: true`, it will allow you to fetch the note content

**Comment by SkepticMystic** [comment]
@crazymedguy I've already changed this!
Use `content: open` or `content: closed` to show the content of each note, with the dropdown open or closed

**Comment by SkepticMystic** [comment]
Gonna close this out, thanks for prompting the idea for BC-Codeblocks :)
