### ISSUE TITLE
Add support for nested/recursive tags for BC-tag-note frontmatter field

### ISSUE THREAD

**Issue by DevJake** [SkepticMystic/breadcrumbs#236]
Hey there! Great plugin, I'm enjoying getting up to speed with things. However, I've noticed that the `BC-tag-note` field doesn't seem to support nested tags. So if I had the following structure of tags:

- `#A`
- `#A/B`
- `#A/C`

Such that `#B` and `#C` are children of `#A`, if I were to set a note to accept `BC-tag-note: '#A'`, it would recursively include all nested tags. Whilst this is useful in some scenarios, it's also an issue in others. An optional field, such as `BC-tag-note-explicit: [true/false]` or `BC-tag-note-depth: [int; 1 for ignoring nesting]` to only accept notes with a top-level tag (ignoring nesting) would be perfect! 

There might be a potential workaround for this now, but since I'm still getting to grips with things, I'm not sure. I appreciate any input that can be offered!

**Comment by SkepticMystic** [comment]
Hmmm I see, I see. So this isn't a feature request for a `BC-recursive-tag-note` feature. More a request to be able to limit which tags get included?

**Comment by DevJake** [comment]
Yes, absolutely! At the moment, tags are included recursively. To disable recursive tags on selective notes with the `BC-tag-note` field would be great!

**Comment by DevJake** [comment]
Just tested it out and it works brilliantly. Thank you so much for your speed in adding this in!!
