### ISSUE TITLE
Bug: no tooltips shown anymore

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#238]
probably related to #225, there are now no more tooltips showing at all :(

**Comment by SkepticMystic** [comment]
That's weird, it works for me on both sides.
![image](https://user-images.githubusercontent.com/70717676/148360781-02d24929-2c09-4dfb-ab44-8d749a8be9e5.png)

The side of the tooltip depends solely on the value of `Settings > Views > Matrix/List View > Open View in Right or Left Side`

**Comment by SkepticMystic** [comment]
The tooltip only shows for implied siblings

**Comment by chrisgrieser** [comment]
ah, having turned of implied siblings, I was wondering why no tooltips ever occurred 🤣 

got it, sorry for missing this!

**Comment by SkepticMystic** [comment]
Hahahah maak sin 😋
