### ISSUE TITLE
[BUG] Trail view crashing but matrix/list view correct

### ISSUE THREAD

**Issue by maggiedelano** [SkepticMystic/breadcrumbs#242]
Hi! I am having some issues with breadcrumbs. I have confirmed my YAML data is set up correctly and can see the correct relationships in the matrix/list view in the sidebar, but the correct trail view is not displaying. The errors started with "Cannot read property 'forEachEdge' of undefined" and then later all appear to be of the form "Cannot read property undefined of undefined" and related to `drawTail`. I'm attaching a full log for your reference. 

More details: on mac 11.6.1, obsidian v0.13.19. All the notes I have are using the `parent` or `BC-folder-note: child` settings in YAML. Things did work briefly but as I added additional notes it seems to be crashing and not working.

Let me know if additional information would be helpful, such as some example notes.

[obsidian.md-1641522166016.log](https://github.com/SkepticMystic/breadcrumbs/files/7825893/obsidian.md-1641522166016.log)

**Comment by maggiedelano** [comment]
I did a little bit more digging and I was able to narrow down the issue. The problem line in my vault was the following line in the YAML of a note (I changed up to parent):

`parent: [[00 - Home]]`

I know the suggested syntax would be `parent: ['00 - Home']`, so when I found it I knew something might be wrong. Here's what was surprising: the line `up: [[00 - Home]]` in YAML works just fine, so it's something about specifically using parent (or some non standard parameter). 

When a problem line like this is used, it crashes the trail view and the only way to get functionality back is to remove the line, totally uninstall the plugin, and then reinstall it. I haven't had any issues so long as I've followed the correct syntax so far, though. I think a solution would just be to handle this case to act the same as `up: [[00 - Home]]` or some other way for trail view to not crash entirely when there is an error.

**Comment by SkepticMystic** [comment]
Hey Maggie, thank you for the detailed bug report.
That is really strange. Although that is the recommended syntax, `parent: [[00 - Home]]` should still work. I'll try reproduce this to handle the error better

**Comment by SkepticMystic** [comment]
@maggiedelano I have been testing out this bug.. I can't seem to recreate the behaviour you experienced.
Both `up: [[Note]]` and `parent: [[Note]]` work just fine in yaml for me.
I'll leave this issue open in case more info comes up, but it's a difficult one

**Comment by maggiedelano** [comment]
Sounds good, thanks for looking into it!

**Comment by SkepticMystic** [comment]
@maggiedelano I've recently rewritten Breadcrumbs from scratch. See the link at the top of the README for more info.
If you decide to upgrade to the beta (using the BRAT plugin), this issue is likely resolved. Could you let me know if you do?

**Comment by maggiedelano** [comment]
Hi! I just updated and the wikilink syntax works now in YAML, you just have to put it in quotes (and the new docs reflect this). So I think this is resolved?

I did notice some other issues while testing out the BETA that I can create separate issues for.

**Comment by SkepticMystic** [comment]
Please do! Thank you
