### ISSUE TITLE
All Breadcrumbs views don't show on version >= 2.26.0

### ISSUE THREAD

**Issue by phillipjohnston** [SkepticMystic/breadcrumbs#249]
Hello,

I just updated the plugin this evening, and now I can no longer see the breadcrumbs panes in the sidebar, or the button on the ribbon bar to open the visual display. Disabling and re-enabling the plugin had no effect on this, and neither did uninstalling and reinstalling the plugin.

Do you have any tips on how I can figure out what's going on?

**Comment by phillipjohnston** [comment]
Ok - turning safe mode on, and then off again seemed to have resolved it. I have no theories as to why that is. OK to close this unless you think there's something worth investigating further.

**Comment by SkepticMystic** [comment]
That's very strange indeed. I'll leave the issue open in case someone else gets the same bug

**Comment by SkepticMystic** [comment]
It seems this issue has resolved itself. Please open a new one if this happens again on the latest versions
