### ISSUE TITLE
@ in file name breaks breadcrumbs

### ISSUE THREAD

**Issue by tami5** [SkepticMystic/breadcrumbs#25]
A file name starting with @ breaks links. resulting in the creation of new pages, rather than navigating to the page it self. 

for example:

```
---
parent: [[\@bookName2019]]
---
```

Creates a new page.

**Comment by SkepticMystic** [comment]
I think I'll just preprocess the text by removing any backslashes, that should work

**Comment by tami5** [comment]
Also, in that vein, it might be useful to be able to write the name of the file without brackets and it would recognized it as links. The only reason to keep using wikilinks in yaml that it would update when the filename changes, but I'm not sure that would work in yaml

**Comment by SkepticMystic** [comment]
So you could write: `parent:: Index, Upper` and it would be treated the same as `parent:: [[Index]], [[Upper]]`

**Comment by SkepticMystic** [comment]
Using this syntax would create ambiguity. Is `Index, Upper` referring to two notes: `Index` and `Upper`, or one note with a comma in it? `[[Index, upper]]`?
I think there are enough ways to write the syntax, and this change would be breaking.
