### ISSUE TITLE
[Bug] Alias not picking up inline dataview fields

### ISSUE THREAD

**Issue by SlRvb** [SkepticMystic/breadcrumbs#256]
Some of my notes that use inline fields `Title:: ` aren't being picked up by breadcrumbs even with the `Use yaml or inline fields for hierarchy data` toggled on. Only the yaml ones `Title: ` are being picked up properly.

**Inline not being picked up:**
![Obsidian_cZZT6KOTuo](https://user-images.githubusercontent.com/54087190/148719061-6a3e4b83-9c02-4d84-a776-b440d76fd023.png)

**Yaml being picked up:**
![J7ykPuBJlW](https://user-images.githubusercontent.com/54087190/148719167-1d63690d-6da0-433c-92c3-a422b87e44e3.png)

**Comment by SkepticMystic** [comment]
For when I fix this:
Instead of grabbing the TFile from `getFirstLinkPathDest`, get the `dataview.api.page` of the note name, instead. This has both metadata types on it.
Obvs check if DV is enabled before doing so, falling back to Obsidian metadataCache if so
