### ISSUE TITLE
FR: Allow codeblock `depth` to take a range of values

### ISSUE THREAD

**Issue by scriptor-dga** [SkepticMystic/breadcrumbs#257]
It would be nice if Breadcrumbs were able to output a list of descendants of the note in focus at the desired depth level. In the example below, the descendants of A at level 1 are [B1, B2, B3] and its descendants at level 2 are [C1, C2, C3, C4, C5, C6]. Each descendant would be transcluded (is this the right word? I mean that it should be a clickable link).
![image](https://user-images.githubusercontent.com/59956700/148719851-a7890d3f-81d9-4959-a306-ffd70092b4d0.png)

**Comment by SkepticMystic** [comment]
Have a look at the Codeblock section in the wiki, you should be able to do exactly what you're looking for :)

**Comment by scriptor-dga** [comment]
That's not quite what I'm looking for. With the codeblocks I can get a list of ALL the descendants of A, but I actually want to see **only** its grandchildren (C1...6), not all the nodes in between (B1...3).

**Comment by SkepticMystic** [comment]
Ahhhhh I see!
I will make it so that in the codeblock, you can write `depth: 2-4` to only shows notes at a depth between `2` and `4`, for example

**Comment by scriptor-dga** [comment]
Thank you! So to get the result I mentioned in my last post, I'd have to do `depth: 2-2`?

**Comment by SkepticMystic** [comment]
Exactly, yes. And you'd be able to use `2-` to set a lower bound with no upper bound

**Comment by scriptor-dga** [comment]
That would be perfect! Not to pressure you or anything but when are you planning on implementing this? 👀

**Comment by SkepticMystic** [comment]
@scriptor-dga should be working in the latest release 😋

**Comment by scriptor-dga** [comment]
OMG you're so fast! I'm gonna make you a donation as soon as I get my salary XD

But I think there's a bug!

When I do:

```
```breadcrumbs
type: tree
dir: down
depth: 1-1
``` 
it should give me the children of that note but it actually gives me its grandchildren (depth 2)

**Comment by SkepticMystic** [comment]
Haha glad to hear it's working!
Indeed, minimum is 0 - it's a programming thing 😋

**Comment by scriptor-dga** [comment]
I know, but maybe it'd be better to make it more user-friendly for the majority of the users, who are not programmers? 😜

**Comment by SkepticMystic** [comment]
I get you... maybe. It is in the wiki, and I feel like the top-level items don't really have any depth, you know? They're at the top, before you've "dug down" yet

**Comment by scriptor-dga** [comment]
I disagree 😅 There is a difference between, let's say, me and my father. We're not the same person, therefore the difference - or depth - between us can't be 0 but 1. I know it's in the wiki but personally, I'll have to put some thought into it every time I write a codeblock 🙃

**Comment by SkepticMystic** [comment]
That is a good point, indeed. Considering that the results don't include the current note, all of them have a depth of atleast one. 
Yeah, I guess I agree :yum:

**Comment by scriptor-dga** [comment]
So you will change it? 😲

**Comment by SkepticMystic** [comment]
Haha indeed, it makes more sense this way 😋 I'll ping you once I've changed it

**Comment by SkepticMystic** [comment]
The original FR is closed, so I'll make a new one for the `depth` change
