### ISSUE TITLE
field varients for relation types shouldn't be shown

### ISSUE THREAD

**Issue by tami5** [SkepticMystic/breadcrumbs#26]
In list and matrix view, it would be nice to not see the variants I have and instead see the type of the relationship e.g. `Parents`.

**Comment by SkepticMystic** [comment]
This could be a setting. I'll add it to the list

**Comment by tami5** [comment]
Thanks ❤️

**Comment by SkepticMystic** [comment]
Should be fixed in the new release 😄 let me know if it works for ya
