### ISSUE TITLE
Limit trail to only show certain fields: only up?!

### ISSUE THREAD

**Issue by scriptor-dga** [SkepticMystic/breadcrumbs#260]
Why does the option "Limit trail to only show certain fields" only have the option Up?
![image](https://user-images.githubusercontent.com/59956700/148758353-16397499-78ff-4aaf-8f31-6d6c70253c6e.png)

**Comment by SkepticMystic** [comment]
Because the trail view only shows you the `up` tree. So toggling a `next` field, for example, would have no effect on the result. Does that make sense?

**Comment by SkepticMystic** [comment]
If you add another `up` field, you'll see it get added there when you reload settings
