### ISSUE TITLE
FR: Sort "down" view alphabetically (like List view)

### ISSUE THREAD

**Issue by derekvan** [SkepticMystic/breadcrumbs#261]
Would love to see the "down" view sorted the same as the List/Matrix views. Thanks!

**Comment by SkepticMystic** [comment]
Hey @derekvan :)
Thanks for the FR! This problem is alot more complicated than a simple `results.sort()` call... I would need to store the results in a fundamentally different way. I will try implement it - maybe there is a solution I haven't considered - but it won't be soon

**Comment by smaroukis** [comment]
+1 so that the codeblocks down tree view matches the matrix/list view

**Comment by SkepticMystic** [comment]
Complete in V4 :) See here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
