### ISSUE TITLE
Span over Pre for the codeblock indent

### ISSUE THREAD

**Issue by SlRvb** [SkepticMystic/breadcrumbs#269]
Instead of using the `<pre>` html for the indent class, it might be better to use `<span>` with the same padding.

---
Obsidian uses `<pre>` to style outer edge of codeblocks which is why you've had to use `background: transparent` for your `<pre>` css and why it already had some padding added to it. 
![DPEjsaKhNJ](https://user-images.githubusercontent.com/54087190/149015512-6e1ae28f-c99b-4afe-9471-19bed3b7835c.png)

It'd be better to use `span` for other themes that style the `pre` in different ways resulting in some funky looking styling on the breadcrumbs codeblock display. For example the ITS Theme styles the pre and results in this:
![Obsidian_0CHnfAKiqy](https://user-images.githubusercontent.com/54087190/149015491-ce1c4053-883c-459a-b3d2-a7cc01198115.png)

**Comment by SkepticMystic** [comment]
This should be resolved in the rebuild, gonna close this out.
Please read here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
