### ISSUE TITLE
Duplicated links when a link is both implied and real

### ISSUE THREAD

**Issue by tami5** [SkepticMystic/breadcrumbs#27]
If a page has both implied and real relationship to a file, the link get repeated.

**Comment by SkepticMystic** [comment]
Good catch, I'll fix this

**Comment by SkepticMystic** [comment]
@tami5 Should be fixed in 0.5.4. My implementation is a little hacky though, so let me know if it works as expected :)

**Comment by tami5** [comment]
> @tami5 Should be fixed in 0.5.4. My implementation is a little hacky though, so let me know if it works as expected :)

Thanks a lot @SkepticMystic , I'll check it out letter this evening
