### ISSUE TITLE
Hierarchies not syncing across devices

### ISSUE THREAD

**Issue by kraigparkinson** [SkepticMystic/breadcrumbs#273]
EDIT: Sorry. Please ignore this. Had to not just restart but reopen my synced vaults on all devices. 🤦🏻‍♂️ 

I have sync and this plugin and dataview enabled on all of my devices. I created a hierarchy on my iPad Pro, however after a complete sync and restart of Obsidian across my iPhone and iPad Mini, the additional hierarchy that I've added on my iPad Pro is not being synced to the iPhone or iPad Mini.

**Comment by SkepticMystic** [comment]
Haha thanks for noting the fix :)
