### ISSUE TITLE
Bug: Option "Filter Implied siblings" doesn’t work.

### ISSUE THREAD

**Issue by Shuusei04** [SkepticMystic/breadcrumbs#275]
I use two different hierarchies and enable the option. 

"solution concepts ⬆️---topics---⬆️ game theory" and

"Roger B. Myerson - Game Theory - Analysis of Conflict  ⬆️---belongTo---⬆️ game theory ";

From the description of the option, they won't show up in each other's "implied sibling". However, they still show up  even if their parent type is different (topics vs. belongTo)

https://user-images.githubusercontent.com/52666628/149312715-597665ec-8d29-44eb-b9a0-c49c4eebec86.mp4

**Comment by SkepticMystic** [comment]
Yes, this feature doesn't work for now. A breaking change a while back made it more difficult to do this. I still intend to add it back though. Thanks for adding the issue :)

**Comment by SkepticMystic** [comment]
I'm gonna close this as complete (especially in v4), now that hierarchies and their implied relations are separate
