### ISSUE TITLE
FR: Inserting inline metadata where the text cursor is

### ISSUE THREAD

**Issue by crazymedguy** [SkepticMystic/breadcrumbs#276]
Sometimes during threading mode, I'll "leave" a note with the hotkey/command, but what happens is that the inline metadata gets inserted at the top of the file. I'm wondering if it's possible to insert the inline metadata wherever the text cursor is? For example, I like doing something like:

```
from:: [[page A]]

page B contents....

*text cursor here*to::[[page C]]
```

**Comment by SkepticMystic** [comment]
Hey @crazymedguy :)
I like this idea. I'm wondering though, when should it happen? I guess there can be a setting to say "Always place it under the cursor", or "Always put it at the top"?

**Comment by SkepticMystic** [comment]
@crazymedguy this is working in the latest release!
You need to enable the setting `Commands > Threading > Thread Under Cursor` for it to work
