### ISSUE TITLE
FR: Allow to exclude a note with `.` from the dendron hierarchy

### ISSUE THREAD

**Issue by Pyrodusk** [SkepticMystic/breadcrumbs#277]
I really enjoy the ability to use the Dendron Notes alternative hierarchy and I was wondering if it would be possible to add some kind of metadata (in YAML) to a note to exclude it forme the dendron hierarchy ? 
My use case is that some of my notes include `.` but simply because of the name they have (ex. `Hypothes.is` (the web annotator)) and not because of a structure I want to give them thus it would be best to be able to exclude them.

**Comment by SkepticMystic** [comment]
Hey @Pyrodusk! I think this is a great idea!
I'll make it so that adding `BC-ignore_dendron: true` to the frontmatter of a note ignores it froms dendrons

**Comment by Pyrodusk** [comment]
Sweet, thank you!

**Comment by SkepticMystic** [comment]
The release isn't available yet. Just gotta merge the PR first
