### ISSUE TITLE
Tree view disappeared

### ISSUE THREAD

**Issue by deehtodd** [SkepticMystic/breadcrumbs#278]
Same as discord posting: https://discord.com/channels/686053708261228577/929513881041248266/931257053748551780 with pictures. 

I think my "tree" view disappeared overnight.  Impossible I know, but can't seem to get it back.  It is selected in settings as shown below (1st pic). but doesn't appear on the sidebar menu as shown (2nd pic).
![image](https://user-images.githubusercontent.com/77208255/149413474-49618725-4278-4e6d-a179-86592fb08117.png)
![image](https://user-images.githubusercontent.com/77208255/149413511-4d61a620-7268-4564-b3be-58cc1a279092.png)

You mentioned --SkepticMystic — Today at 11:46 AM
I did change something there, so it's possible a bug was introduced. I'll check it out 🙂

**Comment by SkepticMystic** [comment]
@deehtodd wait, isn't this this tree view, though?
![image](https://user-images.githubusercontent.com/70717676/149621918-79752caa-c7f5-4818-8352-b391d3ac1c1d.png)

**Comment by deehtodd** [comment]
>  Not like it used to be at least.  This just shows the down (or up... etc) level one deep.  A tree view used to show your entire vault basically in outline form. This is not a high-priority item, but I use it a lot and would like to see it return, but I suspect many others do not use it as I do.

**Comment by SkepticMystic** [comment]
Hmm that's strange. It still shows the full tree as intended, for me

![image](https://user-images.githubusercontent.com/70717676/149649374-18f802b6-d3c9-47dd-94df-9cdd06f8aa3f.png)

Perhaps you need to change the direction from the dropdown? But the default should be `down` already... let me know if changing that helps, otherwise there's a bug here

**Comment by SkepticMystic** [comment]
@deehtodd do you still get this issue with the latest versions of BC and Obsidian?

**Comment by SkepticMystic** [comment]
Closed due to inactivity
