### ISSUE TITLE
Bug: Regex Note picking up more notes than it should

### ISSUE THREAD

**Issue by SlRvb** [SkepticMystic/breadcrumbs#279]
I'm trying to use regex note here to take me to the next note for files titled `SOAS-000 File Title`. But it seems to be picking up everything that vaguely matches.

So notes with `SOAS-000-00 File Title` also get picked up when they shouldn't. Also seems to apply the scenes and chapters to `Duplex` and some chapter to `Above` which they *definitely* shouldn't be applied to.

I've tried changing the field stuff to capital/lowercase and the regex: adding/removing a caret, using a regular space/`\s`; but it doesn't seem like any of those change enough to fix this issue.

---
My hierarchy is `Chapter, Duplex, Scene, Next, Previous`

```yaml
BC-regex-note: '/SOAS-\d{3}\s\w+/'
BC-regex-note-field: next
```
---
The left search is what it should bring up. Instead breadcrumbs is _also_ showing my scenes in its view:
![](https://cdn.discordapp.com/attachments/929513881041248266/931307534608904203/Obsidian_H0C582VbC0.png)

**Comment by SkepticMystic** [comment]
I've been trying to figure this one out, but have had no luck so far.
My tests show that:
- Breadcrumbs creates the regex correctly
- Javascript's regex engine correctly matches the file names you're checking for
![image](https://user-images.githubusercontent.com/70717676/150589701-275c0025-5a8e-43c8-bc00-cca4f9406935.png)

So I'm not currently sure...

**Comment by SlRvb** [comment]
Hmm, yeah I haven't seem to have had anymore issues with my testing. I'm not sure what happened 🙈 

Since it's working fine now, I think I'll close this issue. If it pops up again, I'll reopen it with more info on how it got messed up.
