### ISSUE TITLE
Feature Request: Imply siblings farther than one link away

### ISSUE THREAD

**Issue by mikkovedru** [SkepticMystic/breadcrumbs#280]
Let's say there are 3 notes: A, B, and C.

- A says that B is "same".
- B says that C is "same".

The implied connections created:
- From B to A.
- From C to B.

But there are no implied connections:
- A -> C
- C -> A

Is there a reason why they are missing? Is it a bug or some kind of philosophical/technical issue?

It would be nice to have those notes automatically connected with the settings option of turning it on or off. 

Might be a bit trickier with prev/next categories...

**Comment by SkepticMystic** [comment]
Hey @mikkovedru :)
This is covered in the more general discussion here #259.
I'm currently working on the features, in fact, so there should be a beta up relatively soon
