### ISSUE TITLE
Bug: Same title' notes in different folder share same relationship.

### ISSUE THREAD

**Issue by Shuusei04** [SkepticMystic/breadcrumbs#281]
My hierarchy is parent-sibling-child-next-prev.

I tried to create different books' chapters in a different folders and use breadcrumbs to specify their relationship. Then I found that the name "1. introduction" file shares the same relationship.

Here is file "1. introduction" in folder "book A" 

<img width="1920" alt="CleanShot 2022-01-17 at 21 15 31@2x" src="https://user-images.githubusercontent.com/52666628/149767923-54a989bf-e487-4098-ab3a-dd538f94b147.png">

Here is file "1. introduction"  in folder "book B"

<img width="960" alt="CleanShot 2022-01-17 at 21 16 33@2x" src="https://user-images.githubusercontent.com/52666628/149768053-18e6b923-3d33-43ad-a777-4f7e89ef9e6f.png">

**Comment by SkepticMystic** [comment]
Indeed, this issue is being tracked in #136. Thanks for noting it, but I'm gonna close this to keep it in one place
