### ISSUE TITLE
FR: Implied sibling relation of root notes in folder containing only Dendron-style hierarchy notes

### ISSUE THREAD

**Issue by andrey-jef** [SkepticMystic/breadcrumbs#282]
# Current situation:
I have a dedicated folder, which is located inside an Obsidian vault, containing only *markdown* files with Dendron hierarchical structure as follows
```
a.md
a.foo.md
a.bar.md
b.md
b.alpha.md
b.beta.md
```
Currently, `Breadcrumbs` plugin can recognize perfectly the hierarchy that `foo` and `bar` are siblings, under the parent node `a`. Similar behavior for `alpha` and `beta`, with their parent node `b`.

But `Breadcrumbs` cannot recognize the implied relation that `a` and `b` are siblings. 

## Expected behavior:
I want that `Breadcrumbs` recognize the implied relation that `a` and `b` are also siblings. And this implied relation should be only expected in a folder with Dendron-style *markdown* notes. 

## My thoughts
The requested behavior makes it easier to navigate in a Dendron-style hierarchical folder. At the moment, when I want to navigate from note `a` to note `b` on mobile, I need to use `Search` pane, or scrolling the `File explorer` pane, instead of simply swiping left and pick the notes from the `Breadcrumbs` navigation pane.

I understand that this request might affect the expected behavior of `Breadcrumbs` for other notes that don't follow the Dendron-style hierarchy. I voice my suggestion here to learn about its possibility to be implemented.

Thanks.

**Comment by SkepticMystic** [comment]
Hey @andrey-jef :) Thanks for the FR.
I think I get what you're saying. My concern is that the sibling relation you're looking for isn't necessarily always true.
What if `a` is a note about Maths, and `b` is a note about Fish. Just because they're root nodes doesn't imply that they're related in any way. You know what I mean?
There could certainly be some logic to decide when this is the case, but a simple solution is just to add the real sibling relation from one to the other `same:: [[a]]` or `same:: [[b]]`.

What are your thoughts?

**Comment by andrey-jef** [comment]
Hi @SkepticMystic 
Absolutely agree with you that `a` and `b` is not compulsory related. Just under the viewpoint of a hierarchical echelon in Dendron, `a` and `b` are in the same level, and they would be displayed as `siblings` or `same` in the Breadcrumbs `matrix view`

Further, this assumed behavior should be applied solely for a folder which has only Dendron-style notes. Because in Dendron, there is a `root` node, with filename `root.md`. `a` and `b` are implicitly considered as children of `root`
```
root.a
root.b
```
although, the note's filenames are only `a.md` and `b.md`

Imho, this FR is not for the benefit of Obsidian. Personally, I think this is for the advantage of Dendron users, who use Obsidian as their mobile companion app. Hence I hesitate so much before raising up the request. I'm not comfortable with my inner thoughts that I'm abusing the resource of an Obsidian developer for another community 😊

**Comment by SkepticMystic** [comment]
Thinking about this more, you could probably achieve this with Folder Notes.. Create a new note `/index.md`, and add the `BC-folder-note-field: same` field to the frontmatter. It shout mark all top-level notes as sibllings
