### ISSUE TITLE
Alignment issue when there are both real and implied relations under the same direction

### ISSUE THREAD

**Issue by onnyyonn** [SkepticMystic/breadcrumbs#285]
In the Matrix view, generally the direction (up, down etc.) is an h4 heading that is left aligned and real/implied is an h6 heading that is right aligned. But if there are both real and implied relations are under the same direction, the implied heading becomes left aligned.

The problem can be visualized in this screenshot, where the direction (h4) are green, real/implied headings (h6) are yellow and the links are blue.

![Screenshot_20220122_031243](https://user-images.githubusercontent.com/963267/150630839-1877a3de-d525-4b94-90e5-d7c312d117d1.png)

**Comment by SkepticMystic** [comment]
Hey onnyyonn :)
Thanks for the issue. I feel both the real and implied headings should always be right aligned
