### ISSUE TITLE
Feature Request: allow the autosuggestor to suggest user-filled breadcrumb types

### ISSUE THREAD

**Issue by brimwats** [SkepticMystic/breadcrumbs#286]
what I mean is to have it suggest the things filled out in settings. For example:

![image](https://user-images.githubusercontent.com/73113656/150691920-efb6f2de-c544-4995-b28c-415b6519d6be.png)

if I typed like BC-BT (or just BT) to have Breadcrumbs suggest "BT⤴️"

**Comment by SkepticMystic** [comment]
@brimwats this is available in the latest beta release :D
You'll need to install it manually from here: https://github.com/SkepticMystic/breadcrumbs/releases/tag/2.44.0

Go to Settings > Alternative Hierarchies > Enable Relation Suggestor. Weird place, I know. You can also change the trigger.
Let me know how it works for you :)
