### ISSUE TITLE
Threading Minor Bugs

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#288]
The settings for the Threading File Name should disallow illegal characters. took me a bit to figure out the problem 🙈 

<img width="1155" alt="Screenshot 2022-01-23 22 28 10" src="https://user-images.githubusercontent.com/73286100/150698691-8da2abad-1064-4612-80de-2af9b0599261.png">
<img width="1077" alt="Screenshot 2022-01-23 22 27 49" src="https://user-images.githubusercontent.com/73286100/150698692-426a7281-e338-4c99-be13-fc06d1767b1c.png">

---

After that, the dependency on metaedit for the threading feature is nowhere to be documented. :(

**Comment by SkepticMystic** [comment]
Just for reference
![image](https://user-images.githubusercontent.com/70717676/151491792-31b758c0-b535-47fb-a6d2-73eeb760cfe8.png)
