### ISSUE TITLE
[BUG]: Codeblock: `title: false` not accepted

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#289]
<img width="1089" alt="Screenshot 2022-01-24 20 45 51" src="https://user-images.githubusercontent.com/73286100/150853414-4384edd2-36f9-42da-8186-1d8dd9e23bff.png">

ლ(ಠ_ಠლ)╯ 

````
```breadcrumbs
type: tree
dir: down
title: false
```
````

**Comment by scriptor-dga** [comment]
the `it has to be false` is wrong, but it's true that if you leave the line out, the title will not show up.

**Comment by SkepticMystic** [comment]
I've got this working again in the latest release :D
