### ISSUE TITLE
Codeblock and Folder notes

### ISSUE THREAD

**Issue by MicheleDeZen** [SkepticMystic/breadcrumbs#291]
I am trying to setup a codeblok to show me all the notes under a folder note but i can't figure out what i am doind wrong.
The file structure is as follows :
- Folder
  - Main
  - Test1
  - Test2

inside of main i have 
`---
BC-folder-note: up
---`

I can see the relation in the matrix view 
![image](https://user-images.githubusercontent.com/66516225/151148184-10d87c07-e3e9-4741-aba9-2fa2cf58d527.png)

but if i try with the codeblock it doesn't work (at least as i am expecting) 
````breadcrumbs
type: tree
dir: down
````

**Comment by SkepticMystic** [comment]
Hey @MicheleDeZen :)
I think the issue is that you `BC-folder-note` field is pointing `up`, but you're asking the codeblock to show you notes in the `down` direction.
Either change the folder note field to `down`, or the codeblock `dir` to `up`

**Comment by MicheleDeZen** [comment]
oh ok i was thinking it backwards. thanks
