### ISSUE TITLE
[ENHANCEMENT] Removing second Scrollbar in Matrix mode

### ISSUE THREAD

**Issue by veradrawer** [SkepticMystic/breadcrumbs#292]
Hi @SkepticMystic

This is hacky as hell, but that second scrollbar was driving me mad.
I have this simple snippet to share. It works on both Minimal and Default.

```
[data-type="BC-matrix"] div.view-content{
	overflow: hidden !important;
}
```

Take care!

**Comment by SkepticMystic** [comment]
Hey :)
Second scrollbar? Can you share a screenshot of what you mean?

**Comment by veradrawer** [comment]
![imagen](https://user-images.githubusercontent.com/75331117/151562189-336a4532-61ce-477e-84b8-6858f346da0d.png)

Minimal Theme

![imagen](https://user-images.githubusercontent.com/75331117/151562278-1b2b5063-a5d4-4015-93db-55f775886df5.png)

Default Theme

The icons on top are creating some kind of overflow. You could group them, fix their positioning, set them to relative, adjust their z-index, and add some margin on top to the list-container... Or force the parent item not to have a sidebar, which fixes it.

Don't ask me, I don't fully understand what is going on.
By the way, I have some other CSS to streamline the Matrix's appearance a little .

```
.BC-Matrix div {
    border: none !important;
    text-align: left !important;
}
.BC-Matrix li{
	color: var(--text-accent);
	margin: 0.2em !important;
}
.BC-Matrix {
	font-variant-numeric: tabular-nums !important;
	line-height: 1.5 !important;
}
h4.BC-Matrix-header:first-letter {
    text-transform: capitalize;
}
.BC-Matrix-square li {
    list-style: disc;
}
[data-type="BC-matrix"] div.view-content{
	overflow: hidden !important;
}
.BC-Matrix-square:last-child{
	margin-bottom: 50% !important;
}
```

![imagen](https://user-images.githubusercontent.com/75331117/151562790-1832357b-ded4-4144-aec9-46be02ac0404.png)

![imagen](https://user-images.githubusercontent.com/75331117/151562831-75b870d1-e8b0-44bc-90b5-464627770a35.png)

**Comment by SkepticMystic** [comment]
Thanks for the suggestions :)
I've added some of these in the latest version, and added some of the other to the Wiki page on styling

**Comment by veradrawer** [comment]
Always glad to be of value!
