### ISSUE TITLE
It is not possible to make an alternative hierarchy from tags

### ISSUE THREAD

**Issue by BigbadHort** [SkepticMystic/breadcrumbs#293]
I'm watching a video where the author shows how to make an alternative hierarchy from tags (https://youtu.be/N4QmszBRu9I?t=757 )
I have a set of tags 
![image](https://user-images.githubusercontent.com/7830654/151301299-8bed46db-7dd8-415b-81db-961194850ac7.png)

I am adding the necessary construction to the yaml
![image](https://user-images.githubusercontent.com/7830654/151301473-627e49e3-4bd9-4a35-aa44-ceb6e3e9b1d8.png)

But the hierarchy is not being created....
![image](https://user-images.githubusercontent.com/7830654/151301344-a8b8340e-a083-481e-a03f-0d1f91bea2d2.png)
What is my jamb?

**Comment by SkepticMystic** [comment]
Hmmm everything looks right there...
Do you get any errors in the console?

**Comment by BigbadHort** [comment]
console for BC-folder-note: down
![image](https://user-images.githubusercontent.com/7830654/151670397-2e5e1708-9103-488c-b5d3-c82bff71b34c.png)

console for BC-tag-note: '#clip'
![image](https://user-images.githubusercontent.com/7830654/151670419-cf6f3ab3-7d03-497d-beef-be2f15c973a7.png)

**Comment by SkepticMystic** [comment]
@BigbadHort can you update to the latest version, then go to settings and turn Debug Mode onto the `INFO` level.
Then, Refresh Index, and go to this section of the debug logs in the console:

![image](https://user-images.githubusercontent.com/70717676/152634619-75b1aad9-b2f9-47c2-9a4d-04039be19013.png)


`tag` should be `#clip` in this example, and 
`targets` should be all the notes with that tag.

If `targets` is empty, please can you send an example of a note with the `#clip` tag in it

**Comment by SkepticMystic** [comment]
Closed due to inactivity
