### ISSUE TITLE
Bug: Relationship suggestor adds or removes wrong characters

### ISSUE THREAD

**Issue by HEmile** [SkepticMystic/breadcrumbs#295]
I suppose it removes the space in the second try because it wants to remove the default \. But using the string "- \" as the trigger gives the same result.
https://user-images.githubusercontent.com/1289165/151521914-f07e445a-138a-4713-811c-d3bcc972e081.mov

Also for Juggl links, I would prefer not to have the : appended :) This is not a huge issue though, I get that it's a niche use case.

**Comment by SkepticMystic** [comment]
May be resolved when I re-implement this in V4 (#472)

**Comment by SkepticMystic** [comment]
I believe this is fixed now (in V4 beta). The suggestor's `onTrigger` method is much simpler now. It looks for the prefix at the start of a line, and reliably removes the correct characters on selection
