### ISSUE TITLE
Dendron note parents are not displayed in trail/grid view or in graph view

### ISSUE THREAD

**Issue by Kamholtz** [SkepticMystic/breadcrumbs#296]
Apologies if this is due to misconfiguration. I am brand new to obsidian! 

## Observation

"This note has no real implied parents" is displayed in the trail view for a note that has a Dendron style parent. It is evident that the parent exists when the matrix view is inspected:

![image](https://user-images.githubusercontent.com/13547250/151538847-4e3bc9b3-eb8b-4cc4-801a-de9e94d4d5d6.png)

![image](https://user-images.githubusercontent.com/13547250/151538830-39019b88-b2f3-43a6-b673-29896fb17459.png)

The dendron hierarchy also does not appear in graph view:

![image](https://user-images.githubusercontent.com/13547250/151540077-28420488-ee56-4fb4-9b40-ed9173cc3e20.png)

## Expectation

The trail view should show the parents/up hierarchy which are already displayed in the matrix view. The graph view should show both parents and children.

## Vault files

![image](https://user-images.githubusercontent.com/13547250/151538533-2bace24e-07e9-428e-8d6a-574ea44bb5e3.png)

## Config

All defaults + `Alternative Hierarchies -> Dendron Notes -> Add Dendron notes to graph` is enabled. As per the defaults a standard hierarchy is configured "(up) (same) (down) (next) (prev)"

![image](https://user-images.githubusercontent.com/13547250/151538865-793a69f3-452c-41d2-ac34-970765e5d960.png)

## Update (29/01/2022)

I have found that ticking `up` in `Limit Trail View to only show certain fields` (as shown below) makes the the trail show a note's parent. This was previously off by default in my newly created vault. Graph view still does not represent the dendron hierarchies however.

![image](https://user-images.githubusercontent.com/13547250/151635613-07c073b4-8efe-4a2c-bdd6-55b267ff167a.png)

However I would have expected that if I didn't have it limited to any fields that it would show ALL parent notes by default. i.e. set as this:

![image](https://user-images.githubusercontent.com/13547250/151635740-b6a12596-df22-4cc7-bdc5-322e4d709d50.png)

From the settings in https://github.com/SkepticMystic/breadcrumbs/wiki/Settings it would appear that the intended behaviour is all `up` fields should be shown by default. Not sure whether that means all fields should have been ticked by default or if having none ticked implies there is no limiting enabled, but I do think showing all parents by default would be most intuitive.

> Limit Trail to only show certain parents
> From a list of your different up fields, choose which should be shown in the trail view. All are shown by default.

**Comment by SkepticMystic** [comment]
Hey @Kamholtz :)

I see that the changes made in your edit resolved the issue.
So that settings works as "If a field is ticked, show it in the trail. If not, don't show it".
All of the fields _should_ be ticked by default, therefore showing all fields by default - as the wiki says.
But given that the `up` field was not ticked, and you didn't untick it, then there must be a bug there

**Comment by SkepticMystic** [comment]
There is definitely a bug here, thanks!
I've added a fix which I believe should resolve it. But it doesn't work retroactively. So if the checkboxes were already unticked, it won't go and tick them for you. It will, however, tick _new_ fields

**Comment by SkepticMystic** [comment]
@andrey-jef @Kamholtz alright, 2.45.0 is out, this issue should be resolved. Be sure to tick all the appropriate checkboxes first (you'll only need to do this once)

**Comment by Kamholtz** [comment]
Thank you for such a fast fix!

**Comment by Kamholtz** [comment]
Just a side note, would you expect Dendron hierarchies to be reflected in the graph view as well? I don't seem to see this happening even with the `Limit Trail View to only show certain fields` setting applied.

**Comment by SkepticMystic** [comment]
@Kamholtz Breadcrumbs' Dendron features don't add "real" links to Obsidian. So they definitely won't show up in the Graph View, no

**Comment by Kamholtz** [comment]
Do you think adding real links from Dendron hierarchies would be within the scope of your plugin? I am happy to write up a feature request if so even if it's not a priority.

**Comment by SkepticMystic** [comment]
Have a look at this FR on the Obsidian API repo, we added it for this reason :)
https://github.com/obsidianmd/obsidian-api/issues/33

**Comment by andrey-jef** [comment]
> Have a look at this FR on the Obsidian API repo, we added it for this reason :)
> 
> https://github.com/obsidianmd/obsidian-api/issues/33

Thanks for pointing to the obsidian FR. The explanation in details of nothingislost is great. TIL that obsidian also uses database called indexedb 🤓

**Comment by SkepticMystic** [comment]
I'm gonna close this out, as the original bug seems to be fixed
