### ISSUE TITLE
FR: Support dendron hierarchy stubs

### ISSUE THREAD

**Issue by Kamholtz** [SkepticMystic/breadcrumbs#297]
In Dendron there is the concept of a stub (https://wiki.dendron.so/notes/c6fd6bc4-7f75-4cbb-8f34-f7b99bfe2d50/#stubs). A stub is a note that is referenced in a hierarchy, but does not actually exist yet. It appears as a parent when viewing its descendants. 

## Example

Notes in vault:
- `note1`
- `note1.note2.note3`  
- `note1.note2.note4`  

In this vault, `note2` is a stub. It does not exist yet, but it is referenced in the hierarchy of `note1.note2.note3`. When `note1.note2.note3` is opened, `note1.note2` should appear as a parent, and upon selecting `note1.note2` it should be created (in the same way that following a link to a note that is not yet created will automatically create it).

## Purpose

By not supporting stubs, it becomes difficult to ascend the hiearchy when you are at `note1.note2.note3` because its parent `note1.note2` does not appear in breadcrumbs. It also cannot be inferred that `note1.note2.note3` and `note1.note2.note4` are siblings.

It therefore becomes necessary to remember to create `note1.note2` for easy traversal of the graph. This is a point of friction and error prone as the hierarchy grows.

Without stubs, existing dendron vaults will not be traversable using breadcrumbs without first creating all of the stubs. 

## Use case

Suppose I want to create a todo list  for my projects in my brand new vault with Dendron hierarchies. It is grouped by project, then tasks, then parts. I want to jump straight in and write two notes for `part1` and `part2` of `task1` in `project1`

- `todo.project1.task1.part1`
- `todo.project1.task1.part2`

In order to get breadcrumbs to recognise these two notes as siblings, I must create the entire hierarchy first by making each note in the graph. This is particularly tedious on mobile.

- `todo`
- `todo.project1`
- `todo.project1.task1`
- `todo.project1.task1.part1`
- `todo.project1.task1.part2`

By recognising stubs, I can start at the lowest point of the tree by writing `part1` and `part2` and navigate up the tree via breadcrumbs (which will automatically create the notes) to fill out the details of `taska` and `projecta` at a later time.

**Comment by SkepticMystic** [comment]
Thank you for the detailed FR @Kamholtz, always appreciated :)
I can definitely add support for this! I don't really use Dendron notes myself, but I thought stubs were already possible. I don't think it should be too hard to implement

**Comment by Kamholtz** [comment]
Myself (and likely many other Dendron users) eagerly await this! Thank you!

**Comment by SkepticMystic** [comment]
Can you give it a try on 2.46.0 and let me know if it works :)

**Comment by Kamholtz** [comment]
I can confirm that this is working extremely well on my Dendron vault. I think you just made this a very viable option for creating/exploring Dendron notes on mobile devices. Thank you so much for the speedy work!

**Comment by prashanth-lavinna** [comment]
@Kamholtz Hello Carl. I loved Obsidian but I miss Dendron hierarchies so bad. I'm trying to use same vault for Obsidian and Dendron to overcome this. Would you elaborate on how you are using them together?
