### ISSUE TITLE
Expose Implied/Derived Relationships to Dataview

### ISSUE THREAD

**Issue by ethanresnick** [SkepticMystic/breadcrumbs#298]
I'd like to be able to query my hierarchies from dataview, as this seems like it would enable a lot of powerful and maybe-semi-common cases. However, it's currently only possible to query the relationships that are manually specified in each note, as that's all dataview can see.

To give one example, in programming terms, of how this could be useful: 

- Suppose I have a bunch of people in my network, each represented as an Obsidian note. 
- Each person has skills, which are expressed as frontmatter links. So, e.g., one person might have frontmatter like: `skills: "[[Python]]", "[[Computer Vision]]"`. 
- The linked skill notes are all arranged in a hierarchy, managed by breadcrumbs. So, I might have `AI -> NLP -> Speech Recognition` as well as `AI -> Computer Vision`.

Now, suppose I'm arranging an AI confab with friends. What I'd like to do is be able to generate a dataview table that shows all people with "AI" as one of their skills — even if the note for the person only mentions some child skill in the `skills` frontmatter.

It seems to me like this should be possible, because dataview exposes an API which other plugins can use, and it looks like this API exposes access to the dataview index, with methods that would allow breadcrumbs to detect changes to the index and update it. (Or maybe breadcrumbs would want to patch the metadata cache; I So my hope would be that the breadcrumbs plugin could add some simple fields to this index. The simplest starting point would just be to reflect the implied relationships in dataview. I.e., if Note A has `parent: "[[B]]"`, but Note B doesn't have an explicit `child: "[[A]]"`, then Note B should nevertheless a `child` field exposed to dataview that includes a link to A.''

To support my hypothetical of finding all the people with an AI-related skill, I think a collection of all of a note's derived ancestors/descendents would have to be exposed to dataview (not just the implied immediate parents/children), unless I can do some sort of recursive traversal (which is probably possible in dataviewjs).

**Comment by ethanresnick** [comment]
Note: I was able to accomplish this by reading `app.plugins.getPlugin("breadcrumbs").closedG` from inside my dataviewjs block and then working with the graphology api directly, but I have to assume that the graphology API is not meant to be part of breadcrumbs' public interface.

**Comment by SkepticMystic** [comment]
I have added a [Breadcrumbs API](https://skepticmystic.github.io/breadcrumbs/modules.html) which can achieve what you're looking for using a DataviewJS codeblock!

**Comment by ethanresnick** [comment]
Thanks!
