### ISSUE TITLE
Typo: In the description of "Relationships"  

### ISSUE THREAD

**Issue by I-Pch** [SkepticMystic/breadcrumbs#299]
Hi there 😊 !

Nothing absolutely urgent here 😁, but I just thought I'd mention that there's a very small typo in the introduction/description of the `Relationships` section 😊 : `relaiton` should be `relation` 😇 
(A `m` might also be missing in the rest of the sentence : "[...] so you can style the`m` differently")  

<img width="930" alt="Typo   Relationships   Relaiton" src="https://user-images.githubusercontent.com/77828085/151696402-7d5ccd33-b113-4a5d-9985-59373064c886.png">

I'm not sure if creating an issue for such a small and trivial thing is useful or not (It feels a bit like an overkill as I could have just said it on Discord 😊 )

Sorry in advance if I shouldn't have (and you would have preferred a simple message on Discord 😇 )

**Comment by SkepticMystic** [comment]
Thank you for noting this :)
The repo is a perfectly fine place to post this sort of stuff!
