### ISSUE TITLE
Feature Request: Support Indexing 

### ISSUE THREAD

**Issue by brimwats** [SkepticMystic/breadcrumbs#3]
As per #2 — it would be nice if breadcrumbs could support the bulding of an index somewhere.

An index might also generate fields for SN (scope notes) DF (definitions) and pages for OT/PT (parent terms, tops of hierarchies)

**Comment by SkepticMystic** [comment]
This links to the idea @weeyizhi had to "auto-generate" child and sibling fields based on their parents. I'll work on this after the refactoring mentioned in #1

**Comment by SkepticMystic** [comment]
Can you please elaborate more on what you mean here, Bri. I don't think I understand what the index would be or do.

**Comment by brimwats** [comment]
Everytime the graph detects a new parent term it writes it to a file. A concanetned list of PTs. It would be cool if it could autogenerate a list but idk how hard that is. i.e.

PT Arthitecture
    NT American Architecture
        NT American Log Cabins
    NT (etc)
        NT (etc)

**Comment by SkepticMystic** [comment]
Interesting... So to have the entire hierarchy structure written to a single file? 
The first thing that comes to mind is dealing with items the link up to multiple other parents, for example. But the common child could just be repeated in both places

**Comment by ashishbhateja** [comment]
It will be good to have an option for the hierarchy appended to the note. That way the links appear together with the text.

**Comment by SkepticMystic** [comment]
Thanks for the feedback @ashishbhateja.
I'm curious about how I should implement this. Currently there are two options:
1. Make one, giant index of the entire vault
2. Make an index for each page. Are you speaking about this option?

For 2., say the matrix view looked like this for the note `Goals`:

![image](https://user-images.githubusercontent.com/70717676/123596127-09b75780-d7f2-11eb-9bf1-0fa3d7d3f77c.png)

What would the appended index look like? Something like:

`parent`: [[Index]]
`Sibling`: [[Tasks]]
`Sibling`: [[Resources]]
`Sibling`: [[Projects]]
`Sibling`: [[Areas of Responsibilities]]
`Child`: [[Goals Inbox]]
`Child`: [[Closed Goals]]
`Child`: [[Archived Goals]]

@brimwats also curious to hear what you think of the second option. What other formats would be useful?

**Comment by ashishbhateja** [comment]
This is how Roam Research implements:
<img width="405" alt="Screen Shot 2021-06-28 at 4 22 09 PM" src="https://user-images.githubusercontent.com/69289857/123604361-5a987180-d82d-11eb-8671-6ebc3b354cac.png">

**Comment by SkepticMystic** [comment]
This problem is deceptively non-trivial, but I'm working on it

**Comment by SkepticMystic** [comment]
@brimwats @ashishbhateja I think I've got this working... Will you try out 0.9.15 and let me know if it works for you.
Currently, it will copy the index to your clipboard

**Comment by brimwats** [comment]
@SkepticMystic this works great on a page where all the NTs and BTs (etc) point to. Is there any way to do it for the entire vault?

**Comment by SkepticMystic** [comment]
I'm gonna close this issue out as more recent discuss is happening in #67
