### ISSUE TITLE
Make next and prev work like same

### ISSUE THREAD

**Issue by scriptor-dga** [SkepticMystic/breadcrumbs#300]
`Next` and `prev` should work like `same`.
If I have a note `Maths Course` -up> `Maths 101` -prev>` Maths 102`-prev>`Maths 103` etc. and I open `Maths 101`, I'd like to see not only its next `Maths 102`, but also its implied sibling `Maths 103`

**Comment by ooker777** [comment]
shouldn't it be Maths 101 -next> Maths 102-next>Maths 103? And Maths Course -up> Maths 101 is not relevant here

**Comment by SkepticMystic** [comment]
Closing as a sub-duplicate of #259. Will refer to this when working on that issue. Thanks.
