### ISSUE TITLE
Date note mistakes non-daily note for daily note even after renaming

### ISSUE THREAD

**Issue by scriptor-dga** [SkepticMystic/breadcrumbs#302]
How to repro:

- Turn on option `Add date notes to graph`
- Create a note titled `Bla bla bla 2022-02-01`
- Date note feature mistakes the note for a daily note and links it accordingly.
- Rename the note as `Bla bla bla`
- Refresh the index
- The `next` and `prev` date breadcrumbs are still there, and since they're not written in the file, there's no way to remove them.

**Comment by SkepticMystic** [comment]
Should be fixed in the latest release!

**Comment by SkepticMystic** [comment]
@scriptor-dga can you confirm if this still happens?

**Comment by SkepticMystic** [comment]
Gonna close this as complete in v4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
