### ISSUE TITLE
Feature Request: Add a yaml-key `BC-ignore` to completely ignore a note from picked up by Breadcrumbs

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#306]
[Context](https://discord.com/channels/686053708261228577/929513881041248266/938459409590419526)

**Comment by SkepticMystic** [comment]
@chrisgrieser I've added in `BC-ignore` as a field.
It currently works for _most_ alternative hierarchies (not for Link Notes, for example). Give it a try and let me know if it covers your use case

**Comment by chrisgrieser** [comment]
tbh, I don't remember the original use case for it anymore, so I cannot tell whether it would cover my use case 😂 🙈 (so I am closing this)

But I guess it's still useful to many others, e.g. https://github.com/SkepticMystic/breadcrumbs/issues/207
