### ISSUE TITLE
remember list/matrix view

### ISSUE THREAD

**Issue by weeyizhi** [SkepticMystic/breadcrumbs#31]
Plugin version: 0.4.12

If I use list view, every time I restart Obsidian, it resets back to matrix view. It would be great if the state of list/matrix view could be saved in the workspace.

Thanks a lot! This plugin has become one of my favorites :)

**Comment by SkepticMystic** [comment]
Haha this also started annoying me! So I added a setting: Default View Type (Or something). You can set what the view defaults to on load :)
