### ISSUE TITLE
[Feature Request] Depth Selector for trail or grid views

### ISSUE THREAD

**Issue by dummifiedme** [SkepticMystic/breadcrumbs#312]
An option to limit the trail to a certain number of crumbs, as discussed here:
https://discord.com/channels/686053708261228577/929513881041248266/938324102450675732

**Comment by Pummelfisch** [comment]
It seems to be implemented by now in some way. But currently we can't set a fixed number for the notes thats saved. We can just hide some as soon as we open the a note. I think it would be more helpful and clean if we could set a fixed number or a fixed note to which the breadcrumbs are trailed. Currently I often find myself to open a note and then click a few times at the minus at the top to bring down the trail.

**Comment by SkepticMystic** [comment]
Gonna close this as the original request is implemented.
However, @Pummelfisch please do open a new FR to save depth per-note, if you're still interested.
