### ISSUE TITLE
Sometimes there is no button on the left to open modal 

### ISSUE THREAD

**Issue by ooker777** [SkepticMystic/breadcrumbs#317]
But if I restart Obsidian it seems to solve the problem
![](https://i.imgur.com/aHqLtAF.png)

**Comment by SkepticMystic** [comment]
Do you get any console errors when this happens?

**Comment by ooker777** [comment]
I'll report to you when this happens again

**Comment by SkepticMystic** [comment]
@ooker777 any update on this?

**Comment by ooker777** [comment]
well I haven't use this feature lately. In fact I'm still unsure how this is helpful to me. I remember you said somewhere that it isn't much full-fledged either

**Comment by SkepticMystic** [comment]
Closed as inactive
