### ISSUE TITLE
A "Create new X from the current note" should make the new X in the folder, especially with BT-Folder-Note

### ISSUE THREAD

**Issue by brimwats** [SkepticMystic/breadcrumbs#319]
Just trying out this feature and realizing that the new notes aren't made in the same folder as the generating note, but thinking that it should!

**Comment by brimwats** [comment]
Another thought—can/should there be a way to invoke a template for the newly-created note?

**Comment by SkepticMystic** [comment]
Hey Bri!
I think it uses your Obsidian settings to determine where the new note goes. Is there a conflict there?

And yes, you can choose a template! Checkout the settings for the command under Settings > Commands > Threading

**Comment by brimwats** [comment]
> think it uses your Obsidian settings to determine where the new note goes. Is there a conflict there?

it does! that's what I mean, I was thit it should override the default if one is creating it from a note with BC-Folder-Down (etc)

> And yes, you can choose a template! Checkout the settings for the command under Settings > Commands > Threading

ah amazing! don't know how I missed that! thanks

**Comment by SkepticMystic** [comment]
Completed in the latest V4 release
