### ISSUE TITLE
[FR] Add options to disable trail of notes for specific pages

### ISSUE THREAD

**Issue by bobwng** [SkepticMystic/breadcrumbs#321]
Sometimes we dont' want to show trail of note:

 - Hide the trail note by default if there is no parent:
   - Suggest to add a plugin-settings:  Hide trail note if no parent.
 - If we just don't want to show the trail note on some special scenarios:
   - Suggest to add a key into metadata like "breadcrumbs-trail-note: false" to disable trail of note for current page

Please be noticed that this is different to #306, they are just want to hide trail of note, rather than exclude the pages from breadcrumbs index completly.

**Comment by SkepticMystic** [comment]
Hey @bobwng!
If think both of these can be done already:
1. To hide the trail if no parents exist, change the `No path found message` to be blank
![image](https://user-images.githubusercontent.com/70717676/152634009-0286cbe5-e9cd-4406-8442-fcd5d8e36cff.png)

2. To hide the trail on specifc notes, use `BC-hide-trail: true`

**Comment by bobwng** [comment]
Got it, thank you!

I like the plugin very much, thanks again~!
