### ISSUE TITLE
hierarchy notes should support next prev field

### ISSUE THREAD

**Issue by HananoshikaYomaru** [SkepticMystic/breadcrumbs#327]
# thanks 🔥

Thanks for the continuous improvement of the plugin. I honestly think this is one of the greatest plugin in the community. 

# request 

As title. The current hierarchy note only support up same down relation. The following should be supported such that people can stick to this hierarchy option.

```
- [[1]]
  - [[1.1]]
    - next [[1.2]]
    - [[1.1.1]]
    - [[1.1.2]]
    - [[1.1.3]]
  - [[1.2]]
```

`[[1.2]]` appear two times in the hierarchy. One is for `down` relation of `[[1]]`, one is for `next` relation of `[[1.1]]`. 

I hope this make sense.❤️

**Comment by SkepticMystic** [comment]
This is a reasonable FR, I'll see if I can make it happen!

**Comment by SkepticMystic** [comment]
@HananoshikaYomaru I've added support for this in the latest update (hasn't been released yet as of writing this). Please let me know if it works for you

**Comment by Cammagno** [comment]
now that there is a way to specify a (different) prev-next order in hierarchy notes, 
what about setting it to consider by default that the following item in a list (at the same level) is next to the previous one?

e.g.:
- [[1]]
  - [[1.1]]
    - [[1.1.1]]
    - [[1.1.2]]
    - [[1.1.3]]
  - [[1.2]]
  
  1.2 is next of 1.1
  1.1.3 is next of 1.1.2 which is next of 1.1.1

**Comment by adzcai** [comment]
I'd also like this feature! I believe it was also requested in #392

**Comment by jiajiala** [comment]
`- [[xx]]
  - [[dd]]
    - [[dd~]]
    - [[dd~x]]
  - [[oo]]`

Structures like this should be recognizable by nature
oo   is next of  dd

**Comment by SkepticMystic** [comment]
The original FR is implemented as requested. You can override the default field using `- <field> [[note]]`.
I'm working on the related issue, and will track progress there.

Thank you to @adzcai for your PR. Unfortunately the timing didn't work with my rewrite to v4, but I appreciate your effort nonetheless!
