### ISSUE TITLE
expose breadcrumbs API 

### ISSUE THREAD

**Issue by HananoshikaYomaru** [SkepticMystic/breadcrumbs#329]
**Is your feature request related to a problem? Please describe.**

Breadcrumbs is possibly the ultimate tool to note structuring tool in obsidian. Its core is the user defined hierarchies of different hierarchy method. It could expose its API such that other plugins can build on top on breadcrumbs. 

**Describe the solution you'd like**

A typed API can be exposed like Dataview does. This will be a big thing for the obsidian community because the API will super charge Obsidian to be well-organized vault.

https://blacksmithgu.github.io/obsidian-dataview/plugin/develop-against-dataview/

More on rationale: https://github.com/SkepticMystic/breadcrumbs/discussions/335#discussion-3860274

**Comment by SkepticMystic** [comment]
It now does :D
https://skepticmystic.github.io/breadcrumbs/index.html

**Comment by SkepticMystic** [comment]
Gonna close this out. Please add any issues/FRs for additional APi related stuff :)
