### ISSUE TITLE
Duplication of ties in matrix/list view

### ISSUE THREAD

**Issue by stefanopagliari** [SkepticMystic/breadcrumbs#33]
If Note A lists Note B as "child" and  Note B lists Note A as "parent", the lists/matrix view will show this relationship twice. Something like:
- Parent
  - A
  - A
- Child
  - B
  - B

Would it be possible to show only unique values? Something like this:
- Parent
  - A
- Child
  - B

Thank you

**Comment by SkepticMystic** [comment]
Hey Stefano. Does it still do this? I implimented a fix in a recent release. Which version are you on?

**Comment by SkepticMystic** [comment]
@stefanopagliari please let me know if this still occurs on the latest release. You will need to manually reinstall the latest one
