### ISSUE TITLE
Bug: adjust hierarchy notes show nothing 

### ISSUE THREAD

**Issue by HananoshikaYomaru** [SkepticMystic/breadcrumbs#330]
I try out the `adjust hierarchy note` feature but it shows nothing. 

I have no idea what the problem is. The index refresh without any problem. Should be some problem in the code.

https://user-images.githubusercontent.com/43137033/152745194-4d15bb90-8715-4231-8392-d4a7597c7a53.mp4

Version: 2.52.0

**Comment by HananoshikaYomaru** [comment]
![CleanShot 2022-02-07 at 17 03 29](https://user-images.githubusercontent.com/43137033/152757352-ce458479-8a1a-44a6-8346-ada034f8f69c.png)

in `HierNoteModal.ts`, when user put a folder in the hierarchy note setting, the length should not be 1, instead it should search the folder.

**Comment by HananoshikaYomaru** [comment]
# fix above bug

# another problem 

<img width="1164" alt="CleanShot 2022-02-07 at 17 42 59@2x" src="https://user-images.githubusercontent.com/43137033/152763589-c8d638f2-f93d-4e1d-b84c-f43f5e7ed144.png">

the ModifyHNItemComp is empty because the `onOpen` function of `ModifyHierItemModal` did not mount the UI component!!

![CleanShot 2022-02-07 at 17 42 08](https://user-images.githubusercontent.com/43137033/152763483-110ca5ed-d5f3-4e52-990d-cabc5c8be328.png)

**Comment by HananoshikaYomaru** [comment]
```ts 
export let modal: ModifyHierItemModal;
  export let settings: BCSettings;
  export let hnItem: HNItem;
  export let file: TFile;
  export let rel: "up" | "same" | "down";

  interface HNItem {
    depth: number;
    line: string;
    lineNo: number;
  }
  let inputEl: HTMLInputElement;

  let newItem = file.name.replace(".md" , ""); // this line added 

  const buildNewItem = (
    newItem: string,
    depth = hnItem.depth,
    preview = false
  ) =>
    `${" ".repeat(Math.round(depth / (preview ? 2 : 1)))}- ${
      preview ? newItem || "<Empty>" : makeWiki(newItem)
    }`;
```

default value of quick add HN should be file name.

**Comment by HananoshikaYomaru** [comment]
in `HierarchyNoteManipulator.ts` this make more sense becasue the purpose of `adjust hierarchy` is to adjust the hierarchy note without going to the hierarchy note. Therefore the most common key (`click` and `enter`) should be map to command `Add child` instead of enter the note. 

only `shift + enter` can enter the note.

```ts 

 onChooseItem(item: HNItem, evt: MouseEvent | KeyboardEvent): void {
    if (evt instanceof KeyboardEvent && evt.key === "Delete") {
      this.deleteItem(item);
    }else if (evt instanceof KeyboardEvent && evt.key == "Enter" && evt.shiftKey ){
      const view = this.app.workspace.getActiveViewOfType(MarkdownView);
      const { editor } = view ?? {};
      if (!editor) return;
      //@ts-ignore
      view.leaf.openFile(this.file, { active: true, mode: "source" });
      editor.setCursor({ line: item.lineNo, ch: item.depth + 2 });
    } else if (evt instanceof KeyboardEvent  || evt instanceof MouseEvent) {
      let  rel : "up" | "down" | "same" ;
      if (evt instanceof MouseEvent && evt.type == "click") { 
        rel = "down"
      }
      if ( evt instanceof KeyboardEvent ) { 
        if ( evt.key === "Enter") rel = "down"
      }
      if ( evt instanceof KeyboardEvent && evt.shiftKey )   { 
        if (evt.key === "ArrowUp") rel = "up" 
        if ( evt.key === "ArrowDown" ) rel = "down" 
        if (evt.key === "ArrowRight") rel = "same" 
      }

      new ModifyHierItemModal(
        this.app,
        this.plugin,
        item,
        this.file,
        rel
      ).open();
      this.close();
    } 
  }
```

**Comment by HananoshikaYomaru** [comment]
also using if clause is clearer than `? :` operation.

**Comment by SkepticMystic** [comment]
This will be resolved by your PR :)
