### ISSUE TITLE
Shift Breadcrumbs downwards

### ISSUE THREAD

**Issue by Pummelfisch** [SkepticMystic/breadcrumbs#331]
Hi just recently discovered this plugin and i love it.

I was wondering if it would be possible to shift the breadcrumbs downwards on some pages. For example with a css-class. I am using the banners-plugin and that one overlaps with the breadcrumbs.

Sadly i dont know anything about css, so i have no idea how to achieve this myself.

**Comment by HananoshikaYomaru** [comment]
```scss
// Main banner wrapper
.obsidian-banner-wrapper {
  margin-top: var(--banner-height);

  > .obsidian-banner {
    position: absolute; // this could be the issue
    top: 0;
    left: 0;
    right: 0;
    height: var(--banner-height);
    width: 100%;
    overflow: hidden;

    &.gradient:not(.error) {
      mask-image: linear-gradient(to bottom, black 50%, transparent);
      -webkit-mask-image: linear-gradient(to bottom, black 50%, transparent);
```

The problem is that obsidian banner use absolute position. Absolute position will find the closest relative parent and do the positioning. Therefore this is a not a problem of BC but rather a problem for banner. But as the problem is with CSS, it should be able to fix with only CSS. However, It think instead of modifying BC, banner should be the modified.

**Comment by Pummelfisch** [comment]
Okay so if i understood you correctly the banner will always be put straight on top of the page. I will make an issue there aswell and ask if there is someone who can help me.
However my problem was more that i wanted to move the BC downwards after the banner. So the banner can stay on top of everything then the BC and after that the content of the page. Or is that also dependent on the banner?

**Comment by HananoshikaYomaru** [comment]
I think you can provide a screen shot for developer to better understand the situation.

**Comment by SkepticMystic** [comment]
Please try v4, the html structure is quite different. See here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
I think this should be considered solvable with CSS (if v4 doesn't already solve it). So please give that a try first. If it's impossible, you can reopen this issue
