### ISSUE TITLE
breadcrumbs dataview note should support dataviewjs 

### ISSUE THREAD

**Issue by HananoshikaYomaru** [SkepticMystic/breadcrumbs#333]
dataviewjs can do advanced manipulation. If dataview query is supported, dvjs should be supported as well.

**Comment by SkepticMystic** [comment]
I don't think there is a simple way to do this...
The Dataview API doesn't even expose a way to run regular `WHERE` queries, so a full dvjs snippet is probably less likely. I'm constrained by what the API can do, you see?

**Comment by HEmile** [comment]
Isn't it possible to just directly execute that dataviewjs block as js code? Or will it not pick up the dv api calls then

**Comment by SkepticMystic** [comment]
I don't _think_ it will recognise what `dv` is.
I guess it depends what context the code is executed in? But the console doesn't recognise `dv`, for example, so it won't work on a global scope

**Comment by HananoshikaYomaru** [comment]
I don't know if this works. I can write normal js code in dvjs codeblock. Can I call a breadcrumb API in the dvjs codeblock to update the breadcrumbs? Then I can use both dvjs and breadcrumbs.

But for sure the dvjs file must be able to run in background.

**Comment by SkepticMystic** [comment]
@HananoshikaYomaru I don't know if you've seen this message yet, but I've exposed an API you can use in dvjs blocks: https://discordapp.com/channels/686053708261228577/855181471643861002/942003316123119646

**Comment by HEmile** [comment]
@HananoshikaYomaru I think you'd be able to set a variable called dv to getAPI() to ensure the javascript would recognize it. At least that's how it works in other languages, I've never done this in Javascript.

**Comment by SkepticMystic** [comment]
Note, there's a Dataview API method called `executeJS` that looks promising. I need to see if it's a superset (can execute regular dv queries as well), or if I need a way to specify. Also, what shape does it return?
