### ISSUE TITLE
FR: Define Implied relationships *per hierarchy*

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#338]
The toggles for the implied relationships are fantastic, and were a game changer for my workflow. However, I am noticing that I'd like to have implied siblings for one hierarchy and *not* have implied siblings for an other hierarchy. Being able "customize" specific hierarchies also reflects much better the spirit of the hierarchies: that they represent fundamentally different types of relationships.

<img width="1043" alt="Screenshot 2022-02-10 12 32 38" src="https://user-images.githubusercontent.com/73286100/153400755-1580e471-bf48-45df-8102-75d8140cf3e3.png">

**Comment by safrilth** [comment]
Do you mean.. 
Instead global settings, we can localize setting for each hierarchy ? 

I love that idea.. 

It reminds me kanban plugin that have :
- global settings
- board settings

**Comment by pawel-ilnicki** [comment]
Hi, @chrisgrieser - suppose you have two hierarchies:

1. First hierarchy
   - `up` for up
   - `down` for down
2. Second hierarchy
   - `parent` for up
   - `child` for down

Do I understand you correctly that you would **NOT** like siblings to be created between these two hierarchies?

Two notes sharing the same `up` is fine - display `same`. But one note with `parent` and the other with `up` should not be implied as `siblings` or `same`, right?

**Comment by pawel-ilnicki** [comment]
But... if you meant that one hierarchy shouldn't have siblings, for example, all you need to do is delete them:
![image](https://user-images.githubusercontent.com/98173950/199809781-06bf4a14-d64e-4f02-bdef-5696f7e4567c.png)

**Comment by SkepticMystic** [comment]
Added in the rebuild: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
Gonna close this out
