### ISSUE TITLE
[Feature] Activate leaf if note is already open

### ISSUE THREAD

**Issue by kometenstaub** [SkepticMystic/breadcrumbs#34]
If I click on a link in the l/m view, if the note is already open but not in the active leaf, I would like the note not to open in the current leaf, but activate the leaf where it is already open.

(This would be very useful when combined with sliding panes.)

**Comment by SkepticMystic** [comment]
Ahh I like this idea! I can try get that working. I'll check if the note is already open, then switch to it if it is. Otherwise, open the note as normal

**Comment by SkepticMystic** [comment]
This is partly working. If a note is already open, then clicking the link for it in the m/l view, will switch to it instead of opening it again.
This doesn't work for the trail though...
