### ISSUE TITLE
Add more than one direction in codeblock

### ISSUE THREAD

**Issue by adeldaoud** [SkepticMystic/breadcrumbs#342]
The code examples for codeblock shows how to add one direction "dir". But I wonder how to add several directions in the same view. I tried variants of the following code but that did not work. Any ideas?

```breadcrumbs
type: juggl 
dir: {next, down}
layout: force-diracted
fdgdLayout: d3-force
depth: 0
navigator: true

**Comment by SkepticMystic** [comment]
This is now possible in V4 :)
See the link at the top of the README for more info on the beta version, and see the docs to learn about the new codeblock fields: https://publish.obsidian.md/breadcrumbs-docs/Views/Codeblocks
