### ISSUE TITLE
easy paste index to plantuml wbs

### ISSUE THREAD

**Issue by mattjastremski** [SkepticMystic/breadcrumbs#343]
**Is your feature request related to a problem? Please describe.**
Limited in ability to use index in other tools / plugins - eg to visualize hierarchies

**Describe the solution you'd like**
A breadcrumb command (or option for existing commands) that renders the output of "copy a local index" / "copy a global index" in the format that the plantuml wbs diagram expects, eg:

```
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
```
_or_
```
+ Business Process Modelling WBS
++ Launch the project
+++ Complete Stakeholder Research
+++ Initial Implementation Plan
++ Design phase
```
(with or without double square brackets)

so that when pasted into a plantuml codeblock (with @startwbs and @endwbs), the hierarchy is rendered as a static image.
![image](https://user-images.githubusercontent.com/10131607/154165408-aab6735e-722e-405c-949b-9dd2d11f08d1.png)

**Describe alternatives you've considered**
Some type of script that replaces the existing output with this type of notation.

Inspired by the issue at https://github.com/HEmile/juggl/issues/116

**Comment by SkepticMystic** [comment]
Hey @mattjastremski , thanks for the detailed issue.
For now, I recommend using a Templater script or something similar to do this.
Something like:

1. Split index into lines
2. Check how many spaces there are before the bullet point on each line
3. Replace those spaces with the same number of `*`'s
4. Merge the lines back together into a string
