### ISSUE TITLE
FR: Hierarchy Notes works when outline contains words which isn't a link

### ISSUE THREAD

**Issue by LoneFireBlossom** [SkepticMystic/breadcrumbs#347]
**Is your feature request related to a problem? Please describe.**
I use outline to organize my notes in Obsidian.
But I find that if outline contains words which isn't a link, breadcrumbs will not work:

![CleanShot 2022-02-18 at 10 44 53](https://user-images.githubusercontent.com/50087596/154608068-b7b87c3f-9f05-494d-997b-ba14813f458c.gif)

**Describe the solution you'd like**
I hope breadcrumbs can work in this situation.

**Comment by SkepticMystic** [comment]
Hmmm I see... The way I get Hierarchy Notes to work depends on the way Obsidian sees lists. So if you have a list item with no links in it, I can't see that working. Perhaps you can use a different syntax, or comment out the no-link items? `%%- comment %%`
