### ISSUE TITLE
FR: Hierarchy Notes doesn't warn when outline includes comments

### ISSUE THREAD

**Issue by LoneFireBlossom** [SkepticMystic/breadcrumbs#348]
**Is your feature request related to a problem? Please describe.**
When I write MOC in Obsidian, I usually want to write some comments before the link.
But if I use Hierarchy Notes, it will warn me. For example:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/50087596/154612459-0a71f7be-3f4d-42cd-92a6-af1cc6e31104.png">
I think the warning should be removed.

**Describe the solution you'd like**
I know this warning is from "Specifying Different Up Fields: You can tell Breadcrumbs to override the default up field name, by putting the field name you want before the note".
But I think it can be changed. For example, breadcrumb will only recognize specific grammar before the link.

**Comment by HananoshikaYomaru** [comment]
I tried. The comments does not work in front of the link but works after the link, can you simply put the comment after the link?

**Comment by LoneFireBlossom** [comment]
> I tried. The comments does not work in front of the link but works after the link, can you simply put the comment after the link?

😲Oh, I see.
So this is just a feature request😂

**Comment by SkepticMystic** [comment]
Yeah, as @HananoshikaYomaru says, a comment before the link won't work (BC tries to use it as a field). But a comment after is fine. Does that work for you? I think it might have to be a breaking change to support only a specific syntax infront of the link

**Comment by LoneFireBlossom** [comment]
Yes, it works.
So if my feature request needs break change, I think it's ok to change my behavior. 😂
