### ISSUE TITLE
Bug: line numbers don't line up when breadcrumb trail is shown

### ISSUE THREAD

**Issue by avh4** [SkepticMystic/breadcrumbs#349]
**Describe the bug**

When breadcrumb trail view is shown in the editor, the line numbers gutter is not shifted down to account for it, so the line numbers no longer line up with the lines.

**To Reproduce**
1. Enable line numbers: Settings -> Editor -> "Show line number"
2. Install and enable Breadcrumbs plugin
3. Enable trail view in editor: Settings -> Breadcrumbs -> Views -> Trail/Grid/Juggl -> "Show Breadcrumbs in Edit/Live-Preview Mode"
4. Open a note
5. See line numbers don't line up anymore

**Expected behavior**
Line numbers should be moved down to account for the inserted breadcrumb trail view.

**Screenshots**
The blank line should be line 1, and the list item bullet should be line 2:
<img width="274" alt="Screen Shot 2022-02-19 at 1 13 26 PM" src="https://user-images.githubusercontent.com/1222/154819271-c0a704e9-2b72-459a-aee0-0e40442e4289.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 0.13.23

**Additional context**
Idea for how to fix: when `div.BC-trail` is added to `div.cm-contentContainer`, a corresponding element with height set to the computed height of the `div.BC-trail` should be added to either `div.cm-gutter` or `div.cm-gutters`.

**Comment by SkepticMystic** [comment]
Thank you for your idea to fix this! I'll give it a try :)

**Comment by SkepticMystic** [comment]
@avh4 I can't quite figure out what I'm doing wrong here...
After adding the BC-trail, I try to grab it's height off the div element, but it always comes back as `0`.
Whether I use `trailDiv.offsetHeight`, `trailDiv.clientHeight`, or `trailDiv.getBoundingClientRect().height`, it always comes back 0. Any thoughts?

**Comment by SkepticMystic** [comment]
Fixed in #384, thanks @artem-barmin :)

**Comment by Pummelfisch** [comment]
Sorry for necro-bumping this, but I am experiencing this problem again when enabling trail in live-preview. Has something changed or am I missing something else?

**Comment by SkepticMystic** [comment]
Hey @Pummelfisch, no worries. I think there was a regression, indeed.
If you haven't heard elsewhere, I've rewritten like 95% of Breadcrumbs, and it's available via BRAT under V4. See here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
Once you've read the breaking changes, consider updating to V4 where this issue is resolved
