### ISSUE TITLE
Bug: Tree View shows notes with multiple parents incorrectly

### ISSUE THREAD

**Issue by joellti** [SkepticMystic/breadcrumbs#351]
**Describe the bug**

Support a note hierarchy that looks like one below
```
- a
  - b
    - d
  - c
    - d
```

Basically, note d has two parents: b and c. And note b and c have the same parent note a.

When note a is the active note, the tree view looks like the one below
```
- c
  - d
- b
```
when it's supposed to be
```
- c
  - d
- b
  - d
```

When either note b or note c is the active note, the tree view shows the d as the child as expected.

**To Reproduce**
1. Create note a, b, c, d
2. Make note a the parent of note b and c
3. Make note d the child of note b and c
4. Open note a and go to tree view

**Expected behavior**

When note a is the active note, the tree view should look like the one below
```
- c
  - d
- b
  - d
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows and Ubuntu
 - Version 2.55.2

**Smartphone (please complete the following information):**
 - Device: Not tested
 - OS: N/A
 - Version N/A

**Additional context**

**Comment by SkepticMystic** [comment]
Thanks @joellti. This issue is most likely related to #241. The traversal algorithm doesn't work perfectly for some graphs, hence some nodes being missing. I'm still not sure how to fix it, but it's helpful to have some more info

**Comment by SkepticMystic** [comment]
Hey @joellti, please consider upgrading to v4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md. This issue is resolved there
