### ISSUE TITLE
Bug: Notes with multilple different type of parents won't imply correct siblings.

### ISSUE THREAD

**Issue by Dekirumonka** [SkepticMystic/breadcrumbs#352]
**Describe the bug**
First I enable the Relationships - Same parent is Siblings in settings.
then, say there are two different hiearchies:
(parent)(sibling)(kid)()()
(employer)(coworker)(employee)()()
and 4 guys name A, A1,A2, B. 
A is the parent of A1 and A2, B is an employee of A, but not A's kid.
so I wrote 4 notes:

> 
> #### A  
> kid:: [[A1]]
> kid:: [[A2]]

> #### A1

> #### A2

> #### B
> employer:: [[A]]
> 

I would expect B is not a kid of A, and A1 is not an employee of A.
But it will imply B is a sibling of A1 and A2, and A1 A2 become coworkers and siblings of B.

**Screenshot:**
I framed the relationships that's not correct:

![图片](https://user-images.githubusercontent.com/17879091/154864732-77128188-88c7-4a84-a4a8-2af9ddead375.png)

And it won't help if I change the _employer:: [[A]]_ in B to _employee:: [[B]]_ in A:

![图片](https://user-images.githubusercontent.com/17879091/154864753-4acf9c27-4f9d-4ae0-87fe-95ec34c609bd.png)

**Desktop**
 - OS: Windows 10
 - Version 10.0.19043

**Software**
- Breadcrumb 2.55.2
- Obsidian 0.13.23

**Comment by ayapcck** [comment]
I've encountered this issue as well!

**Comment by SkepticMystic** [comment]
This should be resolved in v4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md.
Consider upgrading to the beta. Will close this out for now
