### ISSUE TITLE
Bug: Dataview Doesn't Work With Aliased Link

### ISSUE THREAD

**Issue by tristonlees** [SkepticMystic/breadcrumbs#359]
When using Dataview to create a breadcrumb structure, the plugin does not work nicely for links that use aliases. E.g. `down:: [[file.md|File]]` will not work as `down:: [[file.md]]` would. It also prevents any following sections in that file to not be read correctly, though any associations created before are registered.

The expected behaviour is just for the the above example, and those similar, to work as with any other. Unless there is any reason in particular why this hasn't been implemented, I assume it is just an oversight.

 - OS: Windows
 - Obsidian Version 0.13.33
 - Plugin Version 2.55.2

**Comment by SkepticMystic** [comment]
Hey @tristonlees. 
Does this still happen? The example you shared works fine for me
![image](https://user-images.githubusercontent.com/70717676/163718586-79724d14-301c-4f50-977d-b06ec6eb41f3.png)

**Comment by SkepticMystic** [comment]
Gonna close this out.
Please let me know if this still happens on the latest versions of BC and Obsidian
