### ISSUE TITLE
[Feature] Show multiple paths to index note

### ISSUE THREAD

**Issue by kometenstaub** [SkepticMystic/breadcrumbs#36]
If there are multiple paths to the index note (or the last parent note #35), there should be an option to show them all or the shortest path.

**Comment by SkepticMystic** [comment]
There is now basic functionality for this as of 0.7.0.
However, it only works when given multiple explicit index notes. If you don't have an index note in settings, you will still only see one path

**Comment by SkepticMystic** [comment]
This should be working much better now.
In 0.7.3 there is some weird behaviour where it doesn't always show the full path. But overall, it's a useful feature.
@kometenstaub will you give it a try and let me know. You no longer need to have an indexNote to show multiple paths up the parent tree

**Comment by SkepticMystic** [comment]
Given that this is now possible (thank you @HEmile :D) I'm gonna consider this issue closed!
![image](https://user-images.githubusercontent.com/70717676/124947492-29c7f180-e010-11eb-9f42-c90062352c34.png)

**Comment by mkasu** [comment]
I can't get this feature to work. It once worked briefly for me in 0.8.17 or so I think, but in newer versions I just see the shortest path, no matter what settings. I have selected "all paths" in options and also set an index/home note. 

I have this note with two parent notes which should display two different routes to the home note, but it only shows one, the  second route via "Vision and Language" is not shown:

<img width="896" alt="Screenshot 2021-07-20 at 16 52 21" src="https://user-images.githubusercontent.com/798036/126283018-99ee08e6-3796-4541-aa06-ab07235b1778.png">

Am I doing something wrong or is this a regression?

**Comment by SkepticMystic** [comment]
@mkasu can you message me on Discord, it'll be easier to debug from there :)
My handle is @SkepticMystic
