### ISSUE TITLE
Bug: Toggle Show Trail/Grid in Edit & LP mode - toggles off but not on

### ISSUE THREAD

**Issue by laurastephsmith** [SkepticMystic/breadcrumbs#364]
**Describe the bug**
The command "Toggle Show Trail/Grid in Edit & LP mode" can toggle the trail off, but doesn't toggle it back on. Thanks! :)

**To Reproduce**
1. Get a view of a breadcrumb trail on screen in live preview mode.
2. Run command  "Toggle Show Trail/Grid in Edit & LP mode"
3. Observe trail disappears.
4. Run command  "Toggle Show Trail/Grid in Edit & LP mode"
5. Trail doesn't come back.

**Expected behavior**
Trail comes back.

**Desktop**
 - OS: Debian
 - Breadcrumbs 2.55.2

**Comment by SkepticMystic** [comment]
You're absolutely right! Thanks, this should be fixed in the latest release

**Comment by laurastephsmith** [comment]
Perfect now, thank you @SkepticMystic!
