### ISSUE TITLE
Bug: not working in one of my vault

### ISSUE THREAD

**Issue by dowwang** [SkepticMystic/breadcrumbs#366]
**Describe the bug**
work normally in the other two vaults, but don't work in the largest vault. No index shown.

**To Reproduce**
after installed, in console, there is an error:
	- (unknown) TypeError: Cannot destructure property 'frontmatter' of 'app.metadataCache.getFileCache(...)' as it is null.
    at eval (eval at <anonymous> (app.js:1), <anonymous>:35082:17)
    at Array.map (<anonymous>)
    at getObsMetadataCache (eval at <anonymous> (app.js:1), <anonymous>:35081:27)
    at buildMainG (eval at <anonymous> (app.js:1), <anonymous>:35182:15)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:64430:36)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13914012/161463700-965342da-36ff-47a5-9620-7c4156ea60f5.png)
![image](https://user-images.githubusercontent.com/13914012/161463260-e13408b9-ce16-4f97-b5c7-8fe1df96f28b.png)

**Desktop (please complete the following information):**
 - OS:  win10
 - obsidian Version : 0.14.2
 - breadcrumbs: 2.55.2

**Comment by dowwang** [comment]
solved by creating a new vault, and tranfers the old files into the new vault

**Comment by SkepticMystic** [comment]
Hey @dowwang.
When this error happened, were there any notes in the vault at all, or was it empty?

**Comment by dowwang** [comment]
sorry for late answer

there are lots of notes in the vault

**Comment by SkepticMystic** [comment]
Gonna close this since it seems to be working after your change
