### ISSUE TITLE
FR: Allow folding of indents in the 'Down' view

### ISSUE THREAD

**Issue by Brettelectric** [SkepticMystic/breadcrumbs#367]
The 'Breadcrumbs Down' window on the right-hand-side is very useful for getting an overview of my note structure, but it can take a fair bit of scrolling to get to the category and note that I am looking for.

It would be great if we could have those little triangle buttons to fold or unfold tiers/indents/categories so that we can skip over parts of the structure that we are not looking in, rather than having to scroll through it all.

Edit: I know 'folding' is something that you can do in the base Obsidian program, for headings or paragraphs.
Also I have seen it implemented in a core side-bar plugin - Outline

Thanks!

**Comment by SkepticMystic** [comment]
Hey @Brettelectric, thanks for the FR!
I agree, this would be useful. Unfortunately, the way the Tree View is implemented is actually kinda hacky 😅 there actually isn't any nesting going on once it is displayed. It's jsut a whole bunch of sibling divs with different numbers of spaces infront of them:

![image](https://user-images.githubusercontent.com/70717676/163719265-0ed1489d-8f1e-4aea-bad7-66b08580fc71.png)

So I can't add folding sections without completely revamping how it works.
I may do this in the future, but it'll take a little while

**Comment by SkepticMystic** [comment]
@Brettelectric I'm happy to say this issue is now closed :)
It's available in the V4 beta, see the link in the README for more info
