### ISSUE TITLE
CodeBlock

### ISSUE THREAD

**Issue by Llamahat** [SkepticMystic/breadcrumbs#368]
Code block does not allow alphabetical sorting when displaying in type: tree. This then misaligns with the right side bar allowing for alphabetical sorting.
Would be great to have a "sort: alphabetical" or add the ability for a dataview field to sort using something like "sort file.name asc" or "sort rating asc".

**Comment by SkepticMystic** [comment]
I get you. This is kind of difficult though. If you sort the top level, for example, all the other items nested under each top-level item need to be moved with it.
This is possible, but the way I've implemented the Tree makes it difficult to do this. 
See my comment in #367 for a bit more info

**Comment by SkepticMystic** [comment]
This is now possible in the v4 beta, please see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
