### ISSUE TITLE
FR: BCAPI call to refresh index (ideally with an optional callback when the index is ready)

### ISSUE THREAD

**Issue by zsviczian** [SkepticMystic/breadcrumbs#369]
https://discord.com/channels/686053708261228577/929513881041248266/962241581270855680

**Comment by SkepticMystic** [comment]
Hey @zsviczian! I'm gonna work on this now.
Just a question about the callback, what would it take as arguments?

`BCAPI.refreshIndex(cb: () => any)`

**Comment by zsviczian** [comment]
I think just a function without arguments letting the other app know that the index was refreshed should be sufficient. If it is not too much trouble, then a list of the pages that were updated (assuming a partial update) would be nice.

**Comment by SkepticMystic** [comment]
For the first option, can't you just await the `refreshIndex` call? Or chain `.then`?
For the second option, the index is not partially updated, so I won't be able to do that

**Comment by SkepticMystic** [comment]
Closing as complete. The `refreshIndex` function is async, so you can just await it and run your callback after
