### ISSUE TITLE
Automatically update links if a file was renamed

### ISSUE THREAD

**Issue by Ljqd** [SkepticMystic/breadcrumbs#371]
I'm not sure, is this feature really not implemented or this is some kind of a bug.

### Description:
Assume that we have two files, Note A and Note B with next relations:
![image](https://user-images.githubusercontent.com/30119650/163198053-e7615e3a-a3e0-4472-a21f-4dfd738cb2e0.png)
![image](https://user-images.githubusercontent.com/30119650/163198137-f3f7da33-b738-4fd3-9df9-810c3f7ee7bb.png)

Now, we change the title of 'Note B' to 'Note C'.
I expected that after this renaming the link in the 'Note A' will automatically updated just like it happens with regular obsidian's links.

But instead of that - the link remains unchanged in the note A and we have a situation like this: 
![image](https://user-images.githubusercontent.com/30119650/163200872-84459a96-37c1-4f4b-a78c-33c56f4fe136.png)
![image](https://user-images.githubusercontent.com/30119650/163199239-24def0d8-cf9f-46c7-9575-69c640740596.png)

**Comment by SkepticMystic** [comment]
Hey @Ljqd.
Unfortunately, this is not something I can (easily) fix. Obsidian doesn't recognise links in YAML, so it is actually a little hacky to treat them as such. Until Obsidian adds this functionality, I recommend using [Dataview inline fields](https://blacksmithgu.github.io/obsidian-dataview/data-annotation/#pages) instead (the link name will be updated when the file name is changed).
