### ISSUE TITLE
[FR] Display Different Hierachies Through Tabs

### ISSUE THREAD

**Issue by SlRvb** [SkepticMystic/breadcrumbs#372]
**Is your feature request related to a problem? Please describe.**
If I included all the files in a folder using multiple hierarchies, it's incredibly hard to find the file I'd want to look at. Currently I haven't had this issue yet, but this example is one where I might just encounter it.

This is the current breadcrumbs setup for my media analysis of a show, I can end up with 100s of episodes in this panel that would hide the subplots at the bottom. While I could just create a new hierarchy and move it up, I feel as though a separate view for that new separate hierarchy would be the cleanest way for me to personally move about my files.
![Obsidian_IevYZPl4Pc](https://user-images.githubusercontent.com/54087190/163780994-abdf1e6e-c050-48df-b3f3-6dcb820e0488.png)

**Describe the solution you'd like**
Some **Tabs** to view different hierarchies, maybe looking something similar to what you've done for the Graph Analysis plugin, but for user created hierarchies. An `All` tab view would also be good as the default view that opens up.
![Obsidian_HsU6MNxAJT](https://user-images.githubusercontent.com/54087190/163780356-8ffea0f6-6fdf-4153-914c-73df10381a91.png)

**Comment by SkepticMystic** [comment]
I'm gonna consider this "in progress", since you can now collapse _directions within a hierarchy_: 


![Image](https://github.com/SkepticMystic/breadcrumbs/assets/70717676/d2d84004-0b13-48bd-8b86-1f2c3c0d426d)


I'll try adding a way to collapse all directions in a whole hierarchy at once. That should achieve alot of the same effect as the original issue

**Comment by SkepticMystic** [comment]
@SlRvb I've just added a setting to collapse the Matrix View dropdowns by default, and a button to quickly open/close them from the view itself
