### ISSUE TITLE
Bug: 2 "alias" related issues

### ISSUE THREAD

**Issue by laphylee** [SkepticMystic/breadcrumbs#373]
For example, when node [[App]] has an alias "app":

Case 1: With Dendron enabled, I created a new node [[app.Chrome]], the Matrix view will show the parent as "app", but clicking it will lead to creating a new empty node [[app]], instead of the existing node [[App]]. 

Case 2: When I created a node [[app1]] and add this in frontmatter: "up: [[App]]". and then create a node [[app2]] with "up: [[app]]" (lowercase, which is the alias). But in app1's matrix view, I can't see "app2" as its sibling. Same thing happens in app2's matrix view.

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue. I think in both cases, this isn't the "expected" behaviour, but I also don't think it's wrong. Aliases are different from the file path - they have to be specified differently `[[path|alias]]`. If Obsidian is treating `[[app]]` as distinct from `[[App]]`, I don't think Breadcrumbs should _not_ do that.
Having said this, Breadcrumbs V4 works differently under the hood, so this issue might be resolved anyway. But I'm going to close this out as not planned.
