### ISSUE TITLE
Why can't I get Date Note to work?

### ISSUE THREAD

**Issue by SkepticMystic** [SkepticMystic/breadcrumbs#376]
### Discussed in https://github.com/SkepticMystic/breadcrumbs/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **Gattomarino** April 18, 2022</sup>
Hi, I've been loving the plugin since I discovered it (yesterday!) but I have trouble understanding how to use the Date Notes feature.
Simple scenario:
- Daily Notes all in one giant folder, title for the notes is YYYY-MM-DD
- I set Date Notes to the required format, which *I think* should be: YYYY-MM-dd
- I don't get any result out of this. I tried some other formats to no avail.
Note: My real-usage scenario would be more complicated with year and month subfolders, like so: Journals/YYYY/MM/DD MMM YY and the "Override locale" Calendar option should be set to my locale (specifically, "it"), returning e.g. Journals/2022/01/01 Gen 22
Right now I don't understand if it's just me not understanding what format to use or there's something more to it. (I don't know anything about programming and I couldn't really follow your info on debugging, sorry). Thanks for any help!</div>

**Comment by SkepticMystic** [comment]
Hey @Gattomarino! Thanks for the post.

I think the date format you've entered is slightly off. Give this a try and let me know `yyyy-MM-dd` :)

**Comment by SkepticMystic** [comment]
Currently, the folder method of months and years won't work, but that's maybe something to be added in future

**Comment by Gattomarino** [comment]
Thanks; still not working tho... I managed to open the Console and I got an
error upon loading the plugin in a new vault. Something about a broken
promise... very poetic :)
(It's actually "Uncaught (in promise) TypeError: Cannot destructure
property 'basename' of 'app.workspace.getActiveFile(...)' as it is null
etc. etc.")
Let me know if it's ok to post it here or elsewhere. It repeats identically
when I change the date format in the Date Notes settings.
I forgot to mention my Mac is ancient... I'm on 10.12.6.

Il giorno lun 18 apr 2022 alle ore 18:02 SkepticMystic <
***@***.***> ha scritto:

**Comment by SkepticMystic** [comment]
Haha it is kinda poetic :p

I don't think it will work in an empty vault. Can you try adding some regular notes, and some dated notes using the date format specified.

**Comment by Gattomarino** [comment]
It still won't work on any of my vaults; and I'm also experiencing new
issues! For example, two new notes created today with a up: statement
refuse to show in the matrix or list view. The old ones still do...
My graph view also is not displaying properly all of a sudden. Something
else must have gone wrong along the way...

Il giorno lun 18 apr 2022 alle ore 20:55 SkepticMystic <
***@***.***> ha scritto:

**Comment by haoadoreorange** [comment]
@SkepticMystic It doesn't work on my side either, I verified everything. Still the links doesn't show up. Do you have any idea why ?

**Comment by charleshan** [comment]
It's not able to link to prev/next when there are missing daily notes.

## Expected
Given these two notes [[2024-01-06]], [[2024-01-08]], the second note should be linked from to the first. 

## Actual
It either doesn't link anything or links to a non-existing note.

**Comment by SkepticMystic** [comment]
@charleshan I don't think that's how it was written to work.
Date notes only point to the next _day_, not the next daily note that _exists_.

**Comment by charleshan** [comment]
@SkepticMystic I see... but isn't that the expected behavior? "Daily notes: open previous/next daily note" commands do this.

**Comment by SkepticMystic** [comment]
@charleshan yeah, that does make sense. At the moment, that's not how it behaves though.
I'm really not promising anything (as I haven't worked on this project in ages), but you can open a FR for this

**Comment by charleshan** [comment]
@SkepticMystic I understand

**Comment by SkepticMystic** [comment]
I'm going to consider the original issue closed, as I've rewritten the plugin in V4. Date Notes should work more consistently now. See the first link in the README for more info about updating to the V4 beta

**Comment by SkepticMystic** [comment]
@charleshan this is now possible in V4 :) See here for more info: https://github.com/SkepticMystic/breadcrumbs#date-notes
