### ISSUE TITLE
Bug: console error!

### ISSUE THREAD

**Issue by YIRU69** [SkepticMystic/breadcrumbs#377]
**Describe the bug**
A console error when I use it.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48148292/163919554-b1ebc37d-2103-4f26-ba37-29f63d3bc0d4.png)
![image](https://user-images.githubusercontent.com/48148292/163919613-7468a944-0e25-4661-9171-e52067bcb0db.png)

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Version [2.58.1]

**Additional context**
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">Uncaught <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read properties of null (reading 'basename')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at eval (eval at &lt;anonymous&gt; (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:1494667" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">app.js:1:1494667</span>), &lt;anonymous&gt;:42281:59)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at t.e.tryTrigger (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:903075" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">app.js:1:903075</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at t.e.trigger (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:903008" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">app.js:1:903008</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at t.trigger (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:1467542" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">app.js:1:1467542</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at t.activeLeafEvents (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:1459183" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">app.js:1:1459183</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at a (<span class="devtools-link" role="link" tabindex="-1" title="app://obsidian.md/app.js:1:263910" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">app.js:1:263910</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(32, 33, 36); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | eval | @ | VM174:42281
-- | -- | -- | --
  | e.tryTrigger | @ | app.js:1
  | e.trigger | @ | app.js:1
  | t.trigger | @ | app.js:1
  | t.activeLeafEvents | @ | app.js:1
  | a | @ | app.js:1
  | setTimeout (async) |   |  
  | e.tryTrigger | @ | app.js:1
  | e.trigger | @ | app.js:1
  | t.trigger | @ | app.js:1
  | t.activeLeafEvents | @ | app.js:1
  | a | @ | app.js:1
  | setTimeout (async) |   |  
  | l | @ | app.js:1
  | t.setActiveLeaf | @ | app.js:1
  | checkCallback | @ | app.js:1
  | Mz | @ | app.js:1
  | e.executeCommandById | @ | app.js:1
  | executeObsidianCommand | @ | VM255:11776
  | executeCommands | @ | VM255:11690
  | await in executeCommands (async) |   |  
  | run | @ | VM255:11685
  | onChooseMacroType | @ | VM255:16108
  | await in onChooseMacroType (async) |   |  
  | execute | @ | VM255:16084
  | callback | @ | VM255:16158
  | Mz | @ | app.js:1
  | e.executeCommandById | @ | app.js:1
  | execute | @ | VM160:98
  | eval | @ | VM160:85
  | Promise.then (async) |   |  
  | getSuggestions | @ | VM160:84
  | t.updateSuggestions | @ | app.js:1
  | t.onInput | @ | app.js:1

</span></div>
</body>
</html>

**Comment by YannickTemplay** [comment]
+1

**Comment by SkepticMystic** [comment]
This should be resolved in the latest versions
