### ISSUE TITLE
Bug: Outgoing Dataview Breadcrumbs don't work

### ISSUE THREAD

**Issue by Liberonscien** [SkepticMystic/breadcrumbs#378]
**Describe the bug**
BC-dataview-notes aren't connecting properly.
**To Reproduce**
Make a 
`BC-dataview-note: ''[[Random Note]]'
BC-dataview-note: Children`
Refresh Index
**Expected behavior**
The note should connect to Random Note
 - OS: Windows
 - Version 10

**Comment by SkepticMystic** [comment]
Hey @Liberonscien, thanks for the issue.
Just to be sure, the exact query you posted as an example has some errors in it. Can you try this instead and let me know if it works:
```
---
BC-dataview-note: "[[Random Note]]"
BC-dataview-note-field: Children
---
```
