### ISSUE TITLE
Visual Bug: The depth selector of the Grid View seems to visually overstep on the "next" note

### ISSUE THREAD

**Issue by I-Pch** [SkepticMystic/breadcrumbs#379]
### Describe the bug
I think there's a small CSS problem with the brand new Grid View Depth Selector 😇 .

When the selector is inactive (not hovered), other than the height of the border (which is higher than the line it currently sits in the grid) there's part of the "minus 1 level" visible and both (border & button) overstep the line where the "next" note is supposed to be. (See screenshot 1 😊 )

When the selector is active (hovered), the "minus 1 level" goes back to its place but the border still appears over the "next" note line kind of making it look like it's strikethrough (See screenshot 2 😊 )

(This has been tested with the default Obsidian Dark Theme and just 4 CSS snippets (1 for progress bars, 2 for admonitions/callouts and 1 for the plugin Supercharged links)

### Expected behavior
The depth selector shouldn't visually come over the "next" note 😇  (I guess 😅 ) 

#### Screenshot 1 : Partially visible and overlapping "minus 1 level" button
<img width="521" alt="Depth Selector - Inactive" src="https://user-images.githubusercontent.com/77828085/164273551-6ba34112-fc0e-4cf4-8664-6f1928103239.png">

#### Screenshot 2 : Overlapping borders
<img width="521" alt="Depth Selector - Active" src="https://user-images.githubusercontent.com/77828085/164274161-cff947cd-743d-4bf0-8b40-fbf5b4c542a7.png">

### Desktop
 - `MacOS Big Sur 11.6.5`
 - `Obsidian v0.14.6` + Default Obsidian Dark Theme
 - `Breadcrumbs 2.58.1`

### Additional context
Not tested on mobile 😇

**Comment by SkepticMystic** [comment]
Thanks for the issue :)
V4 uses a different layout, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
Gonna close this out as complete
