### ISSUE TITLE
[WAITING] Have to trigger `draw` manually for ls/m and trail to show initially on mobile

### ISSUE THREAD

**Issue by SkepticMystic** [SkepticMystic/breadcrumbs#38]
Probably because the dv indices take longer to load on mobile

**Comment by SkepticMystic** [comment]
@kometenstaub does this still happen?

**Comment by kometenstaub** [comment]
On Android yes, on iOS not.
So it must be because of the slower processor on Android.

**Comment by SkepticMystic** [comment]
I will consider this closed now that one can customise the time to wait for dv to load
