### ISSUE TITLE
Output a field on the code block like what dataview list does

### ISSUE THREAD

**Issue by ooker777** [SkepticMystic/breadcrumbs#380]
For example:
```
- parent: done
 - child: pending
  - grandchild: doing
```
A use case would be that the notes belongs to an issue tree, and it would be great if I can know the status of each note.

I also have another suggestion: [Hijacking Dataview code block for complex query](https://github.com/SkepticMystic/breadcrumbs/discussions/381)

**Comment by SkepticMystic** [comment]
This has been added in v4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
Gonna close this out
