### ISSUE TITLE
Bug: Data loss Breadcrumbs plus Longform plugin

### ISSUE THREAD

**Issue by pdworkman** [SkepticMystic/breadcrumbs#382]
I haven't managed to figure out exact steps to replicate this yet (have been doing too much damage control) but I have seen this happen a few times the last couple of days. 

I edit a Longform scene in Obsidian, then copy the revised text and paste it into Grammarly, and it is the unedited version. Go back to Obsidian, and it has reverted to the previous version. Very irritating. 

This appears to be a conflict with Breadcrumbs plugin, as I cleverly decided to use Next in the metadata to allow me to Next/Previous navigate through scenes. The first thing I have been changing when I start my editing on a scene is to add the Next: [[scene name]] into the metadata. When I copy and paste the scene into Grammarly, the Next: line is missing, and so are the rest of my edits. Or at least some of them. 

When I disabled Breadcrumbs, I stopped experiencing the loss of edits. 

I will keep watching and try to give you replicatable steps. 

Mac OS 11.6.5
Longform 1.1.0
Breadcrumbs 2.58.1

I also have Dropbox running, but the reversion seems to occur before Dropbox has a chance to back up the revised file. 

I have not experienced this in the other vault where I am using Breadcrumbs, which does not have Longform installed.

**Comment by SkepticMystic** [comment]
Do you still experience this issue? Do you have any other info to share that could help narrow it down? Any errors in the console?

**Comment by pdworkman** [comment]
No, I've never tried it again.

**Comment by SkepticMystic** [comment]
Alright, I'm gonna consider this closed. There haven't been other reports of data loss, with Longform or other plugins. Please reopen if you decide to try again and experience this problem
