### ISSUE TITLE
Bug: Breadcrumbs Picking Up Backslash \

### ISSUE THREAD

**Issue by SlRvb** [SkepticMystic/breadcrumbs#386]
**Describe the bug**
While using inline fields from dataview in a table with an alias, it seems the escape character `\` is being picked up by breadcrumbs and thus can't find the linked note. Both for the Matrix and Trail view.

**To Reproduce**

Paste this into a note:
```
| | |
| --- | --- |
| Pipe | (Parent:: [[Link to file\|Alias]]) |
```

**Expected behavior**
Ignore the escape character

**Screenshots**
![IZg9PtiYJW](https://user-images.githubusercontent.com/54087190/165435545-eb5d1e73-ba1a-4998-ac16-ee232a58f303.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 3.2.0
 - Obsidian: v0.14.7

**Comment by SkepticMystic** [comment]
> Depending how you write out the field value, it could be either.
> If you write `parent:: Is this [[Note\|Alias]]`, Dataview sees it as a string and so Breadcrumbs is the one who incorrectly parses it with the escape.
> But if you write it _just_ as a link `parent:: [[Note\|Alias]]`, then Dataview parses it before BC, and so it's on Dataview this time
