### ISSUE TITLE
Bug: All implied relations are being shown as real relation in the sidebar

### ISSUE THREAD

**Issue by onnyyonn** [SkepticMystic/breadcrumbs#387]
**Describe the bug**
All implied relations are being shown as real relation in the sidebar.

**To Reproduce**
1. Go to Breadcrumbs settings > Relationships
2. Enable 'make current note an implied sibling'
3. Current note shows up as real relation in the sidebar

**Desktop:**
 - Version 3.2.0

**Comment by SkepticMystic** [comment]
Thanks for the issue.
I am rebuilding the plugin at the moment, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
This issue is resolved in the beta, so I'm gonna close this out. Please consider upgrading, and share any feedback
