### ISSUE TITLE
Bug: List view and stats have disappeared 

### ISSUE THREAD

**Issue by Sigbert11** [SkepticMystic/breadcrumbs#390]
**Describe the bug**
In the latest obsidian update (possibly also also earlier) while matrix shows flawlessly 
- the BC panel's list view button is no more visible 
- the stats panel is gone too 
for both even no more in the command list (cmd-p)

**To Reproduce**
1. Go to 'a note with BC notations'
2. Click on 'BC panel or searching for BC stats command'
4. See error: while matrix view is fine — no button or panel

**Expected behavior**
in the BC panel a toggle button for list view used to be visible 

**Screenshots**
<img width="741" alt="Screenshot of Obsidian" src="https://user-images.githubusercontent.com/84449137/165972287-da6ad6b4-3406-43d4-b7c6-3d9b426d5648.png">
<img width="821" alt="Screenshot of Obsidian" src="https://user-images.githubusercontent.com/84449137/165972301-e2ae062a-4cb7-4feb-af82-bca867cfd5d4.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 12.3.1 (21E258)
 - Obsidian: 0.14.7 
 - BC 3.3.1

**Additional context**
additionally tried it in a separate vault with only very few plugins

**Comment by SkepticMystic** [comment]
Hey @Sigbert11 
That's right, I removed both in a recent release.
The List View was redundant, as it shows the same info as the Matrix View.
The Stats View does far too much computation for what it's worth, I feel. Not many people use it.
Both features were taking alot of resources to maintain and update, and I felt it wasn't worth it
