### ISSUE TITLE
Bug: 'Write breadcurmbs into current file' dose not use corret format  

### ISSUE THREAD

**Issue by xuey06** [SkepticMystic/breadcrumbs#391]
**Describe the bug**
When I used the  commond of 'Write breadcurmbs into current file' to write the connection into yaml. The format of results are not correct, shown as following:

````
---
up:
 - a
 - b
 - c
---
````

, which is not as:

````
---
up: ['a', 'b', 'c']
---
````
or not as:
````
---
up: [[a]], [[b]], [[c]]
---
````
How to solve this problerm?

**Comment by adzcai** [comment]
The first format you listed is valid YAML list formatting. See [YAML syntax](https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html)

**Comment by SkepticMystic** [comment]
Closing, as the output is indeed valid YAML, and the new Obsidian Properties feature hides it all anyway
