### ISSUE TITLE
Automatic prev-next ordered hierarchy notes

### ISSUE THREAD

**Issue by Cammagno** [SkepticMystic/breadcrumbs#392]
Now that there is a way to specify a prev-next order in hierarchy notes,
what about setting it to consider by default that the following item in a list (at the same level) is next to the previous one?

e.g.:

- [[1]]
  - [[1.1]]
    - [[1.1.1]]
    - [[1.1.2]]
    - [[1.1.3]]
  - [[1.2]]
1.2 is next of 1.1 (unless differently specified)
1.1.3 is next of 1.1.2 which is next of 1.1.1 (unless differently specified)

This will make it much easier to set a long list of ordered items

**Comment by jiajiala** [comment]
I really need this, too

**Comment by jiajiala** [comment]
`- [[xx]]

[[dd]]
[[dd~]]
[[dd~x]]
[[oo]]`
Structures like this should be recognizable by nature
oo is next of dd

**Comment by SkepticMystic** [comment]
You can now enable this for an entire List Note (previously Hierarchy Note) by adding the `BC-list-note-neighbour-field: <field>` to your List Notes. This only works in V4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md

Really quite happy with this feature :)

**Comment by Cammagno** [comment]
> In this example, it would be `BC-list-note-neighbour-field: next`, but it can also be `same`

Great!
Is next the default, or the BC-list-note-neighbour-field` is mandatory?

**Comment by SkepticMystic** [comment]
Mandatory for now, but it's reasonable for this to be a setting to apply to all List Notes. Will you open a separate FR for that?

**Comment by Cammagno** [comment]
> Mandatory for now, but it's reasonable for this to be a setting to apply to all List Notes. Will you open a separate FR for that?

Done: https://github.com/SkepticMystic/breadcrumbs/issues/515#issue-2191330579
Thanks!

**Comment by SkepticMystic** [comment]
For sure! Is it all working as expected?

**Comment by Cammagno** [comment]
> Is it all working as expected?

Not tested it yet because I'm travelling, but I'll do it ASAP!
