### ISSUE TITLE
Bug: Next/Prev commands not working on mobile iOS

### ISSUE THREAD

**Issue by derekvan** [SkepticMystic/breadcrumbs#394]
**Describe the bug**
On my desktop version, the "jump to next/prev" commands work well. On mobile, when I use the command (or when I create a button for the command in the toolbar), I get the following error message: "No note was found in next given the limited fields allowed:" . This error doesn't appear on the desktop when invoking the common on the same note--it just works.

**To Reproduce**
I have the following YAML header:
````
---
next: ['2022-05-07.md']
prev: ['2022-05-05.md']
week: ['2022-W19']
---
````

Invoking "Jump to first prev" on desktop takes me to the note, on iOS it gives the error listed above.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version Obsidian 0.14.9

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 15.4.1
 - Version Obsidian 1.2.1 (52)

**Additional context**

**Comment by SkepticMystic** [comment]
@derekvan can you try this on V4? I've rewritten this command

**Comment by derekvan** [comment]
Yeah, working fine for me on mobile version 1.5.11 (133)

**Comment by SkepticMystic** [comment]
Nice, on Breadcrumbs v4 right?

**Comment by derekvan** [comment]
Yes correct

**Comment by SkepticMystic** [comment]
Ok great, gonna close this out then. Thanks for testing
