### ISSUE TITLE
FR: Option to include Hierarchy Note in the hierarchy

### ISSUE THREAD

**Issue by imdadkadir** [SkepticMystic/breadcrumbs#398]
Love using the Hierarchy Notes in Alternative Hierarchies. Currently, to include the Hierarchy Note in the hierarchy you must go on the notes at the top of the hierarchy and manually point upwards to the Hierarchy Note. As my structures are constantly changing, it gets repetitive having to manually point to the Hierarchy Note and having to make sure I remove others if their position has changed.

**Describe the solution you'd like**
It would be great if there was an option to include the Hierarchy Note in the hierarchy.

**Comment by SkepticMystic** [comment]
Hey @imdadkadir :)
I've added support for this in the latest release. Toggle this setting on, and all hierarchy notes will become the parent of the top level items in that hierarchy note
![image](https://user-images.githubusercontent.com/70717676/180708695-168834e2-1772-4112-8883-2f566b886e79.png)
