### ISSUE TITLE
`BCAPI.dfsAllPaths()` returns an array of length 1

### ISSUE THREAD

**Issue by ooker777** [SkepticMystic/breadcrumbs#400]
I try `BCAPI.dfsAllPaths()` but it returns an array of length 1. Plus that if I use 
```
let bc = app.plugins.plugins.breadcrumbs
```
then the methods for BCAPII don't apply. I thought they are the same

Windows 11, Obsidian 0.14.6, Breadcrumbs 2.55.2

**Comment by SkepticMystic** [comment]
Gonna close this as a duplicate of #187
