### ISSUE TITLE
Different hierarchies should be independent.

### ISSUE THREAD

**Issue by ojx-fat** [SkepticMystic/breadcrumbs#403]
I create two hierarchies to define two types of relationship, such as Generalization (↑ = Superclass, ↓ = Subclass, ↔ = Same class) and Composition (↑ = Is part of, ↓ = Consists of, ↔ = Other parts).

When I define that A's subclass is B & C, and A consists of D & E, in B's Matric view I should see that B's same class = C, and B 's other parts = empty. 

But the situation is, B's same class = C & D & E, and B's other parts = D & E, which is semantically wrong.  

I think if different hierarchies are independent, the problem will be solved. 

P.S. In “Settings / Relationships”, I only turn on "Same Parent is Siblings".

**Comment by SkepticMystic** [comment]
Resolved in the rebuild.
Please read here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
