### ISSUE TITLE
FR: Sortable Tree View

### ISSUE THREAD

**Issue by vizance** [SkepticMystic/breadcrumbs#407]
## Problem
I find the BC-index can only be displayed with desc order now, see below picture
![CleanShot 2022-06-09 at 10 24 23@2x](https://user-images.githubusercontent.com/29624657/172750985-35feb073-85ec-4634-8e7f-22f3660dd073.png)

**Describe the solution you'd like**
add change sort order button (asc/desc)

**Describe alternatives you've considered**
I use "Copy a local index to clipboard" to copy and paste to a new note, and use "Sort & Permute lines" Plugin to sort 

**Additional context**
Since I use Luhamnn's ID to name my note, this feature will be useful when I want to organize these notes.

**Comment by SkepticMystic** [comment]
Complete in the latest version :)
It's currently only available in te V4 beta, see the link at start of the README for more info
