### ISSUE TITLE
Bug: fail to index note with  '-' in title

### ISSUE THREAD

**Issue by Steven-AA** [SkepticMystic/breadcrumbs#409]
**Describe the bug**

![sp20220613_140535_117](https://user-images.githubusercontent.com/22387129/173290213-fb55f9d3-cfe6-487c-8dc2-7c332c7cd58c.png)

![sp20220613_141632_351](https://user-images.githubusercontent.com/22387129/173291337-d19d477e-bb42-42dd-9bcb-3646c9a58506.png)

**To Reproduce**

```
---
prev: [[[2022-05]],[[2022 - 05]],[[2022_05]]]
---
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 3.3.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SkepticMystic** [comment]
This seems to be an issue with Dataview.
It is parsing `[[2022-05]]` as a date (which is correct). However, it doesn't store the original value anywhere, so there is no way for me to accurately recreate the date string you have. (`[[2022-05-01]]` gives the exact same date, for example).
I have raised this issue on the DV repo. But until then, I cannot fix this

**Comment by SkepticMystic** [comment]
See this issue for reference: https://github.com/SkepticMystic/breadcrumbs/issues/190
Two solutions are:
1. Put a `.md` at the end of the note name
2. Put the date link in a DV field (instead of a YAML field)

Gonna close this one out
