### ISSUE TITLE
Bug: Matrix view vanishes when focus on sidebar pane [Obsidian v0.15+]

### ISSUE THREAD

**Issue by kometenstaub** [SkepticMystic/breadcrumbs#410]
**Describe the bug**

When the Matrix View is in focus in the sidebar, its contents vanish.

**To Reproduce**
1. Update Obsidian to 0.15+
2. Click on the matrix view in the sidebar
3. Its contents vanish, but the pane itself stays.

**Expected behavior**

The contents should stay the same.

**Screenshots**

![image](https://user-images.githubusercontent.com/83140328/173956213-a25eeaa9-ca55-4078-ab7c-392963286ee9.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: the latest

**Additional context**

With the newest insider releases (v0.15+), sidebar panes can have focus, which is maybe where the issue is.

**Comment by I-Pch** [comment]
Same problem with `Obsidian v.0.15.1` on `MacOS` 😔 ...

Each time I move from a note to another, I need to refresh the index to display the breadcrumbs in the note and a second time in the side pane.

**Comment by I-Pch** [comment]
A small add-on 😊 : I've found this `Error` in the Dev' Tool 😊 

<img width="447" alt="BC-Dev Tool" src="https://user-images.githubusercontent.com/77828085/174067335-d78bbf58-6991-4ad9-baeb-6dce41a62931.png">

Not sure if this is related or not (as I'm not a dev' 😅 ) but I'm still leaving it here, just in case 😊

**Comment by kometenstaub** [comment]
See #411
