### ISSUE TITLE
[Feat]: keyboard shortcut to cycle through notes on "same" level of the hierarchy

### ISSUE THREAD

**Issue by cesar-programs** [SkepticMystic/breadcrumbs#414]
**Is your feature request related to a problem? Please describe.**

It's great to use keyboard shortcuts to traverse up, down, and to the next or previous note in the hierarchy; unfortunately, when we have notes that are marked "same," we do not have a keyboard shortcut.

**Describe the solution you'd like**

Adding the ability to cycle through notes on the same level of the hierarchy would solve the friction point.

Thank you.

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue.
I think one reason this isn't implemented, for `same` notes, specifically, is that the order isn't deterministic.
By definition, the `same` relation isn't directed, so how to tell which is the "next" one?

**Comment by SkepticMystic** [comment]
This has been implemented in V4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
