### ISSUE TITLE
FR: Allowing the user to define inherited relationships

### ISSUE THREAD

**Issue by Salamander230** [SkepticMystic/breadcrumbs#417]
Sometimes I have notes that have certain relationships that I would like to be inherited by their related notes.

For example, if the note `[[Vertebrates]]` has the relationship `has_property:: [[Backbone]]`, I want all the future generations of children of the note `[[Vertebrates]]` to implicitly inherit the `has_property:: [[Backbone]]` relationship.

### How this would look like:
![image](https://user-images.githubusercontent.com/87550781/177862407-0583b42e-92df-4c3c-a79f-0f17e56b28e9.png)

I'm not sure if there's an alternative way of accomplishing this. If not, I would really appreciate adding a feature like this in the future. And as always, thanks for your continued work on this awesome plugin.

**Comment by jayleverett** [comment]
+1 on this feature

**Comment by SkepticMystic** [comment]
Making a reference to #259 for future

**Comment by SkepticMystic** [comment]
I've added a powerful new feature in the latest release, customisable implied relations!
Here's more info about the feature: https://github.com/SkepticMystic/breadcrumbs?tab=readme-ov-file#transitive-implied-relations
And here's more info about the V4 rewrite in general: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md

I'm not fully sure if what you're requesting is possible, but please give it a try and let me know
