### ISSUE TITLE
Bug: Trail View at top of note does not refresh

### ISSUE THREAD

**Issue by Brettelectric** [SkepticMystic/breadcrumbs#422]
**Describe the bug**
'Trail view' at top of note won't display the immediate parent, only the parents above that.
Refreshing alone won't fix it.
To fix it, I need to refresh, then navigate to another note, then back to the original note.

**To Reproduce**
1. In plugin settings, turn on 'trail view at top of note'.
2. I'm using inline dataview, like so: (down:: [[Note]])
3. Open a note that is 2 or 3 levels 'down' in the hierarchy
4. In that note, type a wikilink for a new 'down' note, like so:  down:: [[New Note]]
5. Click the link to create the note. 
6. The trail view at the top of the new note does not show the immediate parent note, only the notes before it. For example, if my hierarchy is Home -> Resources -> World -> New Note, I would expect the trail at the top of the 'New Note' to read: Home -> Resources -> World. But instead it reads: Home -> Resources. 'World' is missing!

**Expected behavior**
In the past, if the trail view at the top of my note was not showing, or showing incorrectly (often the case with a new note), I could hit the 'Refresh Index' button and then the correct trail would be shown. 
But now I need to refresh, then navigate to another note, then back to the original note. 

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 3.4.1

**Additional context**

**Comment by SkepticMystic** [comment]
Hey @Brettelectric, thanks for the issue.
Please consider trying V4, more info here: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md.
Will close this out for now
