### ISSUE TITLE
FR: Using symbols/characters and/or emoji for heirarchy names

### ISSUE THREAD

**Issue by 64bakerst** [SkepticMystic/breadcrumbs#424]
**Is your feature request related to a problem? Please describe.**
No problem - but would like cleaner hierarchy indicators, than words - like ↓ or ↑ symbols or ⤵ emoji for names. Right now neither emoji nor symbol works.

**Describe the solution you'd like**
Example:
↓:: [[child page]]

or 
⤵:: [[child page]]

**Comment by SkepticMystic** [comment]
Hey :)
This issue has been raised before.
It's actually a limitation of Dataview not parsing emoji or symbols are valid keys:

![image](https://user-images.githubusercontent.com/70717676/180611588-ad6d3925-98d0-4fbd-816e-b07c6498a358.png)

Not much I can do here, but I recommend raising it on their repo

**Comment by szfkamil** [comment]
Experienced the same issues and found this issue here. Hope dataview fixes that!
