### ISSUE TITLE
[FR] Alphabetically Sort when Copying Index to Clipboard

### ISSUE THREAD

**Issue by 64bakerst** [SkepticMystic/breadcrumbs#425]
**Is your feature request related to a problem? Please describe.**
When copying the (Global or Local) index, currently it's out of order - or some arbitrary order, maybe by creation date/time? 

**Describe the solution you'd like**
Would like to post the index in an alphabetical order

**Comment by zhao414** [comment]
I think currently the plugin directly generate the output text, so there is no reordering. 

I think the potential solution maybe:
when generating the output, the hierarchical output can be stored in a hierarchical list and after the generation of this list, some reorder can be made on each level of this list. And at last, the output text is generated with a walk through of this re-ordered list.

**Comment by SkepticMystic** [comment]
This is implemented in V4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
Now when you run the Create List Index command, you can choose a sort order
