### ISSUE TITLE
Bug: Date notes not working with non-standard Luxon Format

### ISSUE THREAD

**Issue by autolisis** [SkepticMystic/breadcrumbs#426]
**Describe the bug**
Date Notes - Automatic linking to daily notes not working. I follow a slightly non standard naming convention for my daily notes, similar to `2022.07.29.Fri`, so I have the day as well. According to the reference I would expect this to correspond to the format `yyyy.MM.dd.EEE`. However this does not seem to work and I cannot see the next and previous notes in the breadcrumbs trail view or the matrix view.

I have the basic hierarchy set up as (up) (other) (down) (next) (previous)

**To Reproduce**
1. Create a few sequential notes in the format `yyyy.MM.dd.EEE`.
2. Enter `yyyy.MM.dd.EEE` in the option Alternative Hierarchies > Date Notes > Daily Note format.
3. Refresh obsidian, breadcrumbs, restart, whatever

**Expected behavior**
Expecting the hierarchy to show the next and previous notes corresponding to yesterday and tomorrow.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Monterey

**Additional context**
Set Debug logging to TRACE and couldn't see any obvious errors in the console either :(

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue.
I'm currently rebuilding the plugin from scratch, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
This is fixed in the v4 beta. So please consider upgrading to that (after reading the link shared)

**Comment by autolisis** [comment]
Wow that seems like a great update, and a lot of work to rewrite from scratch and I admire that! 

I will check this once I get the time and get back to you.

Thanks for your work on this plugin!
