### ISSUE TITLE
Filter siblings which have a different relation to the parent

### ISSUE THREAD

**Issue by HEmile** [SkepticMystic/breadcrumbs#43]
Siblings are notes with the same parents. However, if the current note is related to the parent through link type A and another through link type B, I would not expect those to be siblings. Is it possible to filter implied siblings to only show those with the same type of relation?

**Comment by SkepticMystic** [comment]
This should be implemented in 0.10.25. There is now a setting under "List/Matrix View" to turn this feature on/off. 
I'm gonna close out the issue, but let me know if there is a bug
