### ISSUE TITLE
Bug: some options are not accessible on mobile

### ISSUE THREAD

**Issue by nathonius** [SkepticMystic/breadcrumbs#434]
**Describe the bug**
Any settings that only show their label on hover may not accessible on mobile. 

**To Reproduce**
1. Go to plugin settings
2. Click on view any set of toggles (like those to show or hide parts of the trail view)
3. See no labels

![Screenshot_20220828-104343_Obsidian.jpg](https://user-images.githubusercontent.com/4851889/187079985-5fdc9a68-8c79-43e7-8554-78f5c2a9954a.jpg)

**Expected behavior**
Should be able to tell what the toggles do.

**Smartphone:**
 - Device: Samsung Galaxy S21 FE
 - OS: Android 12

**Comment by SkepticMystic** [comment]
Thanks @OfficerHalf, I've added some description text to the setting

**Comment by SkepticMystic** [comment]
Also, in v4, all toggles are labeled without having to hover
