### ISSUE TITLE
Bug: Trail/Grid views use wrong width in Live Preview view in Obsidian 0.16.x

### ISSUE THREAD

**Issue by mkasu** [SkepticMystic/breadcrumbs#437]
**Describe the bug**
In the recently updated 3.6.1, the Trail/Grid views now work correctly in Live Preview in Obsidian 0.16.x. 
However, they do not render in full width, making them very hard to see, especially close to the root note.

**To Reproduce**
1. Have trail/grid views activated
2. Go to live preview view
3. Display breadcrumbs close to root note (so path is short)

**Expected behavior**
The width should be wider, similar to how it renders in the Editing view.

**Screenshots**

Live Preview (Bugged width)
<img width="838" alt="189048332-81390448-21d0-4401-b277-1d3d7508f15a" src="https://user-images.githubusercontent.com/798036/189085226-8e640c11-cfa3-4938-a110-e7c07606f25b.png">

Editing view (Width as expected)
<img width="748" alt="189048405-5c8919f8-3562-4e5d-969a-f17d599fadcb" src="https://user-images.githubusercontent.com/798036/189085313-08a6f750-b210-4865-b459-30e4d01a4dfb.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 3.6.1 / Obsidian 0.16.2

**Additional context**

Rel. #435

**Comment by I-Pch** [comment]
Same here 😓 ...

I got this in `Live Preview`/`Source mode` 😔 ...

<img width="741" alt="BC - readable length - Live Preview" src="https://user-images.githubusercontent.com/77828085/189291430-786b08d2-f9f4-40ae-9ee4-4d3df8d76a44.png">

But this in `Reading` 😊 ...

<img width="741" alt="BC - Readable length - Reading" src="https://user-images.githubusercontent.com/77828085/189291615-b6d24cac-73bd-4ef9-b4b9-9a903cd5d9dd.png">

... on a : 

- MBP macOS `Big Sur 11.6.8`
- Obsidian `0.16.2` (Default Dark Theme)
- BC  `3.6.1`

**Comment by mkasu** [comment]
A hack until it is fixed; create a css snippet with
```css
.BC-trail {
	width: 100%;
}
```

**Comment by I-Pch** [comment]
> A hack until it is fixed; create a css snippet with
> 
> ```css
> .BC-trail {
> 	width: 100%;
> }
> ```

Thank you @mkasu 😁 ! This will perfectly do while waiting for a fix 👍 !

**Comment by SkepticMystic** [comment]
Thanks @mkasu, I've added this fix :)
