### ISSUE TITLE
Some visual bugs have appeared with BC 3.6.2 + Obsidian 0.16.2

### ISSUE THREAD

**Issue by I-Pch** [SkepticMystic/breadcrumbs#439]
### Describe the bug
This is mostly what only seems to be some visual bugs, so I think screenshots would be more helpful than my "not really awake" English 😅 ...

But in a nutshell, since the last update (from `BC 3.6.1` to `BC 3.6.2`), if the `Trail/Grid/Juggl view` seems to respect the readable length, its content is kind of stacked to the left of the note 😔 ... (as opposed to having a nice table displaying the BC)

The `Matrix view` is also now weird looking 😅 : If it was returning a normally condensed list of notes, now there seem to be unwanted spaces (which makes it somewhat long and a bit difficult to read)

In the `Down View`, the `freeze/unfreeze` appears as a giant icon and same goes for the `info` in the `Duck view`

There's also in `BC Settings`, icons missing in `Hierarchies` > `Add new Hierarchy`, `Reset all hierarchies`, `Show Hierarchies`

I didn't check every setting though, so there might be other issues there 😊 

Generally speaking, regarding all this visual bugs, it seems like where BC was showing stuff within a table, the table now appear to be generally missing 😇 .  

### To Reproduce
1. Open the Sandbox Vault of Obsidian
2. Install `Breadcrumbs 3.6.2` 
3. Open any note in the vault and add some default hierarchy (up, next, prev, down) info in the YAML of the note
4. Refresh BC Index
5. See the results 😔 

### Expected behavior
I loved the previous display of BC in my notes 😁 ... Could we get that back ? 🥺 

#### 1 - Trail/Grid/Juggl in a note (Live Preview) 
There doesn't seem to be a grid anymore 😔 

<img width="1440" alt="BC 3 6 2 - LP" src="https://user-images.githubusercontent.com/77828085/190625363-73d2087e-955f-4d3c-8a2d-84a710e6f36e.png">

#### 2 - Trail/Grid/Juggl in a note (Reading)
Same, there doesn't seem to be a grid anymore 😔 

<img width="1440" alt="BC 3 6 2 - Reading" src="https://user-images.githubusercontent.com/77828085/190625390-6b0e0024-5853-4da7-bdb6-b699fef161d0.png">

#### 3 - Matrix view
I think the results were rendered within a table/grid 😇 ... Well, this view surely wasn't looking like this 😇     

<img width="1440" alt="BC 3 6 2 - Matrix" src="https://user-images.githubusercontent.com/77828085/190625404-b47ea946-1330-4a46-a9b5-c6f00500e694.png">

#### 4 - Down view
Giant `Freeze/Unfreeze` icon (I don't know if the rest of the menu is looking as it should though as I rarely use it and simply don't remember how it was looking before)

<img width="1440" alt="BC 3 6 2 - Down" src="https://user-images.githubusercontent.com/77828085/190625730-744a29e1-938c-46a2-9e48-f831eda7e956.png">

#### 5 - Duck view
Giant `Info` icon (I don't know if the rest of the menu is looking as it should as I rarely use it and simply don't remember how it was looking before)

<img width="1440" alt="BC 3 6 2 - Duck" src="https://user-images.githubusercontent.com/77828085/190625748-757c0945-c8bc-4e74-befc-a78db649f467.png">

#### 6 - Missing Icons in BC Settings ?
<img width="1102" alt="BC 3 6 2 - Missing Icons" src="https://user-images.githubusercontent.com/77828085/190625763-c96933c0-3a64-44ec-b2fe-215651f45338.png">

### Desktop:
 - `MacOS Big Sur 11.7`
 - `Obsidian 0.16.2`
 - `Breadcrumbs 3.6.2`

### Additional context
I've seen this first in one of my vault this morning (Default Obsidian Theme), but could fully reproduce all this in the Sandbox/Help Vault with only BC installed and the only setting I modified after installing BC was to toggle `ON` the `Show Breadcrumbs in Edit/Live-Preview Mode` 
  
I'm so so so sorry this is happening 😔 ... But I thank you very much for this awesome plugin 🙌 !
I'll patiently wait for a fix 😊 !

**Comment by ample-samples** [comment]
These visual bugs are also happening on Arch Linux 5.19.8

**Comment by SkepticMystic** [comment]
Thank you for such a descriptive bug report!
Can you test out the latest version and let me know?

**Comment by I-Pch** [comment]
Hi @SkepticMystic 😁 !

After a quick test of `BC 3.6.3` (in my vault and the sandbox one), I can tell you that everything seems to be fixed from my side of the screen 🎉 🙌  😁 !!!

(Screenshot from the Sandbox Vault)

<img width="763" alt="BC - Fixed!" src="https://user-images.githubusercontent.com/77828085/191476346-69f9e8d7-2b19-458e-99f2-bcfc16db41a8.png">

Thank you so so so very much 🙌 😁 !!!
