### ISSUE TITLE
Bug: Tree View dir SAME does not display siblings

### ISSUE THREAD

**Issue by doctortalos** [SkepticMystic/breadcrumbs#441]
**Describe the bug**
When using tree view, and the value of dir: is set to same, the tree view does not display any expected notes (siblings). The sibling notes are clearly visible in matrix view. I have tried adding the notes as direct siblings (i.e. same:: xxx) and this does not work either. 

**To Reproduce**
1. create a note with siblings (e.g. assign up:: XXX to two notes)
2. create a tree note code block consisting of at least "type: tree" & "dir: same"
3. refresh breadcrumbs index
4. witness me

**Expected behavior**
Tree view to display siblings. Other directions (up, down) work as expected.

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by SkepticMystic** [comment]
After some testing, I consider this resolved in v4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
Please consider upgrading to the beta after reading the link above, and let me if it works for you
