### ISSUE TITLE
Bug: trail view occupies the area on the left side of the editor

### ISSUE THREAD

**Issue by mikonos** [SkepticMystic/breadcrumbs#442]
obsidian version：0.15.9
breadcrumbs version：3.6.3

when i update to the latest version，
i found the trail view occupies the area on the left side of the editor

i'm not sure if this is a bug...

![image](https://user-images.githubusercontent.com/3193323/193638611-9f019d81-a726-4ccf-a36b-a559eb1c8a52.png)

**Comment by SkepticMystic** [comment]
Is this resolved on >= Obsidian 1.0.0?

**Comment by SkepticMystic** [comment]
I believe this is resolved now
