### ISSUE TITLE
[Feature Request] Matrix view representation in a modal window

### ISSUE THREAD

**Issue by Glint-Eye** [SkepticMystic/breadcrumbs#443]
It would be great if there could be a modal window, that is an exact copy of the matrix view. Maybe with a few standard shortcuts to open the link in same or split pane, new tab, new window. that would be siiiick :-P

Cheers. Thx for the great plugin :)

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue.
Please explain why you'd find this useful. The modal would just cover the screen and show the same info that the Matrix view already does

**Comment by SkepticMystic** [comment]
I don't think I'm going to implement this. I appreciate the idea, thanks
