### ISSUE TITLE
Feature Request: cmd+click should open in new tab, not new pane (Obs. 0.16)

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#444]
To be consistent with the rest of the changes introduced in 0.16, cmd+click should open in a new tab and not in a new pane 🙂

**Comment by SkepticMystic** [comment]
Fixed in the latest v4 release :) See here for more info about the beta: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
