### ISSUE TITLE
Bug: Breadcrumbs matrix is not loaded upon Obsidian startup

### ISSUE THREAD

**Issue by egauthier** [SkepticMystic/breadcrumbs#445]
**Describe the bug**
Breadcrumbs matrix is not loaded upon Obsidian startup.

**To Reproduce**
1. Close Obsidian with a Note open in the main pane, and the BC matrix on the right.
2. Quit Obsidian
3. Start Obsidian
4. The Breadcrumbs matrix is not populated (as it was when you quit Obsidian) until the next Save, even if you have "Refresh Index on Note Change" enabled in the options and a change is made to the note.

**Expected behavior**
I would expect that on startup the matrix is populated as it was on close.

**Desktop (please complete the following information):**
 - Mac OS Monterey 12.5.1
 - Obsidian v0.15.9
 - Breadcrumbs 3.6.3

**Comment by SkepticMystic** [comment]
Does this still happen? If so, do you get anymore errors in the console?

**Comment by egauthier** [comment]
Yes, still happening.  It's not a big deal, a quick manual save refreshes it.  

Obsidian: v1.5.3
Breadcrumbs: 3.6.11
MacOs

**Comment by SkepticMystic** [comment]
@egauthier if you're open to it, please try the beta v4. More info here: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
Most features have been reimplemented, with a couple of changes to make note of befor moving over

**Comment by SkepticMystic** [comment]
Confirmed to be fixed in v4, gonna close this out
