### ISSUE TITLE
Bug: breadcrum does not refresh on a different window

### ISSUE THREAD

**Issue by royhj** [SkepticMystic/breadcrumbs#446]
**Describe the bug**
Assume there is a note being edited on window 1 and a linked pane to the same note on window 2.

If the breadcrumb is edited and refreshed on window 1, then the linked pane (on window 2) will not refresh (even when going out and back of the note in window 1 - automatically on the linked pane as well, since it is linked).

Navigating away and back on window 2 updates breadcrumb properly.

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue! Even though you posted first, I'm gonna close in favour of #511 as it has the more recent context of V4 (see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md)
