### ISSUE TITLE
Trail View in Title Header

### ISSUE THREAD

**Issue by CovetingEpiphany2152** [SkepticMystic/breadcrumbs#447]
**Is your feature request related to a problem? Please describe.**
Problem: Trail view is now only viewable at the top of the file, instead of being viewable at all times.

**Describe the solution you'd like**
Add option to move trial view into Obsidian 1.0's title container, which now contains the directory path breadcrumbs.
![image](https://user-images.githubusercontent.com/7296340/196044723-edd48b94-aa30-47ae-8df0-77e6345c3303.png)
Ideally, I would imagine that we should be able to select one of the folllowing:
- replace directory path breadcrumb with breadcrumb plugin trail view
- add breadcrumb plugin trail view **below** directory path breadcrumbs
- add breadcrumb plugin trail view **above** directory path breadcrumbs

Additionally, on top of the options above, user should be able to decide if they want to keep the top-of-file trail view breadcrumbs
- display top-of-file trail view

**Describe alternatives you've considered**
Another option that came to mind is to display trail view at the status bar. But I'd rather have my status bar stay simple.

**Additional context**
Having to scroll to the top of the file to see the trail makes trail view less useful. There are times when you are reading the file and want to refer to the trail.

Thanks!

**Comment by SkepticMystic** [comment]
Thanks for the issue.
I've recently rewritten Breadcrumbs, and it's available in the v4 beta via the BRAT plugin.
The Trail View is now in a different position in the DOM, and there's a setting to make it sticky on scroll. I feel the combination of these two changes is enough to close out this issue
