### ISSUE TITLE
Give the Matrix View a more native look

### ISSUE THREAD

**Issue by Karmac** [SkepticMystic/breadcrumbs#448]
Hello,

First of all I'd want to thank you for creating this plugin. It is awesome so far, and makes navigation between large vaults much easier.

**Is your feature request related to a problem? Please describe.**
Well, I don't know if it's been addressed before, but I feel BC not to be well integrated into Obsidian design wise.

This time I'm focusing on the Matrix View. It's design is completely different from other sidebars: accent color links draw your attention out of the main window to the sidebar and matrix borders fill up too much space, which in turn makes it difficult to read links in smaller screens (specially if filenames are long, as when using Zettelkasten), to mention some issues.

**Describe the solution you'd like**
I think the Matrix View could be styled using the same approach as the backlink or outgoing link panels. This way it would be fully integrated in Obsidian.

Some benefits of this approach:
- More readable.
- Less attention drawing.
- Themes that style backlinks also style the matrix view.
- Different hierarchies can be collapsed, making it easier to navigate.

**Describe alternatives you've considered**
I have made a quick sketch in Obsidians inspector, so you can see what I mean and what changes should be made. The HTML structure is mostly the same, so it's only changing classes.

This is what I feel it should be like (just a quick sketch):
![imagen](https://user-images.githubusercontent.com/638179/196375462-c39902ce-65e3-4d4f-aadc-6c02ef3a2271.png)

![imagen](https://user-images.githubusercontent.com/638179/196376027-41b8a433-5d16-4f02-8a03-781f75c2a617.png)

Instead of this:

![imagen](https://user-images.githubusercontent.com/638179/196376244-fc9f9bb6-47ce-4796-bfbb-712fd698513c.png)

![imagen](https://user-images.githubusercontent.com/638179/196376432-24a08e9e-dba6-4e5a-bc40-da13169c574f.png)

**Final words**
I'd be glad to help however you need if you consider making this change. Thank you so much and excuse my English, it's not at its best today haha

EDIT: typo

**Comment by SkepticMystic** [comment]
Hey @Karmac, thanks for the issue, I appreciate your effort.
I've recently rebuilt Breadcrumbs from scratch, and it's currently available via beta release under V4. See here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
The Matrix view is much simpler now, and uses fewer custom styles, and more Obsidian styles. Check it out once you've read the link above, and let me know your thoughts. It could certainly still use some work, so I'm open to suggestions

**Comment by SkepticMystic** [comment]
I'm gonna consider this closed as of V4. I've recently made alot of changes to style the Matrix view more natively
