### ISSUE TITLE
[Bug?] Links in the pane are shown with aliases (Juggl links)

### ISSUE THREAD

**Issue by HEmile** [SkepticMystic/breadcrumbs#45]
When using Juggl links (haven't tested others), the aliases of the links are also shown in the pane:

![image](https://user-images.githubusercontent.com/1289165/124469986-50312700-dd9b-11eb-9247-d0617aa11075.png)

**Comment by SkepticMystic** [comment]
Ahh right, I forgot to run the regex replace for Juggl links. I'll implement that in the next release

**Comment by SkepticMystic** [comment]
@HEmile should be fixed in 0.6.11
Will you let me know if it's working for you when you get a chance

**Comment by HEmile** [comment]
Yes, that works, thanks!
