### ISSUE TITLE
Bug: Gutters misaligned in Obsidian v1.0 when Trails are enabled

### ISSUE THREAD

**Issue by pdelre** [SkepticMystic/breadcrumbs#450]
**Describe the bug**
The gutters are misaligned in Obsidian v1.0 when Trails are enabled.

**To Reproduce**
- Enable line numbers
- Enable Breadcrumb's Trail view
- Make sure note has parent notes
- See line numbers do not align with text

**Expected behavior**
Line numbers should align with text

**Screenshots**
_Trail view enabled_
![image](https://user-images.githubusercontent.com/1379248/197036033-ec4e9180-12d4-48ca-b374-45ac5d500cfe.png)

_Trail view disabled_
![image](https://user-images.githubusercontent.com/1379248/197036082-9372bd71-5698-4a24-99fe-6f9f5a81b8e7.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.6

**Additional context**
Likely tied to this code: https://github.com/SkepticMystic/breadcrumbs/blob/master/src/Views/TrailView.ts#L222-L229

![image](https://user-images.githubusercontent.com/1379248/197036949-b3b7ec95-c0ed-4178-ab36-1142ea3add14.png)

**Comment by JaySpencer1234** [comment]
I concur.

**Comment by AtlcatlQ** [comment]
In Obsidian 1.1 that bug still happens

**Comment by pdelre** [comment]
YMMV, but my workaround was to modify `.obsidian/plugins/breadcrumbs/main.js`'s lines linked in the original post.

```diff
       const cmGutter = view.querySelector("div.cm-gutters");
       if (cmGutter) {
         requestAnimationFrame(() => {
-          const gutterHeight = trailDiv.getBoundingClientRect().height;
+          const gutterHeight = 0;
           cmGutter.style.paddingTop = `${gutterHeight + 4}px`;
         });
       }
```

**Comment by SkepticMystic** [comment]
Fixed in v4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md.
Please consider upgrading to the beta.
Gonna close this out as complete
