### ISSUE TITLE
Bug: Typo in options

### ISSUE THREAD

**Issue by AtlcatlQ** [SkepticMystic/breadcrumbs#451]
**Describe the bug**
I just wanted to report a typo I noticed in the options menu

It shows: `Enable Apahebtical Sorting`, It should says `Enable Alphabetical Sorting`

**Screenshots**
![image](https://user-images.githubusercontent.com/87624226/197357270-4285e29c-313b-4c44-8f06-8b1ca4214157.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Plugin Version: 3.6.3
 
 PS: I Love this plugin

**Comment by SkepticMystic** [comment]
I don't see the type you're referring to...

**Comment by pdelre** [comment]
I believe the Issue has a typo. [This line](https://github.com/SkepticMystic/breadcrumbs/blob/master/src/Settings/MatrixViewSettings.ts#L81) uses `Alpahebtical` instead of `Alphabetical`

**Comment by SkepticMystic** [comment]
Haha thank you @pdelre, should be resolved now
