### ISSUE TITLE
[FR] Visualize hierarchy of files in file-tree pane

### ISSUE THREAD

**Issue by andrey-jef** [SkepticMystic/breadcrumbs#452]
**Is your feature request related to a problem? Please describe.**
Currently the Matrix/List view is not intuitive to use. While the hierarchy of files could be possibly easier to navigate using a file-tree pane

**Describe the solution you'd like**
For example: given a `me.md` file with the following frontmatter:
```txt
---
parent: [[dad]]
sibling: [[sister Lara]]
child: [[child Andre]]
---
```
Then the file-tree pane could inherit this metadata and visualize the directory/file tree as follows.
```txt
vault/
├─ dad
│  ├─ me
│  │  ├─ child Andre
│  ├─ sister Lara
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SkepticMystic** [comment]
I think the Tree view does what you're describing. Please try that and reopen the issue if not
