### ISSUE TITLE
Bug: Changing workspace fails to open any notes with a breadcrumbs block

### ISSUE THREAD

**Issue by justjosh** [SkepticMystic/breadcrumbs#453]
**Describe the bug**
Hi, there seems to be an issue with notes that contain a breadcrumbs block where the note will not open when loading up a workspace.
This doesn't happen when starting up Obsidian, or when opening the note directly, but only when loading up a workspace with such a note.

**To Reproduce**
1. Save a new workspace that contains a note with a breadcrumbs block, e.g.
```breadcrumbs
type: tree
dir: down
depth: -3
from: #🗺️MOC 
```
2. Load the new workspace
4. The note with the breadcrumbs block will not open, and the following error is shown:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/3614699/197992656-c469b046-e00a-42fb-bd8a-4bbfe2b6e976.png">

**Expected behavior**
Workspace should load up all it's notes, regardless of whether it contains a breadcrumbs block/tree.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version v1.0.0

**Additional context**
Have only recently started using breadcrumbs in this way, so unsure if it relates to the latest Obsidian update or not.

**Comment by SkepticMystic** [comment]
Thanks for the issue @justjosh.
I've recently rewritten Breadcrumbs from scratch, and it's available in beta via the BRAT plugin.
Please consider upgrading and checking if this issue is resolved there. Alot of problems are resolved now

**Comment by justjosh** [comment]
Can confirm V4 has resolved this issue, thanks!
