### ISSUE TITLE
Bug: glitchy matrix at the top of the note

### ISSUE THREAD

**Issue by pawel-ilnicki** [SkepticMystic/breadcrumbs#455]
**Describe the bug**
Glitchy matrix view at the top of the note in **the Minimal theme**

**To Reproduce**
1. Enable Minimal theme
2. Enable matrix view at the top of the note

**Expected behavior**
Not glitchy

**Screenshots**
![image](https://user-images.githubusercontent.com/98173950/199696849-58b45496-73fd-490a-884c-5b494a389c52.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] of Obsidian 1.0.3, latest of Breadcrumbs

**Additional context**

**Comment by SkepticMystic** [comment]
I'm gonna consider this resolved by the changes in V4. I've rewritten Breadcrumbs from scratch, and the Trail View works differently now. See here for more info about V4: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
