### ISSUE TITLE
BC-link-note interferes with explicit dataview inlines

### ISSUE THREAD

**Issue by DeutscheGabanna** [SkepticMystic/breadcrumbs#457]
Try to create this note:
```
---
BC-link-note: down
---
> [!dataview breadcrumbs]
> up::[[root]]

Children of this MoC:
- [[one]]
- [[two]]
```

The `BC-link-note` takes **all** outgoing links and marks them as children, which leads to a strange and unwanted situation, where `root` is both parent and child of this note.

**Comment by SkepticMystic** [comment]
I get you. But that's what the feature does 🤷
Maybe you could use you `BC-dataview-note` to filter for only the links you want?
