### ISSUE TITLE
[FR] Add option to change the default hierarchy used in each Hierarchy notes

### ISSUE THREAD

**Issue by icytree** [SkepticMystic/breadcrumbs#461]
I currently use multiple hierarchies and I would love to be able to structure them using a different Hierarchy note for each them. The problem is that currently all Hierarchy notes are associated to a single (default or defined) hierarchy. Of course, their is the [option to override it on a line per line basis](https://breadcrumbs-wiki.onrender.com/docs/Alternative%20Hierarchies/Hierarchy%20Notes#specifying-different-up-fields) but it is not really ideal in the case I know that all the links in a specific Hierarchy note are intended for another hierarchy. So I was wondering if it would be possible to change the default hierarchy in each Hierarchy note perhaps in the frontmatter (ex. `BC-default-hierarchy`). 

Edit: I slightly modified my FR because after further experimentation, I figured out being able to override what ever current default hierarchy for a Hierarchy note on a line per line basis is pretty useful.

As a side note/question related, I was wondering if it would be possible (/still efficient computing wise) to indicate notes that are Hierarchy notes using frontmatter ?

**Comment by SkepticMystic** [comment]
Hey @icytree, thanks for the issue!
This has been implemented in v4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
In fact, now you can _only_ create Hierarchy notes using frontmatter (now called List notes). Use `BC-list-note-field: down`, for example.
Gonna close this out
