### ISSUE TITLE
[FR] Tree codeblock level sorting

### ISSUE THREAD

**Issue by michalzmuda** [SkepticMystic/breadcrumbs#462]
There is no option to sort **tree** [codeblock ](https://breadcrumbs-wiki.onrender.com/docs/Codeblocks) (based on level)

```

```breadcrumbs
title: false
type: tree
dir: down
```

```
I have added tree codeblock as my MOC index page and I would like to have option to sort the items. 
Implementation should add sort property:

```
  title: false
  type: tree
  dir: down
  sort: true
```
Note: we need level sorting (different sorting for each tree level)

**Comment by SkepticMystic** [comment]
I've resolved this issue in the rebuild.
Please read here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
You can use `sort: basename asc/desc` to achieve this
