### ISSUE TITLE
[FR] Show current file in trail view

### ISSUE THREAD

**Issue by AthreyaV** [SkepticMystic/breadcrumbs#465]
I am trying to use the trail view as essentially a file path header alternative. It's just a helpful visual aid for me to be able to see the current file at the end of the trail view in this case, as is standard in a file path. I have tried messing with the settings under trail view but couldn't get it to show, so I figure this isn't a feature currently available in the plugin.

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue.
I get what you mean. But don't you think the Obsidian file header above the trail view is enough? That shows the full file path

**Comment by SkepticMystic** [comment]
I'm gonna close this as not planned. I think the trail in the Obsidian file header is enough, and you can also enable the "Self is Sibling" implied relation to see the current note in the matrix view
