### ISSUE TITLE
Bug?: Breadcrumbs index occupies huge amount of RAM / Obsidan lags (and on mobile: crashes)

### ISSUE THREAD

**Issue by avirosso** [SkepticMystic/breadcrumbs#466]
If I 'activate' the breadcrumbs plugin on my Windows PC it builds the index, the CPU utilization goes up and the occupied RAM for Obsidian increases from 700 MB to 2400 MB and it stays at this level (that would be about 1700 MB only for the breadcrumbs index ...). Obsidian 'lags', but there are no breadcrumb-errors in the developer console.

(Additionally: If I 'activate' the breadcrumbs plugin on my android phone, obsidian mobile hangs/crashes after a while - so I can't use breadcrumbs in Obsidian any more).

I don't know why breadcrumb occupies such huge amount of RAM and slows down obsidian.

Any idea/help or advice?

Thanks in advance!

-----

Background information:

Breadcrumbs version: 3.6.4
Obsidian version: v1.0.3
Installer version: v1.0.3
Operating system: Windows 10 Pro 10.0.19045
Insider build toggle: off
Live preview: on
Community theme: Minimal
Plugins enabled: 66

I'm working (building hierarchies) only with "Tag Notes"
Notes in the Vault: 6215
Tags in the Vault: 8715 (mostly nested)

Tag Note Example:

```
---
tags:
  - Thema/Software/Obsidian
BC-tag-note: '#Thema/Software/Obsidian'
BC-tag-note-field: Down
BC-tag-note-exact: true
---
```

Configuration (data.json)

```
{
  "addDendronNotes": false,
  "addDateNotes": false,
  "aliasesInIndex": false,
  "alphaSortAsc": true,
  "altLinkFields": [],
  "CSVPaths": "",
  "createIndexIndent": "  ",
  "dateFormat": "YYYY-MM-DD",
  "dateNoteFormat": "yyyy-MM-dd",
  "dateNoteField": "next",
  "dataviewNoteField": "up",
  "dateNoteAddMonth": "",
  "dateNoteAddYear": "",
  "debugMode": "WARN",
  "dendronNoteDelimiter": ".",
  "dendronNoteField": "Up",
  "dvWaitTime": 5000,
  "enableAlphaSort": true,
  "enableRelationSuggestor": false,
  "fieldSuggestor": false,
  "filterImpliedSiblingsOfDifferentTypes": true,
  "jugglLayout": "hierarchy",
  "limitWriteBCCheckboxes": [
    "Up",
    "Down",
    "Next",
    "Prev"
  ],
  "CHECKBOX_STATES_OVERWRITTEN": true,
  "gridDefaultDepth": 25,
  "gridHeatmap": false,
  "heatmapColour": " #705dcf",
  "hierarchyNotes": [
    ""
  ],
  "hierarchyNoteIsParent": false,
  "HNUpField": "",
  "indexNotes": [
    "START"
  ],
  "namingSystemField": "",
  "namingSystemRegex": "",
  "namingSystemSplit": ".",
  "namingSystemEndsWithDelimiter": false,
  "refreshOnNoteChange": false,
  "useAllMetadata": false,
  "openMatrixOnLoad": true,
  "openDuckOnLoad": false,
  "openDownOnLoad": false,
  "parseJugglLinksWithoutJuggl": false,
  "showNameOrType": true,
  "showRelationType": false,
  "regexNoteField": "",
  "relSuggestorTrigger": "\\",
  "rlLeaf": false,
  "showAllPathsIfNoneToIndexNote": false,
  "showAllAliases": true,
  "showBCs": false,
  "showBCsInEditLPMode": false,
  "showRefreshNotice": true,
  "showImpliedRelations": true,
  "showTrail": true,
  "showGrid": false,
  "showJuggl": false,
  "showPrevNext": false,
  "sortByNameShowAlias": false,
  "squareDirectionsOrder": [
    0,
    2,
    1,
    3,
    4
  ],
  "limitTrailCheckboxes": [
    "Up"
  ],
  "limitJumpToFirstFields": [
    "Up",
    "Down",
    "Next",
    "Prev"
  ],
  "showAll": "All",
  "noPathMessage": "Kein Breadcrumb-Trail gefunden",
  "tagNoteField": "Down",
  "threadIntoNewPane": false,
  "threadingTemplate": "{{field}} of {{current}}",
  "threadingDirTemplates": {
    "up": "",
    "same": "",
    "down": "",
    "next": "",
    "prev": ""
  },
  "threadUnderCursor": false,
  "trailSeperator": ">",
  "treatCurrNodeAsImpliedSibling": true,
  "trimDendronNotes": false,
  "respectReadableLineLength": true,
  "userHiers": [
    {
      "up": [
        "Up"
      ],
      "same": [
        "Same"
      ],
      "down": [
        "Down"
      ],
      "next": [
        "Next"
      ],
      "prev": [
        "Prev"
      ]
    }
  ],
  "writeBCsInline": false,
  "showWriteAllBCsCmd": false,
  "visGraph": "Force Directed Graph",
  "visRelation": "Parent",
  "visClosed": "Real",
  "visAll": "All",
  "wikilinkIndex": true,
  "impliedRelations": {
    "siblingIdentity": false,
    "sameParentIsSibling": true,
    "siblingsSiblingIsSibling": false,
    "parentsSiblingsIsParents": false,
    "parentsParentsIsParent": false,
    "cousinsIsSibling": false
  },
  "refreshOnNoteSave": false,
  "showUpInJuggl": false,
  "defaultView": true,
  "downViewWrap": true,
  "dotsColour": "#000000",
  "gridDots": false,
  "openStatsOnLoad": false,
  "overflowMLView": false
}
```

**Comment by SkepticMystic** [comment]
Hey @avirosso. Thanks for all the info.
The slowdown is definitely because of how many notes are in your vault. 6000 is quite a large vault by any standard.
I don't see how this could be resolved without some major performance changes to Breadcrumbs

**Comment by avirosso** [comment]
Thanks for the quick response. I'm using Obsidian about a year and there will be an estimated annual growth of about 5000 notes, so unfortunately I can't use breadcrums plugin no longer ...

**Comment by phillipjohnston** [comment]
My 50,000 note vault laughs at the idea that 6000 is large by any standard. But I also don't experience this when I use Breadcrumbs. When I refresh the index, there is perhaps a 5 second lag.

**Comment by BricoleurSoul** [comment]
Mine is much closer to the 6k than the 50k at 14000 but no problem at all.
So my vault adds a hearty chuckle too😀

**Comment by avirosso** [comment]
@phillipjohnston and @BricoleurSoul: Thanks for your comments!

In my case, the problem/cause seems to be the enormous increase of occupied RAM: If I 'activate' the breadcrumbs plugin on my Win 10 PC the occupied RAM for Obsidian increases from 700 MB to 2400 MB (reproducible) and it stays at this level (that would be about 1700 MB only for the breadcrumbs index?). (Side note: This may probably the reason, why Obsidian mobile/android chrashes after activating breadcrumbs).

-> May I ask how much the occupied RAM increases in your case (after activating breadcrumbs)?

Thanks in advance!

**Comment by SkepticMystic** [comment]
Haha thanks for the responses Phillip and Bri :)
Fair enough, 6k isn't very many, it seems! Good to hear that your vaults don't slow down as much as avirosso's does..
@avirosso perhaps then it's because you mainly use tags notes? I haven't checked how that code works in a while, but it's possible there are some inefficiencies, or it's just an inherently costly operation

**Comment by avirosso** [comment]
@SkepticMystic: Thanks for your comment. Yes, I'm working only with tag-notes (see above for examples/configuration) and I guess, there must be a problem ('memory leak'?) in the index /indexing process. There are no errors in developer console, but it can't be 'normal' that indexing/index of tags consumes about 1700 MB RAM (and stays at this level even if the indexing process is finished) ...

**Comment by phillipjohnston** [comment]
> May I ask how much the occupied RAM increases in your case (after activating breadcrumbs)?

I go from ~970MB to ~1180MB.

**Comment by avirosso** [comment]
@phillipjohnston: Thanks for your effort! That increase of occupied RAM would be an average of 4kb relations-index per note (50,000 note vault).

In my case it would be an average of 283 kb relations-index per note (6,000 note vault, 1700 MB increase of occupied RAM) - sounds strange (and the RAM usage doesn't drop, stays at about 2400 MB until I close Obsdian ...)

**Comment by avirosso** [comment]
@KuiyueRO: Thanks for the advice - but I never turned on 'Ducks View' or 'Refresh Index on Note Change' (it's always off) ...

**Comment by dartungar** [comment]
Can confirm the same problem with a relatively small number of notes (~2000) in the vault.
RAM goes to ~1.5GB, and on app startup cache loads forever (~3-5 minutes). Turning off Breadcrumbs makes these problems go away. 
Shame, because I really like the plugin.

**Comment by SkepticMystic** [comment]
Hey everyone here.
I'm currently rebuilding the plugin from scratch. Please see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
It's very likely that this issue is resolved in the new version. Please consider upgrading (after reading the link shared above), and see if that fixes it. Any feedback would be really helpful

**Comment by SkepticMystic** [comment]
I've gotten some feedback that performance is much better in v4. Gonna close this issue out, but please reopen if you experience this problem again.
