### ISSUE TITLE
Bug: Empty breadcrumb matrix when browsing a note

### ISSUE THREAD

**Issue by pawel-ilnicki** [SkepticMystic/breadcrumbs#467]
**Describe the bug**
When I focus on the note window/tab by clicking on it, the matrix tab becomes empty.
I then have to click "Refresh" on the matrix tab to populate it again with connections.
I click away on the note again, to write something in it, and the matrix tab empties again.
...
ad infinitum

**Expected behavior**
Matrix should not be empty when I click away from the tab.

**Desktop (please complete the following information):**
 - OS: win10
 - Version 1.0.3

**Additional context**
I tried "Link with tab" feature after right-clicking on the matrix tab to link it specifically with the note. Does not help.

**Comment by SkepticMystic** [comment]
Does this still happen? Do you get any errors in the console when it does?

**Comment by SkepticMystic** [comment]
Please try out v4, more info here: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
Gonna close this out as complete in the latest version
