### ISSUE TITLE
Bug: "c4.add is not a function" using Dendron hierarchy

### ISSUE THREAD

**Issue by Gekokeitaro** [SkepticMystic/breadcrumbs#469]
**Describe the bug**
Hi,

I'm using Dendron naming for hierarchy organization and your plugin for hierarchy visualization, but since the last update the trail, breadcrumbs matrix and breadcrumbs down views doesn't work anymore.

I tried to reinstall the plugin several times with the same results, and in the debug console i'm having an error in "plugin:breadcrumbs:18837" that says: "TypeError: c4.add is not a function"

**To Reproduce**

1. Go to any note
1.1. Try reading view. No trails showing in the note.
1.2. Open breadcrumbs matrix, no data.
1.2.1. Refresh the breadcrumbs matrix, no data (also error "c4.add" on console)
1.3 Open breadcrumbs down, no data.
1.3.1. Refresh the breadcrumbs down, no data (also error "c4.add" on console)

**Expected behavior**
Open a note and be able to see the trail, matrix and down views.

**Screenshots**
![image](https://user-images.githubusercontent.com/6348952/206856354-aeb80d2c-219f-4001-b6a9-5e718bf6cc01.png)
![image](https://user-images.githubusercontent.com/6348952/206856384-6a960009-fb92-4a7b-aaa8-3cbf5768234e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
My notes are named like this: "ext.game.production.how.game-market-segmentation", where some prefixes exists only as a semantic element for categorizing, and not as a note.

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue.
I'm in the process of rebuilding Breadcrumbs from scratch. Please see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
As such, I likely won't fix any issues in the old (current v3) version. Please try upgrading after reading the link shared, and let me know if that fixes this

**Comment by SkepticMystic** [comment]
Gonna close this as working in v4. Please reopen if you get any new issues
