### ISSUE TITLE
Bug: 'Jump to Prev' command or hotkey resulted in 'No note was found in prev given the limited fields allowed'

### ISSUE THREAD

**Issue by zadorski** [SkepticMystic/breadcrumbs#475]
**Describe the bug**

An exception occurs when navigating using the "Jump to Prev" and "Jump to Next" options (either way, through the command palette, or via hotkeys)." The logic successfully locates and displays the necessary links in the matrix, but it refuses to jump to them, as if it is expecting explicit fields (as shown in the screenshot below).

**To Reproduce**

1. Ensure that daily notes are present in the same folder.
2. The notes do not explicitly specify previous/next relationships.
3. Initiate the "Jump to Next" function using the hotkey or command.
4. Observe the error message "No note was found in next given the limited fields allowed:"."

**Expected behavior**

The hotkey or command "Jump to Prev" has the same result as clicking on the corresponding link in the Breadcrumbs matrix. 

**Screenshots**

![image](https://user-images.githubusercontent.com/678169/216567431-02de7758-c260-4f54-ac83-24a2736ae6d2.png)

**Desktop (please complete the following information):**

 - Windows 11
 - Breadcrumbs 3.6.4
 - Obsidian 1.1.9

**Additional context**

- The "Prev/Next" links are automatically recognized in daily notes without the need for explicit inline tags. The matrix displays the links correctly and clicking on them functions as expected. However, 
- It does not seem to be a regression caused by other plugins. The issue seems to have arisen after the refactoring of daily notes (extracting bullet points into separate notes). Could this process have caused the breadcrumb index to become disrupted? Attempting to "Refresh Breadcrumbs Index" did not resolve the issue.

**Comment by SkepticMystic** [comment]
Hey @zadorski, please share your settings file (`.obisidian/plugins/breadcrumbs/data.json`)

**Comment by SkepticMystic** [comment]
After reimplimenting this feature in v4, I'm gonna consider this resolved as it works more smoothly now. See here for more info about the beta, and consider upgrading: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
