### ISSUE TITLE
Specify a hierarchy note as being a sequence of next (previous) notes

### ISSUE THREAD

**Issue by Sapagrino** [SkepticMystic/breadcrumbs#476]
**Describe the solution you'd like**
I'd like to add several "sequence" notes to my hierarchy notes folder where the default hierarchy is to treat each item in the list as the "next" item for the one before it, as another option to the default of treating all of them as "same".

Roman Numerals
[[I]]
[[II]]
[[III]]

Days of Week
[[Monday]]
[[Tuesday]]
[[Wednesday]]

Time Periods
[[Newborn]]
[[Infant]]
[[Toddler]]

In many cases, this would streamline previous/next coding even better than the recent addition of being able to force a prev / next relationship amongst a parent / child hierarchy.

Thank you for considering this and for your amazing work to date!

**Comment by SkepticMystic** [comment]
This is now possible! See this related issue for info on how to achieve it: #392
