### ISSUE TITLE
Bug: Trail/Grid/Juggl view overflow on small windows/screens

### ISSUE THREAD

**Issue by oqipoDev** [SkepticMystic/breadcrumbs#478]
**Describe the bug**
The Trail/Grid/Juggl view at the top of a note overflows to the right when the note space is thinner than 700px (readable length).

I've been developing a theme and this problem caught my attention because it's almost unfixable through CSS, as it's in the element style.

The problem seems to come from `/src/Views/Trailview.ts` at lines `197-203`, and maybe a quick fix would be to remove them (I suspect, at least).

**To Reproduce**
1. Install and use breadcrumbs in a vault
2. Open any note
3. Resize window/panels/dividers such that the note is thinner than 700px

**Expected behavior**
The Breadcrumbs view should always be the same width as the note inside, and not fixed.

**Screenshots**
| ![image](https://user-images.githubusercontent.com/100394455/218291870-ed05fb1e-d412-4a2c-a7ea-0236e93016b9.png) | ![image](https://user-images.githubusercontent.com/100394455/218291962-b15f3bcc-5515-46ed-b722-4a202c941adb.png) | ![image](https://user-images.githubusercontent.com/100394455/218291986-43182368-5c93-4bc8-b367-f2ed8d92b937.png) |
| --- | --- | --- |
| An example, Default theme, no CSS snippets | The problematic class and suspected property | Solved by disabling the _width_ property |

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version Obsidian 1.1.9, Breadcrumbs 3.6.4

**Comment by SkepticMystic** [comment]
Considered fixed in v4, see the top of the readme for more info
