### ISSUE TITLE
Feature request: Use more appropriate indicators for Trail/Grid/Juggl view

### ISSUE THREAD

**Issue by oqipoDev** [SkepticMystic/breadcrumbs#479]
**Is your feature request related to a problem? Please describe.**
I've seen two main problems with the use of some indicators, mostly in the in-note view.

**Describe the solution you'd like**
- For the trail view, `→` is used, but seems to me like that's a navigation glyph
  -  `›` or `>` are more commonly used to communicate hierarchical relationships (see Windows Explorer, Google Drive, etc.)
- In the next-prev view, putting `prev` and `next` is clunky, unappealing, and just all kinds of wrong in other languages, especially in long-ish titles
  - `←` and `→` seem more appropriate for this use

**Describe alternatives you've considered**
I've actually made a theme with these considerations in mind. Pictured in the section below.

**Additional context**
This is a side-by-side view of the modified CSS. Pay attention to the symbology. Don't mind the theming.

| ![image of original](https://user-images.githubusercontent.com/100394455/218293062-bbb2ba25-ebf6-47c8-abc8-923a3a7f4d8a.png) | ![image of suggested](https://user-images.githubusercontent.com/100394455/218292943-d8c73b7c-c240-4ed4-b45a-97c887b3ad80.png) |
| :--: | :--: |
| Original | Suggested symbology |

**Comment by SkepticMystic** [comment]
Hey, a couple of points:
1. I'm rebuilding the plugin from scratch, and don't intend to implement the Trail view. The Grid view shows the same info.
2. The `prev` and `next` fields can be called whatever you want, so you can change the hierarchy field as you see fit
