### ISSUE TITLE
Links in Breadcrumbs Matrix change the mouse cursor to text instead of pointer

### ISSUE THREAD

**Issue by dsent** [SkepticMystic/breadcrumbs#482]
Basically, this:

![image](https://user-images.githubusercontent.com/8774536/235316101-257002d0-c709-4e4a-ab44-ffa60e6e67d8.png)

**Comment by SkepticMystic** [comment]
Thanks!
Marking as resolved in v4. Please see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
