### ISSUE TITLE
Multiple issues related to cosmetics and hierarchy

### ISSUE THREAD

**Issue by qazero** [SkepticMystic/breadcrumbs#483]
**Describe the bug**
Hey, thank you for this great plugin!

I noticed 5 issues as labelled in the screenshots below. Please find the corresponding descriptions explaining each below.

1. Is it possible to remove this for items without any parents? (not a bug, more of a question and FR)

2. Numbering is not inline with the note titles. Perhaps it is caused by the Blue Topaz theme? Would it be possible to fix this somehow so everything displays nicely inline? (bug)

3. For child bullets, is it possible to preserve tree like structure in the matrix view? I tried the tree view as well but for some reason I was seeing multiple duplicates, not sure why? (bug + FR)

4. When I'm viewing the note titled 'kush' inside the `Information Gathering` folder, why is it listing several notes outside of this folder under 'Same'? I would like it to only list the notes within the same folder. Apologies if there is something wrong with my configuration. I tried various different configurations but couldn't get it to display right. Any ideas? (bug)

5. I tried using the `Hierarchy Note(s)` option but it wouldn't update neither my matrix view nor trail view. Also, the drop down selector seems to be missing options for `down` as well as all others. (bug)

I'm happy to open individual issues for each of these after each is reviewed and confirmed which ones are actual bugs vs FRs. Just temporarily grouping them all in 1 report for now for a quick conversation to get some feedback.

Thanks in advance!

**Screenshots**
![image](https://user-images.githubusercontent.com/10906010/235329698-6062f842-1cdc-41af-837b-5c78da07a973.png)

![image](https://user-images.githubusercontent.com/10906010/235329700-c5c73a80-5691-430c-bfdc-786df70eb266.png)

![image](https://user-images.githubusercontent.com/10906010/235329703-e0134f9a-e03d-4297-9dee-faa02744a5fb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional x64
 - Obsidian: v1.1.16
 - Breadcrumbs: 3.6.4
 - Theme: Blue Topaz 20230426

**Comment by SkepticMystic** [comment]
I'm gonna consider this to be complete by v4. Please reopen if you run into any issues after upgrading
