### ISSUE TITLE
Bug: Breadcrumbs showing incorrect links/indexes - Should be using path+filename for matching when creating indexes instead of only filename alone

### ISSUE THREAD

**Issue by qazero** [SkepticMystic/breadcrumbs#485]
**Describe the bug**
If you have a note with the same name in different folders Breadcrumbs is incorrectly showing links. It is not respecting the different paths, it is only using the filename for matching when it should be matching against the entire path+filename.

In my screenshot below I have created 2 folders named 'test1' and 'test2'. Inside each folder I created a new note with the name 'Untitled'. As you can see in the screenshot, it is showing multiple links in the trail when it should only be showing `Security -> test` for the note which is selected and shown in the screenshot.

Below is what I used in the frontmatter of Security.md to generate the trail indexes for the rest of the notes. Please let me know if this is incorrect.
```yaml
BC-folder-note: down
BC-folder-note-recursive: down
```

**Expected behavior**
Breadcrumbs should be using path+filename for matching when creating indexes instead of only filename alone.

**Screenshots**
![image](https://user-images.githubusercontent.com/10906010/235380490-2d3da488-9654-4254-af78-b6dcae3e10f5.png)

**Desktop (please complete the following information):**
- OS: Windows 10 Professional x64
- Obsidian: v1.1.16
- Breadcrumbs: 3.6.4
- Theme: Blue Topaz 20230426

**Comment by jiajiala** [comment]
I had the same problem
