### ISSUE TITLE
Update Breadcrumb after file renamed 

### ISSUE THREAD

**Issue by LeonardoGentile** [SkepticMystic/breadcrumbs#486]
Hello,
I'm aware there are multiple closed issues about this requests, see #371, #174, #110, #80

I've read that it would be problematic to do this into breadcrumbs and it would probably require a plugin per se.
The thing is that I find this plugin extremely useful and this is the only drawback.

Also, originally excalibrain, another extremely useful plugin was based on this plugin but the creator moved away exactly for this issue when renaming files (see https://github.com/zsviczian/excalibrain/issues/115) 

By fixing this issue it could be possible to integrate it with excalibrain.

Can we support you somehow with a donation or could you point us what should be done to develop such a plugin/ feature?

**Comment by LeonardoGentile** [comment]
This shouldn't be a problem after the introduction of [Properties](https://help.obsidian.md/Editing+and+formatting/Properties#Links) 

When using properties and triggering an internal link with `[[` then obsidian will automatically surround the internal link with quotes!
Also when you rename the linked file the property of the file that is linking from will update as well !!

🎉🎉

**Comment by SkepticMystic** [comment]
Hey @LeonardoGentile thanks for the issue.
I believe this should be working in v4, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md.
Gonna close this out for now
