### ISSUE TITLE
Bug: Cannot refresh index

### ISSUE THREAD

**Issue by 0ge** [SkepticMystic/breadcrumbs#489]
**Describe the bug**
When refreshing the index, it does not update.

**To Reproduce**
1. Create a new folder
2. Add two notes; `Parent` and `Child` (see below)
3. Refresh index

Parent.md:

```
---
BC-folder-note: down
---
```

Child.md:

```
Any content
```

**Expected behavior**
A relationship is created between Parent and Child.

**Screenshots**
Here is the console log:

```
plugin:breadcrumbs:18837 TypeError: Cannot read properties of null (reading '1')
    at getHierarchyNoteItems (plugin:breadcrumbs:16532:56)
    at async buildMainG (plugin:breadcrumbs:18803:37)
    at async refreshIndex (plugin:breadcrumbs:18873:18)
    at async HTMLButtonElement.click_handler_1 (plugin:breadcrumbs:24256:5)
buildMainG @ plugin:breadcrumbs:18837
await in buildMainG (async)
refreshIndex @ plugin:breadcrumbs:18873
click_handler_1 @ plugin:breadcrumbs:24256
```

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 13.2.1 (22D68)

**Additional context**
This does not happen in a clean vault, but it does happen in my primary vault. I don't think it has ever worked reliably. (I did not use Breadcrumbs from start)

**Comment by 0ge** [comment]
Seems like I found the issue…

**To reproduce**
1. Enable Hierarchy notes alternative
2. Set "Offending.md" as note to use for hierarchy
3. Create the files below
4. Refresh index

*Offending.md*

```markdown
- [A note]
```

*A note.md*

```
This is a note
```

**Comment by SkepticMystic** [comment]
I'm rebuilding Breadcrumbs from scratch. See here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
I probably won't fix this issue in the v3 version, but it may already be resolved in v4. Please try when you're ready and let me know

**Comment by SkepticMystic** [comment]
@0ge have you tried out v4 yet? Let me know if this is resolved for you

**Comment by 0ge** [comment]
I haven't tried with v4 and will probably wait until it's available as regular. I'll try to remember to check then. Currently, this is not an issue for me.

**Comment by SkepticMystic** [comment]
Gonna consider this closed in v4
