### ISSUE TITLE
I couldn't see any list

### ISSUE THREAD

**Issue by jakeoung** [SkepticMystic/breadcrumbs#49]
Hello, I'd like to use your amazing plugin, but it seems something wrong on my computer.

I have the index file and set a child, but I couldn't see anything in the breadcrumbs tab as follows:

![image](https://user-images.githubusercontent.com/2376897/125172773-67b14b00-e1b3-11eb-9fb2-84df32a5b885.png)

I use Mac. Do you have any idea?

**Comment by SkepticMystic** [comment]
Hey :)
Can you also screenshot your settings, and also open up the console and send any errors that come up (`Ctrl + Shift + I`). 
If there are no errors, change notes a few times and see. If there's still nothing, turn on debug mode in the settings and try again. If there's still nothing, turn on super debug mode and try again.

**Comment by jakeoung** [comment]
![image](https://user-images.githubusercontent.com/2376897/125175945-828dba80-e1c7-11eb-9941-48f38513c6ac.png)
![image](https://user-images.githubusercontent.com/2376897/125175948-88839b80-e1c7-11eb-9b16-bf82feee24e9.png)

After checking the console, I realize that I have this error:
```
VM1233:8459 Uncaught (in promise) TypeError: Cannot destructure property 'gParents' of 'this.plugin.currGraphs' as it is undefined.
    at MatrixView.draw (eval at <anonymous> (app.js:1), <anonymous>:8459:17)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:8383:24)
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
```

**Comment by WhatABloooke** [comment]
Hi I'm also getting similar-looking errors and have done since maybe version 2 or 3 (can confirm exact version when I'm on my desktop later today). No combination of settings has yet made any change. Let me know if there's any more data I can send from my case. Thanks!

>Uncaught (in promise) TypeError: Cannot destructure property 'gParents' of 'this.plugin.currGraphs' as it is undefined.
    at MatrixView.draw (eval at <anonymous> (app.js:1), <anonymous>:8459:17)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:8383:24)
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
VM176:6320 Uncaught (in promise) TypeError: Cannot read property 'path' of null
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6320:118)
    at Array.map (<anonymous>)
    at getFields (eval at <anonymous> (app.js:1), <anonymous>:6320:62)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6342:63)
    at Array.map (<anonymous>)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6342:18)
    at Array.map (<anonymous>)
    at getNeighbourObjArr (eval at <anonymous> (app.js:1), <anonymous>:6336:48)
    at BreadcrumbsPlugin.initGraphs (eval at <anonymous> (app.js:1), <anonymous>:9424:36)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:9374:46)
VM176:8459 Uncaught (in promise) TypeError: Cannot destructure property 'gParents' of 'this.plugin.currGraphs' as it is undefined.
    at MatrixView.draw (eval at <anonymous> (app.js:1), <anonymous>:8459:17)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:8371:47)

**Comment by SkepticMystic** [comment]
@jakeoung @WhatABloooke the error `Cannot destructure property 'gParents' of 'this.plugin.currGraphs' as it is undefined` is "normal". That happens when the plugin tries to show the breadcrumbs before the graphs have initialised. This should only happen once on load, though.

@jakeoung that second error is from Breadcrumbs, and I think that's where the problem is!
Can you turn on Super Debug Mode in the settings, change notes, and send me a screenshot of the last few console logs before that error. There will be alot, but the last few should tell us where the error happens.

@WhatABloooke Aside from this error you have, does everything else work as intended?

**Comment by SkepticMystic** [comment]
Also, do you guys have dataview enabled? You shouldn't have to have it enabled, but the functionality is different if you do

**Comment by BricoleurSoul** [comment]
Yes, use it extensively for many purposes.

David

**Comment by SkepticMystic** [comment]
Alright, that should actually help. I think Dataview's metadatacache is more standardised, so less goes wrong.
For now, I need those console logs from Jake to move further on this issue.

Regarding the error `Cannot destructure gParents...`, I am waiting on dataview to expose the `index-ready` event so I don't have to hardcode a timeout period before trying to use it's index

**Comment by WhatABloooke** [comment]
> @WhatABloooke Aside from this error you have, does everything else work as intended?

No, I'm getting the same empty pane and lack of trail at the top of notes as the OP. I thought it might be a related issue. I do have dataview enabled though.

**Comment by SkepticMystic** [comment]
@WhatABloooke can you do the same thing then. Enable super debug mode, change notes, and send me the last few console logs that appear

**Comment by jakeoung** [comment]
Even if I change the note, the debug doesn't change. ( I enabled superdebug mode). I don't use dataview plugin, but I installed it one month ago or something. Thanks!

**Comment by WhatABloooke** [comment]
![image](https://user-images.githubusercontent.com/74401804/125189226-8ffb8100-e269-11eb-91c6-dafa4a6879e0.png)

This is the last handful of logs. It also doesn't change when I change notes. I'll go through my plugin list and see if I can isolate any conflicts there.

**Comment by WhatABloooke** [comment]
There's no change with no community plugins enabled except Breadcrumbs and Dataview. Same logs, same blank list.

**Comment by SkepticMystic** [comment]
@jakeoung you don't see a whole bunch of console logs? Super debug mode should log lots of thing.
I suppose if it doesn't then the problem is elsewhere, but the error indicates that it is to do with the metadata in one of your notes

**Comment by SkepticMystic** [comment]
@WhatABloooke alright this is good, the error should be something to do with the content of the note `three clue rule`.
Can you send a screenshot of that note

**Comment by jakeoung** [comment]
@SkepticMystic Yes, I have lots of debugging console.

![image](https://user-images.githubusercontent.com/2376897/125191004-1e570f00-e238-11eb-9bd3-016ed543858f.png)

In the note called ring, filed, I have this metadata:
---
sibling: [[group = set + binary operation]]
---
Is there something wrong here?

**Comment by SkepticMystic** [comment]
@jakeoung can you send the content of the entire `ring` note, if you're fine with that. You can also DM it to me on Discord if you want :)

Can you also enter this into the console and send the results: `app.plugins.plugins.dataview.api.page('ring')`

**Comment by jakeoung** [comment]
I solved this issue by installing dataview plugin and using [[ ]] in the metadata

**Comment by SkepticMystic** [comment]
@WhatABloooke we can leave this issue open until we've figured out the bug for your setup :)
You can message me on Discord with the screenshot if you prefer!

**Comment by jakeoung** [comment]
With the new version 0.8.8, it works without dataview

**Comment by SkepticMystic** [comment]
@WhatABloooke give version `0.8.8` a try, I think it should fix your issue as well :)
