### ISSUE TITLE
Bug: Hierarchy Notes, Traverse Notes not working

### ISSUE THREAD

**Issue by socoldie** [SkepticMystic/breadcrumbs#493]
**Describe the bug**
Hierarchy Notes and Traverse Notes not working.

**To Reproduce**
Steps to reproduce the behavior for Hierarchy Notes:
1. Create hierarchy note
2. Write hierarchy note name in Breadcrumbs Settings under Alternative Hierarchies > Hierarchy Notes
3. Refresh BC index in Breadcrumbs Matrix
4. Relationships not created

Steps to reproduce the behavior for Traverse Notes:
1. Add the following to a note with links:
`---
BC-traverse-note: next
---`
2. Refresh BC Index
3. Relationships not created

**Expected behavior**
Expected Breadcrumbs relationships to be created.

**Desktop (please complete the following information):**
 - OS: Windows 10 on Macbook Pro Bootcamp
 - Version 22H2

**Comment by SkepticMystic** [comment]
Just to clarify, are you adding `--- BC-traverse-note: next ---` to the note, or:
```
--- 
BC-traverse-note: next 
---
```

**Comment by derekvan** [comment]
I can confirm that the Hierarchy Notes option isn't working. I can see the hierarchy note in the "adjust hierarchy notes" option, but none of the relationships are visible in the various views.

**Comment by derekvan** [comment]
that works, thanks!

**Comment by SkepticMystic** [comment]
Great :) please do share any feedback from the beta, it really helps!
