### ISSUE TITLE
Bug: Unable to update/install Breadcrumbs 3.6.7

### ISSUE THREAD

**Issue by I-Pch** [SkepticMystic/breadcrumbs#497]
**Describe the bug**
While checking if there were any updates available for my installed Community plugins, I discovered that, apparently, one was available for Breadcrumbs (`3.6.4` -> `3.6.7`).

But, the problem is that Obsidian can't install it for some reasons 😔 ... (either for a fresh install or an update)  

---
**To Reproduce**
1. Go to Obsidian's `Settings` -> `Community plugins`
2. Click on `Check for updates` (under `Current plugins`)
    - -> Obsidian finds an update for `Breadcrumbs` (if it's already installed)
3. Click on `Update all` (under `Current plugins`) or find `Breadcrumbs` in the list of installed Community plugin below and click on `Update`
    - -> Obsidian returns a `Failed to install plugin "Breadcrumbs".` alert    

---
**Expected behavior**
Being able to update/install the latest version of `Breadcrumbs` (which per the [manifest would be `3.6.7`](https://github.com/SkepticMystic/breadcrumbs/blob/master/manifest.json#L4), as opposed to what's currently available in the `Releases` in the GH repo (where the latest version is still `3.6.4`)) 😊 

---
**Screenshots**
<img width="851" alt="Failed to install Breadcrumbs" src="https://github.com/SkepticMystic/breadcrumbs/assets/77828085/23929b6b-4a7d-4a63-a1cb-8b8928ccfd1f">

---
**Desktop:**
 - OS: `MacOS Big Sur 11.7.10` 
 - `Obsidian 1.5.3`

**Comment by psc0425** [comment]
have the same problem when tried to install it.

**Comment by issaqua** [comment]
Same here, console reports:  "Uncaught (in promise) Error: fatal: bad revision 'null' ..." when I uninstalled and tried to install from scratch.

**Comment by I-Pch** [comment]
Apparently, the issue is being worked on 😁, as stated here: https://github.com/SkepticMystic/breadcrumbs/issues/498#issuecomment-1878629167

**Comment by I-Pch** [comment]
As I was able to install `Breadcrumbs 3.6.11` 🎉 , I'm closing the issue 😊 !
Thank you @SkepticMystic 😁 !!!
