### ISSUE TITLE
Plugin cannot be installed

### ISSUE THREAD

**Issue by joethei** [SkepticMystic/breadcrumbs#498]
Hi @SkepticMystic 

We have noticed that the latest release of your plugin cannot be installed currently.

This is due to the following reason:
- No release found for version 3.6.9

We will remove this plugin from the community plugins not fixed within 30 days.

- The Obsidian Team

**Comment by SkepticMystic** [comment]
Thanks for letting me know.
I'm aware of the issue and trying to resolve when I've got the time. The build command isn't working anymore (last update was more than a year ago), so I need to figure that out or put a release together manually.
