### ISSUE TITLE
separate panels for matrix view and breadcrumbs

### ISSUE THREAD

**Issue by weeyizhi** [SkepticMystic/breadcrumbs#5]
Perhaps the matrix view and breadcrumbs could be separated? Most of the time I find myself needing the breadcrumbs more. Having them at the same pane makes it such that I have to scroll down to see the breadcrumbs

**Comment by SkepticMystic** [comment]
I can definitely do this. There would just be two separate views for each

**Comment by SkepticMystic** [comment]
I have separated the two views. The breadcrumbs trail now appears at the top of the note. This is still buggy, but I'll close this issue and others can be opened for the new bugs
