### ISSUE TITLE
Bug: Breadcrumbs visualisation completely broken

### ISSUE THREAD

**Issue by just-a-garlic-bread** [SkepticMystic/breadcrumbs#500]
**Describe the bug**
None of the options in the  breadcrumb visualisation  work, including every type, relation, close and unlinked options, the only one that regularly works is Arc Diagram 
**To Reproduce**
1. Click the ribbon button
2. See nothing happening, even when changing settings
3. Open developer options(optional)
4. See error(s)

**Expected behavior**
At least seeing force-directed graph working, as it is the one that is set by defaut?

**Screenshots**
![image](https://github.com/SkepticMystic/breadcrumbs/assets/132960873/b63c9c13-c1a0-463d-b622-4afb4507212e)
![image](https://github.com/SkepticMystic/breadcrumbs/assets/132960873/9eb324f1-a231-49b2-be5d-86b375efd288)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version:  21H2

**Additional context**
On some of them it keps sending the same error over and over again, untill stopped by closing visualisation.I understand not all of them are supposed to work at this point, since update was pretty recently

The same problems appear on two of the vaults i checked on, so it cant be plugin/script/theme incompatability

**Comment by wwjCMP** [comment]
I encountered the same bug.

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue.
It's true to say that this feature doesn't work. However, I don't currently intend to put time towards it, unfortunately. If you haven't seen already, I've rebuilt Breadcrumbs from scratch and it's now available in V4: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
I haven't implemented the Visualisation View in v4, and don't plan to. It was a very underused feature, and relied on external libraries I never fully understood. 
So, for now, I'm gonna close this out as unplanned. Please let me know if you've got any questions about the V4 beta
