### ISSUE TITLE
Add BC-folder-note-subfolders to wiki

### ISSUE THREAD

**Issue by flip-rossi** [SkepticMystic/breadcrumbs#504]
**Is your feature request related to a problem? Please describe.**  
I'm really struggling to understand how I'm supposed to use `BC-folder-note-subfolders` and even the way `BC-folder-note` works seems inconsistent with the wiki...

**Describe the solution you'd like**  
Add a clear example of these properties being used to the wiki so it's easier to understand.

**Describe alternatives you've considered**  
I've already tried searching but couldn't find any clear explanation of the feature.

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue!
To confirm, are you on v3 or v4 of Breadcrumbs? There are a couple differences in how folder notes work there.
But either way, I could definitely clarify the docs

**Comment by flip-rossi** [comment]
> are you on v3 or v4 of Breadcrumbs?

I got the plugin from within Obsidian, so I'm on v3.6.11

> There are a couple differences in how folder notes work there

Oh, alright. Could you quickly tell me what those are?

> I could definitely clarify the docs

That would be great, thanks!

**Comment by SkepticMystic** [comment]
Alright, that's the current "production" version. I'm working on v4 at the moment, which is in beta, available via the BRAT plugin. Two differences so far:
1. The field is now called `BC-folder-note-field`
2. You can use `BC-folder-note-recurse: true` to enabled subfolder recursion (without this, only the immediate children notes in a folder will be connected

Consider updating to V4, after reading the `V4.md` file in the root of the repo

**Comment by SkepticMystic** [comment]
I've rewritten the README and it explains Folder Notes better now. I'm gonna close this out, even though v4 isn't in production yet, the docs are up to date
