### ISSUE TITLE
Bug: v4 grid view on top of note multiplies as you back/forward the pane

### ISSUE THREAD

**Issue by derekvan** [SkepticMystic/breadcrumbs#511]
**Describe the bug**
As I go back/forward in the window, I get a new instance of the grid view in the note--I now have 6 repeated grids in the note I'm currently viewing.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 1.5.8

**Comment by SkepticMystic** [comment]
That's wild... please share the version of Obsidian and Breadcrumbs you're on, and your `.obsidian/plugins/breadcrumbs/data.json`

**Comment by derekvan** [comment]
Obsidian 1.5.8
Breadcrumbs 4.0.20-beta

**Comment by derekvan** [comment]
[data.json](https://github.com/SkepticMystic/breadcrumbs/files/14572382/data.json)

**Comment by derekvan** [comment]
possible variable: this was when viewing a note open in a second window, not in the main obsidian window.

**Comment by SkepticMystic** [comment]
Like a 2nd tab within the same Obsidian instance?

**Comment by derekvan** [comment]
no, like from the note context menu, "open in new window"

**Comment by SkepticMystic** [comment]
Oh wow, I didn't know that was possible! Ok, this is definitely the cause. I'll need to understand the interaction here a bit better first. Thanks for the info :)

**Comment by derekvan** [comment]
also, if I click a link in the grid when open in a new window like that, it closes the window.

**Comment by SkepticMystic** [comment]
Do regular Obsidian links not do that? They navigate within the newly opened window?

**Comment by SkepticMystic** [comment]
@derekvan please give the latest version a try, I think this specific issue is resolved now. Note, that I've had to use `span` instead of `a` on links for a different reason, so for now, the right-click context menu doesn't work on BC links. To open in another window, you have to use ctrl+shift+alt+click

**Comment by derekvan** [comment]
yeah, looks to be working on my end as well

**Comment by SkepticMystic** [comment]
Great, thanks for confirming
