### ISSUE TITLE
Bug: V4 [Mobile] Obsidian crashes when tapping a BC link

### ISSUE THREAD

**Issue by Anarchtism** [SkepticMystic/breadcrumbs#512]
**Describe the bug**
Obsidian mobile crashes to a black screen when tapping a link embedded by Breadcrumbs in Page View, Matrix View, or Tree View.

**To Reproduce**
1. Tap a link in Page View, Matrix View, or Tree View.

**Expected behavior**
Navigating to the tapped note.

**Screenshots**
https://github.com/SkepticMystic/breadcrumbs/assets/128257705/1c9a7282-60e5-4253-b928-6eb546785a2b

![Screenshot_20240313-111147_Obsidian](https://github.com/SkepticMystic/breadcrumbs/assets/128257705/0406f3ca-00ef-4b3f-820a-f49f5f43ce99)

**Smartphone:**
 - Device: OnePlus 7T Pro 5G
 - OS: Android 13
 - Version: 4.0.23-beta

**Comment by SkepticMystic** [comment]
Closed by latest release :) Thanks Abi!
