### ISSUE TITLE
Bug: V4 - Notes with embedded notes in them don't show any Breadcrumbs views at the top of the note (Page View) 

### ISSUE THREAD

**Issue by Anarchtism** [SkepticMystic/breadcrumbs#513]
**Describe the bug**
Notes with embeds don't show "Page View" at the top of the note in Obsidian's Reading View (but they are shown in Editing View).

**To Reproduce**
1. Make a note that embeds another note <pre>!\[\[random note here\]\]</pre>
2. Add things that would normally make Breadcrumbs' Page View at the top

**Expected behavior**
Page View should show.

**Desktop:**
 - OS: Windows 11
 - Version: 4.0.23-beta

**Comment by soulsynapse** [comment]
+1 recreated on my device

so weird that it's JUST the pages with embeds

**Comment by Anarchtism** [comment]
Fixed as of 4.0.45-beta. Great work!
