### ISSUE TITLE
Bug: V4 -- Assigning to the same relation in multiple areas in a note doesn't work if one of the relations is an array

### ISSUE THREAD

**Issue by Anarchtism** [SkepticMystic/breadcrumbs#514]
**Describe the bug**
Breadcrumbs detects the "note one" prev, but not the "note two" and "note three:"
```
prev:: [[note one]]
Blah blah blah...

prev:: [[note two]], [[note three]]
Bleh bleh bleh
```

---

This works properly:
```
prev:: [[note one]]
Blah blah blah...

prev:: [[note two]]
Bleh bleh bleh
```

---

**To Reproduce**
```
prev:: [[note one]]
Blah blah blah...

prev:: [[note two]], [[note three]]
Bleh bleh bleh
```

**Expected behavior**
Breadcrumbs should show all three notes.

**Screenshots**
What works:
![Screenshot_20240316-062317_Obsidian](https://github.com/SkepticMystic/breadcrumbs/assets/128257705/c5e176eb-48c1-47e0-a235-7ab474f820d6)
![Screenshot_20240316-062324_Obsidian](https://github.com/SkepticMystic/breadcrumbs/assets/128257705/5ef2f867-11b4-419f-9ae4-e52e475e497a)

What doesn't:
![Screenshot_20240316-062355_Obsidian](https://github.com/SkepticMystic/breadcrumbs/assets/128257705/a6a4b01b-0bef-48a3-8ccf-fb8f6539aa03)
![Screenshot_20240316-062359_Obsidian](https://github.com/SkepticMystic/breadcrumbs/assets/128257705/1b596536-0c50-4de0-8dea-ed40bbff6435)

**Desktop:**
 - OS: Windows 11
 - Version: 4.0.29-beta

**Smartphone:**
 - Device: OnePlus 7T Pro 5G
 - OS: Android 13
 - Version: 4.0.29-beta

**Comment by SkepticMystic** [comment]
Resolved in the latest beta release :) Thanks for the detailed issue!
