### ISSUE TITLE
BC-list-note-neighbour-field default to next

### ISSUE THREAD

**Issue by Cammagno** [SkepticMystic/breadcrumbs#515]
Please make "next" the default value for BC-list-note-neighbour-field, making it unnecessary to add it to all List Notes.

Reference: https://github.com/SkepticMystic/breadcrumbs/issues/392#issuecomment-2002918450

**Comment by SkepticMystic** [comment]
Completed in latest release! There's now an option to set the default neighbour field: https://github.com/SkepticMystic/breadcrumbs?tab=readme-ov-file#list-note-settings
