### ISSUE TITLE
BC v4: Display Breadcrumb trail on all visible notes

### ISSUE THREAD

**Issue by SlRvb** [SkepticMystic/breadcrumbs#516]
**Is your feature request related to a problem? Please describe.**
Currently the beta is only to view the breadcrumb trail on the currently active page as opposed to both pages that both have trails I need to see

**Describe the solution you'd like**
Displaying the trail on any/every opened note that has a trail.

**Additional context**
Currently it's also not consistent with actually showing me the trail on an active note, only when I change the view or give it enough time to switch over.

**Comment by SkepticMystic** [comment]
For when I work on this, I think a simple fix is to check _only_ inside the `active_markdown_view` for an existing TrailView. Currently I check the entire document, which prevents it from existing in multiple places

**Comment by SkepticMystic** [comment]
Closed in latest release
