### ISSUE TITLE
Bug: V4 -- Can't open links in Page View, Matrix View, or Tree View as a new tab

### ISSUE THREAD

**Issue by Anarchtism** [SkepticMystic/breadcrumbs#518]
**Describe the bug**
Middle clicking a link in Page View, Matrix View, or Tree View doesn't do anything. Ctrl + clicking closes the current tab and opens the link twice -- with both pages [linked](https://help.obsidian.md/User+interface/Tabs#Linked+views) to each other.

**To Reproduce**
1. Middle click or Ctrl + click a link in Page View, Matrix View, or Tree View

**Expected behavior**
The link should open in a new tab.

**Desktop:**
 - OS: Windows 11
 - Version: 4.0.50-beta

**Comment by SkepticMystic** [comment]
Please give the latest version a try and let me know. My tests seem fine now based on the steps you gave

**Comment by SkepticMystic** [comment]
Confirmed working over Discord

**Comment by Anarchtism** [comment]
Ctrl + click was fixed, but middle click still doesn't do anything. Should I open a separate issue for that?

**Comment by SkepticMystic** [comment]
Ahh right, I forgot. Please yes
