### ISSUE TITLE
Bug: V4 -- Ctrl + Click on a link in Codeblocks View opens the link in two tabs

### ISSUE THREAD

**Issue by Anarchtism** [SkepticMystic/breadcrumbs#520]
**Describe the bug**
Ctrl + Click on a link in Codeblocks view opens the link in two different new tabs instead of just one.

**To Reproduce**
1. Ctrl + Click a link in Codeblocks view

**Expected behavior**
The link should open only once in a new tab.

**Desktop:**
 - OS: Windows 11
 - Version: 4.0.65-beta

**Additional context**
Interestingly, middle click works properly in Codeblocks View and opens only one new tab.

**Comment by SkepticMystic** [comment]
Thanks Abi.
All these issues are related. For reference, here's the discussion on Discord: https://discord.com/channels/686053708261228577/840286264964022302/1223576343044948028
I _believe_ there is an issue with Obsidian where using `openLinkText` from a view _not inside a Markdown editor_ crashes Obsidian on mobile

And here's the repo where I'm trying to minimally recreate the issue so the Obsidian devs can take a look: https://github.com/SkepticMystic/obsidian-openLinkText-mobile-bug

**Comment by Anarchtism** [comment]
Fixed as of 4.0.73-beta!
