### ISSUE TITLE
Bug: v4 Folder note breaking for non-MD files in directories

### ISSUE THREAD

**Issue by maggiedelano** [SkepticMystic/breadcrumbs#522]
**Describe the bug**
When using BC folder notes, breadcrumb graph generation sometimes stalls out, likely due to processing files that either don't exist or aren't md files.

**To Reproduce**
1. Add a non md file to a folder.
2. Include `BC-folder-note-field: down` for a note in that folder.
3. Rebuild graph.
4. See error in console.

**Expected behavior**
Folder notes should work on all the markdown files in the folder, regardless of other folders or files present.

**Screenshots**
<img width="794" alt="Screenshot 2024-03-31 at 5 40 23 PM" src="https://github.com/SkepticMystic/breadcrumbs/assets/4552976/f00504ae-be88-4a45-b47f-203643dfdc56">
<img width="903" alt="Screenshot 2024-03-31 at 5 48 03 PM" src="https://github.com/SkepticMystic/breadcrumbs/assets/4552976/8cef8d1a-bdb5-48f8-bcdc-4a02c7c16802">

**Desktop (please complete the following information):**
 - OS: Mac 13.4.1
 - Version: Breadcrumbs 4.0.68-beta

**Comment by SkepticMystic** [comment]
Thanks for the detailed issue! Makes sense, should be simple to fix
