### ISSUE TITLE
Bug: Clicking a link on the right-hand-side Matrix pane now requires two clicks instead of one.

### ISSUE THREAD

**Issue by Brett-ai** [SkepticMystic/breadcrumbs#523]
When clicking on a link in the right-hand-side Matrix pane, the first click moves focus to the Matrix window/pane (the cursor in the central edit pane disappears), and then it requires a second click to activate the link.

But you used to be able to just click on the link in the Matrix pane and at it would follow the link immediately - you didn't need to move focus to the Matrix pane before activating the link.

Is there any way to get back to the old behavior?

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue.
Please confirm which version of Breadcrumbs you're on? I fixed this issue in an earlier release, but it may have regressed

**Comment by Brett-ai** [comment]
It seems to be fixed now. I might have been on an older version. Thanks!

**Comment by SkepticMystic** [comment]
Ok cool, thanks for the update. I think BRAT automically upgrades plugins sometimes
