### ISSUE TITLE
Hide Trail View Buttons in Version 

### ISSUE THREAD

**Issue by Pummelfisch** [SkepticMystic/breadcrumbs#525]
**Is your feature request related to a problem? Please describe.**
Buttons and options on top of the trail view in the neww v4 are taking a lot of vertical space.

**Describe the solution you'd like**
Add an option to hide the whole button area of the trail view. Settings could still be made from the settings menu.

**Additional context**
I mean the red marked area in the image bellow
![image](https://github.com/SkepticMystic/breadcrumbs/assets/67376951/94893b0e-4f19-497b-98a2-27453368cd15)

**Comment by SkepticMystic** [comment]
Agreed! Thinking about it now, I don't even use the controls on my main vault.
It's still the default behaviour, but there's now a toggle under `Settings > Views > Page > Trail > Show Controls` to disable this
