### ISSUE TITLE
Bug: V4 -- Mermaid type Codeblocks View parsing error when dealing with parentheses in filenames

### ISSUE THREAD

**Issue by Anarchtism** [SkepticMystic/breadcrumbs#526]
**Describe the bug**
If a Codeblocks View that is `type: mermaid` has to include a notes that has a parenthesis in the filename, it results in a parsing error.

**To Reproduce**
1. Make a note with a parenthesis in the filename
2. Give it some sort of relation to another note
3. Go to the other note and add a Mermaid type Codeblocks View to it that would/should show the note with a parenthesis

**Expected behavior**
A rendered Mermaid graph.

**Desktop:**
 - OS: Windows 11
 - Version: 4.0.90-beta

**Smartphone:**
 - Device: OnePlus 7T Pro 5G
 - OS: Android 13
 - Version: 4.0.90-beta

**Comment by SkepticMystic** [comment]
Thanks Abi, please give the latest release a try, I think I've got this fixed

**Comment by Anarchtism** [comment]
Oops, just did! Very nice.

**Comment by SkepticMystic** [comment]
Awesome, thanks!
