### ISSUE TITLE
FR: V4 tree view: Show tree up and down to provide more context of current note

### ISSUE THREAD

**Issue by boriskroeger** [SkepticMystic/breadcrumbs#530]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I like the tree view to show the trail UP and DOWN from the current note so that I can have a broader context.
In the old version I could select to show UP and DOWN in the side view.

**Describe alternatives you've considered**
Alternative would be to manually switch between UP and DOWN in the tree view.

**Additional context**
Given the following note

```
note A
- up: note X
- down: note Y
```

I would like the tree view to show
```
direction: context (new option, or UpDown)

- note X       <-- tree shown reversed (the higher, the less indented)
  - note A     <-- highlight e.g. bold
    - note Y   <-- standard tree view (the deeper, the more indented)
```

**Comment by SkepticMystic** [comment]
Hey, thanks for the issue!
Although it's not exactly what you're requesting here, for now I'm gonna to suggest that you just open the Tree View twice, one for `up`, one for `down`. You can do this by right-clicking the Tree View icon, and clicking "Split down"

**Comment by IanCKW** [comment]
hi. Can I pick your brain as to why this is not a (planned) feature? Feels like the other (have options that allow them to) them respect the idea that notes higher in the hierarchy should be on the left-and-higher relative to the current node. 

With codeblocks, you can even set the mermaid direction to be bottom-to-top.

I'm asking as I'm wondering if I'm not using the tree view as intended.
