### ISSUE TITLE
FR: Allow the running of the Freeze command in bulk

### ISSUE THREAD

**Issue by ybalkind** [SkepticMystic/breadcrumbs#542]
**Is your feature request related to a problem? Please describe.**

As I'm shaping my graph around the Breadcrumbs plugin, I'm realising that I'm becoming very dependent on it. I have a lot of notes that are linked to each other via breadcrumb property fields with only one edge being explicit, but the various breadcrumbs views enable me to easily see those implicit connects and navigate my notes. If I were to use my notes outside of Obsidian, or to stop/be-unable to use this plugin, navigating through my notes would become difficult and I would lose my whole structure. 

"Freezing crumbs to file" goes a long way to alleviating this because then both files would have a reference to each other. So having the ability to freeze all crumbs across the vault would make me feel much safer about relying on Breadcrumbs. 

Of course the reference to each other would be there through backlinks, but that's not the same because a reference through the edge-field is distinct from other other backlinks and its important that a file referenced this way has a perpetual way of easily "finding" files linked to it

**Describe the solution you'd like**

Command to freeze all files in the vault. Right click on folder to freeze all files in folder. Right click on selected files to freeze all selected files. 

**Describe alternatives you've considered**

I'd have to create a dataview query on every page to find all links to that page from the specific property field. 

**Additional context**

The other element that would make the notes more future proof is the ability to turn all codeblock hierarchies into static markdown on page. So again, if I stop using the plugin or leave obsidian I have all my table of contents in place and I maintain the navigation that i've built between notes. I'll log this as seperate FR.

**Comment by SkepticMystic** [comment]
Nice yeah, I agree. This is in V3, so it makes sense to come over to V4

**Comment by ybalkind** [comment]
Its the kind of feature I might never need or hopefully not for years, but gives me huge comfort knowing its there.
