### ISSUE TITLE
Bug: Blank edge fields in cause error

### ISSUE THREAD

**Issue by ybalkind** [SkepticMystic/breadcrumbs#545]
**Describe the bug**

When graph rebuilds the little indicator block says there are many errors rebuilding
![image](https://github.com/SkepticMystic/breadcrumbs/assets/10196054/595f49b4-d4a6-4b43-a0db-964e0c81039b)

Going into console the errors are all caused by blank edge field properties
![image](https://github.com/SkepticMystic/breadcrumbs/assets/10196054/e6cf9ca4-9417-4f5a-9ca3-847616d87df1)

**To Reproduce**

Just rebuild graph or do anything that triggers graph rebuild. The error message appears in the little block that gives the status of the rebuild

**Expected behavior**

Successful graph rebuild with no errors

**Screenshots**

See above

**Desktop (please complete the following information):**

-   OS: Mac OS Sonoma
-   Breadcrumbs version: 4.12.18
-   Obsidian version: 1.5.12

**Comment by SkepticMystic** [comment]
Thanks, I've addressed this in the latest release

**Comment by ybalkind** [comment]
Thank you. Confirmed that its working on my end
