### ISSUE TITLE
Bug: V4 BC-list-note-exclude doesn't work for me

### ISSUE THREAD

**Issue by Cammagno** [SkepticMystic/breadcrumbs#548]
In my list note, called 
_MunchkinWorld
I set in the YAML
BC-list-note-exclude: true
(see left attached picture)
but it is ignored by BC, the trail starts from 
_MunchkinWorld
instead of starting from thew top folder (named MunchkinWorld) as expected
(see right attached picture)

Everything else works perfectly

![BC-excludeNW](https://github.com/SkepticMystic/breadcrumbs/assets/95725064/725dffb7-4a64-4fdf-8638-a4916ea12e74)

-   OS: Windows 11 Home
-   Breadcrumbs version: 4.2.18
-   Obsidian version: 1.5.12

Am I doing something wrong?

**Comment by SkepticMystic** [comment]
Hey Cammagno
I just double-checked, and the field is actually called `BC-list-note-exclude-index`. I'm gonna update this in the docs now, thanks for pointing this out! Please let me know if that works for you

**Comment by Cammagno** [comment]
> I just double-checked, and the field is actually called `BC-list-note-exclude-index`. I'm gonna update this in the docs now, thanks for pointing this out! Please let me know if that works for you

Yes, now it works!

Thanks a lot, and let me say that you did really a great work with this v.4

**Comment by SkepticMystic** [comment]
Thank you, that's great to hear :)
