### ISSUE TITLE
Implied relationship is real

### ISSUE THREAD

**Issue by SuperMeip** [SkepticMystic/breadcrumbs#57]
This is all the link code in my current vault:
![image](https://user-images.githubusercontent.com/11747166/125204973-e1961280-e24d-11eb-9c88-940ad6f2d5e7.png)

But for some reason, this note has a real link that should be implied:
![image](https://user-images.githubusercontent.com/11747166/125204980-ec50a780-e24d-11eb-86f3-ef603ec1833d.png)

Which is also making the implied note that shouldn't be there in the first image.

**Comment by SkepticMystic** [comment]
@SuperMeip do you mind checking if this issue is fixed in the latest release?
Breadcrumbs is on the community plugin page, so you can update it from there

**Comment by SuperMeip** [comment]
This looks to be fixed on my end!
