### ISSUE TITLE
Bug if a note title contains a comma ,

### ISSUE THREAD

**Issue by jakeoung** [SkepticMystic/breadcrumbs#58]
I have a note called "ring, r-module" and its child "vector space". In the vector space note, it seems to detect ring and r-module separately as follows:

![image](https://user-images.githubusercontent.com/2376897/125205104-8f1e1b80-e278-11eb-87c7-b9b4004e13b8.png)

**Comment by SkepticMystic** [comment]
I think the issue is that using commas in a yaml list `[]` will always be treated as separate values. (I don't split by commas anywhere, so I don't think it's from Breadcrumbs)
Links were never meant to go in yaml anyway, Breadcrumbs and dataview kinda use a hack to get around this, but the notes will always be seen as separate if they're in the yaml, I think

**Comment by SkepticMystic** [comment]
The only way around this is to use dataview inline fields `parent:: [[ring, r-module]]`. But I know that crashes your computer...
Maybe consider changing from commas to something else in the note names. But I can't change how yaml parses it

**Comment by jakeoung** [comment]
Okay, no problem. I will change the title without comma

**Comment by jakeoung** [comment]
To use the inline function, do I need to install dataview?

**Comment by SkepticMystic** [comment]
It's a long-shot, but what if you escape the comma? `[[ring\, r-module]]`

**Comment by SkepticMystic** [comment]
Yes, you do need dataview for inline fields

**Comment by SkepticMystic** [comment]
You can also use Juggl link syntax if you have Juggl enabled

**Comment by jakeoung** [comment]
Oh okay. with \, it still doesn't work, but it's fine. I will check Juggl!

**Comment by jakeoung** [comment]
Juggl works perfectly! I think I will keep using juggl syntax :)

**Comment by SkepticMystic** [comment]
That's great to hear :) 
It's a very powerful way to visualise your graph, too!
