### ISSUE TITLE
automatically find siblings and children

### ISSUE THREAD

**Issue by weeyizhi** [SkepticMystic/breadcrumbs#6]
Instead of having the user create fields for child/sibling, is it possible for the plugin to search for siblings (all children of parents except itself) and children from the graph itself? That would require less maintenance from the user.
- if A is a child of B, then C is a sibling of B if it is also a child of A.
-if A is a child of B, then saying B is a parent of A is redundant. You only need one.

**Comment by SkepticMystic** [comment]
Checkout #3, is this similar to what you are looking for?

**Comment by brimwats** [comment]
It might be possible to use code from the "find related notes" plugin

**Comment by SkepticMystic** [comment]
I _think_ I've implement implied children and implied parents... give it a try and let me know if it works on your vaults.
@brimwats, it is entirely possible that the refactoring I've done (#9)  means this plugin won't work if you don't have dataview installed... I plan to get it working again for those without dataview, but you may need to install it until then.

**Comment by SkepticMystic** [comment]
And now I think I've figured out implied siblings, too! Very curious to see if it works as expected

**Comment by weeyizhi** [comment]
I believe it's working correctly! I did a few tests but nothing rigorous though (I only use parent fields).

**Comment by SkepticMystic** [comment]
@brimwats will you let me know if this works properly on your larger sample size?

**Comment by SkepticMystic** [comment]
I think this works as intended. Gonna close this issue

**Comment by brimwats** [comment]
you are developing like lightining! I will report any bugs back here :)
