### ISSUE TITLE
Real parents at even positions are erroneously repeated in the "Implied" list

### ISSUE THREAD

**Issue by neatpun** [SkepticMystic/breadcrumbs#63]
When I first load this note, the bug is present only for parents:
![image](https://user-images.githubusercontent.com/35105426/125650650-4bb10a23-e3a5-4c97-b7aa-61c97e6ddc13.png)

Then when I click on "List" and the sidebar reloads, the bug appears for children as well:
![image](https://user-images.githubusercontent.com/35105426/125650812-c41ed01c-667a-4649-a37b-6abfcd843719.png)

**Comment by SkepticMystic** [comment]
@neatpun will you let me know if this still happens on `0.8.17`

**Comment by neatpun** [comment]
@SkepticMystic No longer happens in 0.8.18, thanks! Closing the issue.
