### ISSUE TITLE
[Feature] Work together with jump to link plugin

### ISSUE THREAD

**Issue by kometenstaub** [SkepticMystic/breadcrumbs#64]
Would it be possible to hook into this/add the functionality to breadcrumbs to press a hotkey, have a little popup next to a breadcrumbs link with a letter and then on pressing that letter to be taken to that linked page?

That's the plugin in question: https://github.com/mrjackphil/obsidian-jump-to-link

**Comment by SkepticMystic** [comment]
I've opened a FR for this, I'll see if there is something I can do on my side to make this easier to implement.

https://github.com/mrjackphil/obsidian-jump-to-link/issues/24

**Comment by SkepticMystic** [comment]
Does this just work now? I read that it works for Dataview links, and I think those work in the same way as BC

**Comment by SkepticMystic** [comment]
mrjackphil has closed the issue on their side, saying it should now work in 0.5.0 :)
