### ISSUE TITLE
Uncreated pages appear when switching to list mode:

### ISSUE THREAD

**Issue by SuperMeip** [SkepticMystic/breadcrumbs#65]
https://i.gyazo.com/61a65fb3a760657f69d1d9e08aba5545.gif

As you can see, a ton of non-existant pages suddenly join implied siblings.
These items are listed in a child field explicitly somewhere else(under Dawn), but have not been created yet, so maybe it's messing with it somehow?

**Comment by SkepticMystic** [comment]
Well, if Dawn is that note's parent, and all those new notes are Dawn's children, then they are also the current note's siblings. You know what I mean?
But it is weird that you first have to change view types to see them there.

Is it accurate that they are implied siblings, though? If your parent has other children, then those children must be your siblings

**Comment by SkepticMystic** [comment]
@SuperMeip what do you think of this issue? Is it accurate that those notes are implied siblings? Even if they haven't been created yet.
