### ISSUE TITLE
FR: Auto-Updating Index

### ISSUE THREAD

**Issue by FTWynn** [SkepticMystic/breadcrumbs#67]
I love the idea of this plugin and I would love to see a view where we could see the whole outline hierarchy at once, instead of just the relationships in the current pane.

Currently, I build the hierarchy myself in a sort of master outline note, and then use block references to bounce back and forth between individual notes and the outline, but if I could just generate that outline from the relationships that would be a huge overhead savings.

**Comment by SkepticMystic** [comment]
Thanks for the FR :)
I agree, this would be really useful! A bit of a secret, you can _kind of_ do this already... You see, I've been working on this feature since the beginning. This issue speaks about it already #3. It turns out to be deceptively difficult though. If you try out the existing feature you'll see the problem.
If you open the list/matrix view, you'll see the `Create Index` button. If you click it, and open up the console log, you'll see a nested markdown list going all the way down the `children` tree. It isn't perfect, as you'll see. But I'm working on it!

**Comment by SkepticMystic** [comment]
@FTWynn will you let me know if this works in 0.8.19 :)
Clicking the Create Index button will now copy the index to your clipboard

**Comment by FTWynn** [comment]
Confirmed on the root note up to six levels deep for now! Child notes only copy the hierarchy relative to them.

**Comment by SkepticMystic** [comment]
What do you mean they only copy the hierarchy relative to them? Can you show me an example with the expected output

**Comment by brimwats** [comment]
@SkepticMystic same thing I mentioned in the other thread—I'm pretty sure @FTWynn is asking for all the hierarchies at once. For example, my landing page only has one NT right now l
![image](https://user-images.githubusercontent.com/49103046/126525156-7a0928d3-5442-47fa-91da-5141ca4b1219.png)


but the etymology page has lots 
![image](https://user-images.githubusercontent.com/49103046/126525186-d4c22a40-350c-4244-aef8-492eda6a7450.png)


Ideally it would be structured to report the relationships. So in my second example this would do:

![image](https://user-images.githubusercontent.com/49103046/126525490-8e1726d5-2e9a-446d-be21-bb65bf5b0a02.png)

**Comment by brimwats** [comment]
Although I think you'd need to do something to distinguish the "implied" vs real NTs RTs and BTs in my example--maybe a prefix in the settings?

**Comment by SkepticMystic** [comment]
I think I'm confused... It seems like there are a few different points here:

1. Show the entire hierarchy from the 'top' of the vault.
2. Show more than just `child` relationships.
3. Print the immediate neighbours to the current note

For each of those points:

1. Can't you just go to the 'top' note and create the index from there? Given that the index is relative to the current note, creating the index from the top should show you all children going down.
2. The way I have implemented it only considers child relations in a way that would be difficult to do differently.
3. This is different from what I thought the point of the index was. I assumed it should be a TOC type structure only going down from the current note

**Comment by brimwats** [comment]
1. I have no top note, there are multiple interlocking hierarchies. I wanted the index so I could fix things and make it coherent, but even then there will be multiple hierarchies
2 + 3.  That's fine! It's okay if it's not doable. Here's an idea of a list of thesauri to compare to: https://www.asindexing.org/about-indexing/thesauri/online-thesauri-and-authority-files/

**Comment by SkepticMystic** [comment]
For 1. I could add an option to generate an index for all top notes at once.
A top note would be defined as a note with no parents. What do you think? This would be the same as manually going to each top note and pasting each index into one big one

**Comment by SkepticMystic** [comment]
3. Would be easy to do.
Just to confirm I'm understanding correctly, it would just copy what's already in the matrix view to your clipboard? So it would put the neighbours of the current note into the clipboard

**Comment by brimwats** [comment]
1 sounds perfect, yes! Perhaps the feature could be "breadcrumb overview" or "full index" or something if you were looking for phrasing?

I'm not sure if I am understanding #3 though—I think yes? I was generally hoping to generate a whole hierarchy list so I could see things and then regularize them/correct errors :)

**Comment by SkepticMystic** [comment]
For 3. could you give me a bigger example. I think I'm struggling to see the full feature from the example you gave

**Comment by brimwats** [comment]
yes -but i'll need a few days, have a conference today and moving tomorrow — don't be afraid to ping me if I forget

**Comment by FTWynn** [comment]
Whew, what a week! Time to resurface and describe more what I'm talking about!

So the goal I have is to recreate Beau Haan's approach to permanent notes (described in the video here), but to _generate_ the permanent notes page. Linked timestamp shows the permanent notes page, but he start walking through the process at the 8 minute mark.

https://youtu.be/KoddCmn3eL0?t=1581

A key goal of the system is making it easy to navigate and click through, which means fluidly moving around that hierarchy of notes a lot while keeping the bigger picture in mind. Currently my permanent notes page (which is the top level page for breadcrumbs purposes) looks like this:

![Screenshot 2021-07-25 151938](https://user-images.githubusercontent.com/81338/126915193-a5427474-4a2d-4dad-937e-7d51367b8e53.png)

I can then put that note in the sidebar, and get something that looks like this as I work on individual notes.

![Screenshot 2021-07-25 152311](https://user-images.githubusercontent.com/81338/126915324-71fc3517-c931-432f-aa65-134eacfe16df.png)

That way I can navigate around the hierarchy by clicking, but also not lose my bearings. 

Note that right now I'm using block refs, which I generate in the changelog at the bottom, to make it all work. I'm worried about how brittle this is, and breadcrumbs' approach seems much more robust. It leads to some weird questions in the individual notes (do I link to the full note, or the outline index block?). Also, If the hierarchy is generated instead of manual, there could then be other interesting ways to display it as well.

So, that's the user story I'm working through.

**Comment by SkepticMystic** [comment]
Made a bit of progress on this. There are now two commands for Breadcrumbs:
1) Create a local idnex (does what the Create Index button used to do)
2) Create a global index (does what I specified in point 3.)

**Comment by SkepticMystic** [comment]
@FTWynn I think there are a few different ideas floating around in this thread, so I'm struggling to grasp them individually as practical points I can add to the code. Perhaps we can discuss this on Discord, it would help me get a more coherent picture of what your FR is. Do you mind messaging me when you're able and we can discuss this? My handle on the Obsidian server is also @SkepticMystic 😄

**Comment by SkepticMystic** [comment]
@brimwats can I get that bigger example 😅 
I hope your conference and move went well!

**Comment by brimwats** [comment]
> @brimwats can I get that bigger example 😅
> I hope your conference and move went well!

Yes...except breadcrumbs no longer seems to work? I dunno something about the "create hierarchies" broke things for me. I can give you a zipped folder maybe?

**Comment by brimwats** [comment]
@SkepticMystic here are two different folders with multiple hierarchies (thogh 600 is only 1 level deep rn)
[500 - Research PKB & Methods.zip](https://github.com/SkepticMystic/breadcrumbs/files/6993000/500.-.Research.PKB.Methods.zip)
[600 - Etymologies & Onomastics.zip](https://github.com/SkepticMystic/breadcrumbs/files/6993001/600.-.Etymologies.Onomastics.zip)

**Comment by SkepticMystic** [comment]
@FTWynn @brimwats I think this FR is now possible in 2.1.0 :D
Using the new Down View, you can see an auto-updating index of all notes going down the child tree from the current note.
Press the `Freeze` button to stop it from changing

**Comment by brimwats** [comment]
it is!! thanks so much 😀

**Comment by SkepticMystic** [comment]
Gonna consider this working, then.
Please do make another FR if your intention was something else
