### ISSUE TITLE
Feature Request - Suppress breadcrumbs for notes without breadcrumbs metadata

### ISSUE THREAD

**Issue by adxsoft** [SkepticMystic/breadcrumbs#68]
Add option to fully suppress breadcrumb information at top of preview mode for any notes with no parent, child or siblings metadata.

If edit mode breadcrumb view is ever added as a new feature it should also have an option to suppress the breadcrumb information

The basis of this request is many notes will not be part of a parent/child/sibling breadcrumb network.

This will allow a clear visual delineation when viewing notes as to whether they are in the breadcrumb planned network (eg a zettelkasten) or in the overall obsidian link network.

Thanks for the plug-in.

**Comment by SkepticMystic** [comment]
Added in 0.8.19
