### ISSUE TITLE
FR: trail shows path going as far as possible up the parent-tree when no path to index

### ISSUE THREAD

**Issue by weeyizhi** [SkepticMystic/breadcrumbs#69]
As of now, if we do not have any index file specified, the trail shows the path going as far as possible up the parent-tree. If we have an index file specified, the trail only shows the shortest path to the index.

Instead of the "no real or implied parents" message, I would like to be able to see the path going as far as possible up the parent-tree if I have an index specified, but the current file has no path to said index.

I would suggest a new setting to enable this, so that people who want to strictly see path to index still have said ability.

**Comment by SkepticMystic** [comment]
Ahh interesting... so have a "mixed" option to always show all paths, but specify if a path to the specific Index note couldn't be found?

**Comment by weeyizhi** [comment]
Nope. I meant if we enter an index, show path(s) to index if it exists; but if it does not then show path(s) that goes as far up the parent tree as possible.
Whether or not multiple paths are shown should still rely on the show all path settings.
