### ISSUE TITLE
multiple parent fields

### ISSUE THREAD

**Issue by weeyizhi** [SkepticMystic/breadcrumbs#7]
I would like to suggest the ability to indicate multiple parent fields. This would be useful if the user has multiple fields to indicate hierarchy. If multiple parent fields exist in a file, concatenate all the links in those fields as all of its parents.
![image](https://user-images.githubusercontent.com/7296340/122666215-a1a7b680-d1de-11eb-96c4-733f26659180.png)

**Comment by SkepticMystic** [comment]
I can definitely do this. I think this links nicely to #4.
So, there would still only be 3 "types" of fields, `parent`, `sibling`, and `child`, but each of those types could have multiple field names which create them?

**Comment by brimwats** [comment]
I think this would nicely support the use of nonhierachal vocabularies that support multiple parents!

**Comment by SkepticMystic** [comment]
Should be working in 0.4.1. I'll leave it open for bugs
