### ISSUE TITLE
Feature Request: Creating an "Contact" category

### ISSUE THREAD

**Issue by Salamander230** [SkepticMystic/breadcrumbs#71]
I've recently discovered this wonderful plugin and I was intrigued with the thought of keeping track of Parents, Siblings, and Children. 

I was also thinking perhaps a new category may be appropriate in addition to Sibling: "Contact".

Let's say for example you have a pet in the family, a friend who you are on good terms with, or even your rival or enemy. The dog, friend, and rival/enemy are not your parents, siblings, or children, yet they are important to you nonetheless and affect your life in a non-trivial way. I feel like a good category for this would be a "Contact".

Why the name "Contact"?
- **It's a neutral term that implies a relationship, but not as close a relationship as family.** Also, by virtue of it being a contact and not a part of the family, you can be human while it can be non-human. You don't need to fall under the same category (I happen to use categories as parents).
- **A contact does not intrinsically imply other contacts.** Just because someone is on my list of contacts, or if I recently made contact with my dog, it does not necessarily mean that everyone of my other contacts has the same person on their contact list or have even seen my dog.
- **A contact is not mutually exclusive with the other categories.** Even if a contact happens to share the same parent without you knowing (i.e. they are your long-lost sibling or your parent's illegitimate child), that would imply you are siblings while you can still be contacts at the same time.

Is there **_really_** a need for a "Contact" category?
- Technically, any other note that is linked to a current note but is not a parent, sibling, or child can, in some sense, be considered a "contact". However, some of those linked notes are more important than others, and may warrant being in the "contact" category.
- Also, assigning a contact category to some of those links can allow someone to explicitly label that note using their own commonly-used metadata field names, while still keeping track that it's a "contact".
- For example: Let's say a note has two siblings. One of those siblings is "estranged" and the other is "close". We can write something like this:
```
- sibling:: [[Sib1]] [[Sib2]]
- estranged:: [[Sib1]]
- close:: [[Sib2]]
```
In the above example, "estranged" and "close" would be metadata field names for "contacts". So, having a "contact" can allow for more nuance to the sibling, parent, and child relationships and allow for other non-family relationships as well.

I know I've written a lot haha. Thanks for taking the time to read through all this when you get to it, and thanks for making such an awesome plugin!!!

**Comment by SkepticMystic** [comment]
Thank you for such a detailed FR! :)
I see the value in having this separate relationship. I will definitely try implementing this in a reasonable, hopefully non-breaking way. I'm still busy with uni stuff, but I've got a break soon, so I'll be able to work on this

**Comment by Salamander230** [comment]
No rush, and thanks for the quick reply!

In the meantime, I am just stacking on metadata field names in the "siblings" category and using those as my workaround. It was just that for some things, I didn't find it appropriate to call them "siblings", per se... Maybe its more semantics on my part.\

And again, thanks for the awesome plugin! Good luck with uni!

**Comment by veradrawer** [comment]
If Breadcrumbs would allow "contacts" in a nonlinear way whilegiving the option to name said relationships, Obsidian would suddenly become the first tool to actually solve concept mapping: Notes as nodes and links as verbs; what we're missing is the option to name links.

If we could name said "contact" as "#pet", suddenly we could do a Dataview query of owned pets and pet owners. Give each entry some metadata and you can distinguish which is which.

Have a literary note, link another note as contact and name said relationship as "quote," and we now have actual metadata.

**Comment by SkepticMystic** [comment]
@Salamander230 @veradrawer I'm thinking about this feature from the coding side, and it seems relatively simple to implement... Let me know what you think of this: a contact is similar to a sibling, expect it doesn't imply any other contacts. From the code side, I would basically just be adding a new relationship type, and skipping the part where I fill in the implied version of that relation. Is that accurate to what you meant, @Salamander230?

**Comment by SkepticMystic** [comment]
I've recently rewritten Breadcrumbs from scratch, see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md

Given this, I think the following features are enough to achieve the desired result, without having to add an extra "direction". Most of these were not possible when this issue was created:

- Multiple, separate hierarchies
- Implied relations are toggleable, on a hierarchy-level
- Fully custom implied relations, super powerful feature! You can create implied relations using fields from _multiple_ hierarchies

I think with these newer features, coupled with the recent rewrite, you should be able to achieve the same result as in the original post. Let me know if you need a hand setting this up after reading the new README :)

I'm gonna close this out for now, thanks!
