### ISSUE TITLE
FR: Showing alias of notes when generating local index

### ISSUE THREAD

**Issue by jakeoung** [SkepticMystic/breadcrumbs#73]
I often have more meaningful names in _alias_. It would be nice if there is an option to include alias as well, when we generating local index or global index!

**Comment by SkepticMystic** [comment]
Thanks for the request :) I was busy working on the index when you posted this, so I thought I'd give it a try!
I think it's working in 0.9.19, will you give it a go and let me know? You have to enable it as a setting under `Create Index`

**Comment by jakeoung** [comment]
Fantastic! It works smoothly :) Thanks so much for the quick update :)
