### ISSUE TITLE
Error when indexing template note with parent {{LINKCURRENT}}

### ISSUE THREAD

**Issue by stefanopagliari** [SkepticMystic/breadcrumbs#75]
Breadcrumbs (0.9.23) returns an error and fails to load properly when indexing a note that includes this value in the YAML:

Parent: 
  - {{LINKCURRENT}}

**Comment by SkepticMystic** [comment]
@stefanopagliari Does Breadcrumbs still break if this is the case? I tested on my side and things seem to work fine

**Comment by stefanopagliari** [comment]
Apologies for not seeing this before. I must have set my notifications wrong because I only got an email when you closed this, not after your previous message

**Comment by SkepticMystic** [comment]
@stefanopagliari ahh no worries!
Do you still have this issue? After testing on my side initially, it seemed to work fine

**Comment by stefanopagliari** [comment]
I had actually changed my workflow so that I did not rely anymore that.
