### ISSUE TITLE
Add Bidirectional Relationship indicator to Capture of Stats Cell entries.

### ISSUE THREAD

**Issue by BricoleurSoul** [SkepticMystic/breadcrumbs#76]
In capture to clipboard of cells of the stats table  row entries currently have one direction entries even if the relationship is real in both directions.  i.e. a bidirectional relations  is currently reflected by two entries eg.<br>**Valley of Disappointment** → Plateau of Latent Potential <br>and  the obverse <br>Plateau  of Latent Potential→ **Valley of Disappointment** ...  <br>it would be helpful to show the entries with double arrow such as<br>Disappointment <-> Plateau of Latent Potential <br>FR is to implement this style.

**Comment by veradrawer** [comment]
If we were to create some kind of graph using this while having the option to name said bilineal relationships as verbs, we would create the ideal concept mapping tool.

Note ← #concept → Note

**Comment by SkepticMystic** [comment]
This has been added in the original sense of the FR.
@veradrawer can you make another FR to add the relationship name
