### ISSUE TITLE
Is there a way to turn off the breadcrumbs for a note that does not have breadcrumb information in its YAML header?

### ISSUE THREAD

**Issue by swehba** [SkepticMystic/breadcrumbs#77]
I think this plugin is potentially useful, but I don't want it to appear in every note — only in notes where I have set up some relationships — certainly explicit ones, and possibly implicit ones. Is there a way to control this behavior?

**Comment by SkepticMystic** [comment]
If you leave the "No Path Found Message" setting blank, then the path won't show at all for notes with no path

**Comment by swehba** [comment]
Yes, that appears to work. Thanks. I did have to reload Obsidian for the change to take effect. Is that expected?

**Comment by SkepticMystic** [comment]
Makes sense, I haven't inplemented hot reloading for that setting. I'll add that in the next update, thanks
