### ISSUE TITLE
Feature: Highlight the route between A node and B node

### ISSUE THREAD

**Issue by Quorafind** [SkepticMystic/breadcrumbs#78]
Is it doable to hightlight the route between two node? Like search route?

![image](https://user-images.githubusercontent.com/13215013/128592210-55cf120e-7f3e-4aaa-9976-273e0602ab0d.png)

1. You define A node as the start one, B node as the end one, then search, and highlight the route.

When you push next one button, the next route would be highlighted.

**Comment by SkepticMystic** [comment]
@Quorafind I've made some progress on this! Now, you can hover over a node to highlight the path (if it exists), back to the current note (the note you opened the vis view on)

**Comment by SkepticMystic** [comment]
This is now working alot better in the latest version. Right click a node to set the starting point of the path, then hover over another node to highlight the path between the two

**Comment by SkepticMystic** [comment]
Gonna close this out, as it works how I intended
