### ISSUE TITLE
Question: is it possible to fix the position of the tab "Breadcrumbs matrix"

### ISSUE THREAD

**Issue by jakeoung** [SkepticMystic/breadcrumbs#79]
Thanks again for this amazing plugin :) I just have a question regarding the tab.

By default, this tab is positioned on the right side bar. But I usually don't use the right side bar and I put it on the left side bar. However, whenever I update the plugin, its position is changed on the right side bar. Is there any way to fix the position? Or, is this behaviour controlled by the obsidian app? Thanks!

**Comment by SkepticMystic** [comment]
Hmmm interesting. This is a result of how I load the matrix tab. I could very well make it load to the left side just as easily. I can make this a setting to toggle for Right or Left. I'll let you know when I've worked on it :)

**Comment by SkepticMystic** [comment]
@jakeoung This should be working from a previous `0.10.x` update. Just make sure to close the matrix view before changing the default setting. You may also need to reload Obsidian once, but it should work after that
