### ISSUE TITLE
unresolved link does not have "is_unresolved" 

### ISSUE THREAD

**Issue by weeyizhi** [SkepticMystic/breadcrumbs#8]
Links being populated by breadcrumbs plugin seems to be a tags with internal-link class. If the link is unresolved, the is_unresolved class is missing.

User is unable to differentiate links to files that exists versus unresolved ones when using the plugin.

PS: dataview seems to have the same issue too:
https://github.com/blacksmithgu/obsidian-dataview/issues/261

**Comment by SkepticMystic** [comment]
Thanks for the catch! I think I should just be able to check if the link exists in metadataCache (or somewhere else), and add `is_unresolved` as necessary

**Comment by SkepticMystic** [comment]
This seems to be resolved. I ended up having to use a hackyish method of adding a custom class to unresolved links, and just reducing their opacity.
