### ISSUE TITLE
FR: Group implied siblings (Type II) by parent

### ISSUE THREAD

**Issue by veradrawer** [SkepticMystic/breadcrumbs#81]
I currently use parents, siblings and children as derivatives via the Matrix view: literary notes have as parent it's authors, and as implied children any notes that use said reference as bibliography. Siblings are thus any note that come from said parents, but I'ts missing the option to let us know wheresaid siblings are coming from.

It would be amazing to sort siblings by grouping them by parent: siblings by this parent, by the other one, and siblings by both. it would allow people to define in literary notes publishers or similar metadata without the fear of an innavigable bloat.

**Comment by SkepticMystic** [comment]
Interesting, I like this idea.
I'm gonna be working on a big change from some previous FRs, but I'll work on this when possible.

**Comment by SkepticMystic** [comment]
@veradrawer I'm thinking about how this would be implemented. Everything would, of course, be optional. So there is no worry that it breaks functionality for users who don't want this feature.
That being said, there are a couple ways I'm thinking this could be done:
1. If you hover over an implied note in the matrix view, there could be a tooltip showing which note implies it.
2. There could be a more physical separation in the matrix view, with grid squares spacing out the implied relations based on the note that implied them:
![image](https://user-images.githubusercontent.com/70717676/129472076-9837df5a-bee5-45c4-8c8b-f1cb60a05a0b.png)

What are your thoughts on this? @HEmile, I see you are in favour of this feature too, what do you think?

**Comment by hieu6** [comment]
I like option 2, physical/visual separation for a quick at a glance overview

**Comment by HEmile** [comment]
Yes, me too! Would it say what the parent is, though?

**Comment by SkepticMystic** [comment]
@HEmile Yes, the breadcrumbs would be grouped into a mini-matrix with the parent as it's heading

**Comment by SkepticMystic** [comment]
@veradrawer @hieu6 @HEmile I haven't implemented option 2 yet, but option 1 is working in the version I'm gonna release soon

**Comment by SkepticMystic** [comment]
Now that there are so many different types of implied relations (and [fully customisable ones](https://github.com/SkepticMystic/breadcrumbs?tab=readme-ov-file#custom-transitive-relations), too), I don't think I'll add support for this. When there were only two types, it was reasonable to support grouping by the parent that implied the edge. But now that logic can't as easily be applied to all the possible kinds.
Let me know if you've got a different idea, but I'm gonna close this for now.
My recommendation is to use the latest "Sort" feature in the Matrix View, Tree View, and Codeblocks. You can sort by "Explicit", which will group real and implied edges together, and sub-group edges based on the Edge Builder that created them, and the Implied Relation that implied them
