### ISSUE TITLE
Open Stats and Open Matrix view not showing in Command Palette

### ISSUE THREAD

**Issue by heliostatic** [SkepticMystic/breadcrumbs#82]
Two of the commands that are expected (Open Stats and Open Matrix view) with Breadcrumbs do not appear in the palette (or I expect them incorrectly, which is always possible)
<img width="725" alt="2021-08-10 at 20 59 11 - Obsidian - CleanShot" src="https://user-images.githubusercontent.com/70898/128953957-8ce51d34-7950-499f-a802-84872f183319.png">

**Comment by SkepticMystic** [comment]
If they aren't the in the command palette, then those two views should already be open in the right side leaf. Let me know if it works :)
There is also a new setting to toggle which side the matrix view opens on (left or right)

**Comment by heliostatic** [comment]
Yep, that's exactly it. Whoops :D
