### ISSUE TITLE
FR: Filter nodes in Vis View 

### ISSUE THREAD

**Issue by Ravenclawer** [SkepticMystic/breadcrumbs#84]
Add a search frame in visualization view and behave just like obsidian's search frame that allows users to filter out unwanted notes or folders

**Comment by SkepticMystic** [comment]
Definitely something I intend to add to the vis view! It is difficult to add the same search functionality that graph view has, because that feature isn't exposed to other plugins yet. But I could implement a more basic version of this for now

**Comment by SkepticMystic** [comment]
@Ravenclawer the Juggl Codeblock in the latest beta releases can do this :D
You can download it here: https://github.com/SkepticMystic/breadcrumbs/releases/tag/2.41.0
Checkout the documentation on [BC codeblocks](https://github.com/SkepticMystic/breadcrumbs/wiki/Codeblocks). The Juggl codeblocks work the same as `type: tree`, except you just use `type: juggl`.
You can filter nodes using Dataview `from` syntax: 
- Filter by tag: `from: #A and !#B`
- Filter by folder: `from: "Folder/subFolder"`
