### ISSUE TITLE
Breadcrumbs doesn't display anything in latest version, with TypeError

### ISSUE THREAD

**Issue by HEmile** [SkepticMystic/breadcrumbs#86]
Hi,

Since the latest version, Breadcrumbs doesn't display anything anymore (not in preview, trails, stats). Looks like the indexing is botched up somewhere. Here is my output:

![image](https://user-images.githubusercontent.com/1289165/129322301-cc2c05db-0487-4bf5-97a6-0b9dd9a78546.png)

**Comment by SkepticMystic** [comment]
I accidentally released a breaking change, right before I went to bed!😞 
If you go into settings, under the first drop down, you'll see things are different... you can now have multiple separate hierarchies (#85). The changes breaks Breadcrumbs, so you now have to add in your new hierarchies, reload, and it _should_ work.
You can have any combinations of fields within a hierarchy. (↑: Up, Parent; →: Same; ↓: Down), fields can even be blank (↑: Up; →: ; ↓: Down).
Will you give it a try and let me know if it works for you

**Comment by SkepticMystic** [comment]
Be sure to save each hierarchy after editing, and press Show Hierarchies to make sure it did as you wanted.

![image](https://user-images.githubusercontent.com/70717676/129323238-1dd10f82-fd8c-47a2-adcd-8560107efd02.png)

**Comment by SkepticMystic** [comment]
Also, it's very possible the new functionality noticeably slows things down... I've got a fix I'm gonna implement soon

**Comment by jakeoung** [comment]
From the latest version, Breadcrumbs doesn't display anything to me as well.

**Comment by SkepticMystic** [comment]
@jakeoung I accidentally pushed a breaking change. Have you set up hierarchies as described above? I updated the settings documentation to explain how.
Let me know once you've done that, and also update to 0.10.18

**Comment by jakeoung** [comment]
I've updated the new version! But it still doesn't work. (I change the setting as you mentioned) It seems that if I set parent in alias, it seems to work, but if I use the syntax of Juggl, it doesn't work.

**Comment by SkepticMystic** [comment]
Alright, I suspected it was an issue with the Juggl syntax... I'll take a look and try get it working. Thanks for the info!

**Comment by SkepticMystic** [comment]
@jakeoung can you try 0.10.20 and let me know if it works with Juggl links

**Comment by jakeoung** [comment]
It works! Thanks :) The only thing which doesn't work is that when I copy the index, it shows parents in a weird way. (Before, it showed child)

**Comment by HEmile** [comment]
It also works for me now!

**Comment by SkepticMystic** [comment]
@jakeoung thanks for the feedback! I'm gonna close out this issue, but do you mind making a separate one for this index problem :)
