### ISSUE TITLE
🐛 undetected parent if note is a number

### ISSUE THREAD

**Issue by konhi** [SkepticMystic/breadcrumbs#88]
- v0.10.24 (currently newest)
- doesn't work either on v0.9.5, a version from 25 days ago - it's not a new issue
- adding a letter before number fixes it

![obsidian-breadcrumbs-bug](https://user-images.githubusercontent.com/61631665/129455826-e6406616-6aad-46c7-9ae2-975a60d78f4d.gif)

[Shown vault.](https://github.com/SkepticMystic/breadcrumbs/files/6986954/breadcrumbs-bug.zip)

**Comment by konhi** [comment]
May cause be that title is stored as numeric type, instead of text?

**2021.md**
![image](https://user-images.githubusercontent.com/61631665/129456304-28ecb233-ca84-49ba-b7cd-838fb8703a07.png)

**2a021.md**
![image](https://user-images.githubusercontent.com/61631665/129456344-f84170c8-c4e5-4a23-96ca-bfb672e6d3ab.png)

**Comment by SkepticMystic** [comment]
Ahh well spotted, thanks! This only seems to happen when using the Obsidian metadata cache. If you're using dataview, it converts it to a string already. I will check if the value is a number, then convert toString, if so. I'll let you know when I've pushed the fix

**Comment by SkepticMystic** [comment]
This should be fixed in 0.10.25
