### ISSUE TITLE
Feature Request: Place Statistics in Bottom Bar Option

### ISSUE THREAD

**Issue by brimwats1** [SkepticMystic/breadcrumbs#89]
I think it would be great if this 
![image](https://user-images.githubusercontent.com/49103046/129492838-43c012a8-145d-4f78-9902-729b90eaf5c4.png)

would show up in the bottom bar here:

![image](https://user-images.githubusercontent.com/49103046/129492845-c7a5ae3e-3971-43e3-9b6d-63d00eb0cb6b.png)

**Comment by SkepticMystic** [comment]
Ahhh good idea! I think doing it for every hierarchy separately (how it currently shows in the stats view), would be way too cluttered. So instead, I can show the totals for all hierarchies:
`↑(N: 75, E: 54) →(N: 75, E: 54) ↓(N: 75, E: 54)` to say that **all** the `up` fields have 75 Nodes, and 54 Edges, and so on.
What do you think of this @brimwats?

**Comment by brimwats** [comment]
I think either picking a "starred" category to show in the bottom bar and then defaulting to the totals would give folks the most options :)

**Comment by SkepticMystic** [comment]
Ahhh now that is a good idea! I shall do so

**Comment by SkepticMystic** [comment]
I'm currently working on a rebuild, and don't think I'll add support for this.
Please read here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
If it would really help your workflow, I can consider this again in the new release.
