### ISSUE TITLE
Feature Request: Use an Outline in an Index Note to Establish Relationships

### ISSUE THREAD

**Issue by keithadams** [SkepticMystic/breadcrumbs#90]
# Use an Outline in an Index Note to Establish Relationships

Instead of using frontmatter, what if we had the option to use dedicated outline files to establish relationships? By using some set of rules, the user can identify the outline as specific to the breadcrumbs plugin (e.g. title prefix, title suffix, tag, frontmatter in the outline file). The user could then rearrange Wiki Links in a strict bulletpoint outline to establish relationships. Add in a hotkey action like "Jump to Index Note" and users update the relationships of their notes as easily as they can update an outline. 

### Animals Outline

<img width="440" alt="breadcrumbs outline" src="https://user-images.githubusercontent.com/11220719/129791718-44aa080c-89ed-42c9-a2df-5f8b3e97179e.png">

### Breadcrumbs for Dog Generated From Outline

<img width="625" alt="breadcrumbs for dog" src="https://user-images.githubusercontent.com/11220719/129792103-76639bec-56eb-4b6b-b1be-e541ca2fc8ee.png">

### Add Pomeranian as a child to Dog

<img width="437" alt="Add pom to dogs" src="https://user-images.githubusercontent.com/11220719/129792278-bdecaeef-40a9-4c58-a32e-3f08f0ff62fb.png">

### Updated Breadcrumbs for Dog Generated From Outline

<img width="616" alt="breadcrumbs for dog updated" src="https://user-images.githubusercontent.com/11220719/129792564-1f5c32a7-60f8-4e79-8193-5e40fb255cf5.png">

**Comment by SkepticMystic** [comment]
Ooooh this is a good idea! I would definitely only implement it for a specific note, as it would require alot more computation to parse the note content versus grabbing the note's metadataCache.
There would be a setting `Bullet Point Index Notes: ["Index 1", "Index 2", ...]` telling Breadcrumbs to look for this specific type of index on those given notes

**Comment by SkepticMystic** [comment]
lol, and using this feature, you could use the `Create Index` command to auto generate the existing index, and then get rid of all the breadcrumbs in your notes! Nice and clean

**Comment by BricoleurSoul** [comment]
Heaven forbid!

I would not want a “ghost in the machine” having a global impact on the matrix and graph - I like  the “genie in the bottle” to show implied relationships (an incredibly powerful and useful tool) but I am a great believer in a “don’t destroy the data” philosophy and removing the data for the original seems dangerous!

If I have a new note to be “breadcrumbed” I would still want to it to be updated in the index note — but if I needed to regenerate the index note from scratch how would that be possible if the source was removed?

Likewise, if I want to use juggl graphs (labelled edges for the win) I want those shown shoulder to shoulder with the breadcrumb info.


Just my “2 bits worth”  😊

Executive Director


Canadian Lacrosse Hall of Fame
Anvil Centre, 777 Columbia Street,
New Westminster, BC V3M 1B6
E ***@***.***
C 778.237.3601

**Comment by SkepticMystic** [comment]
Hahaha for sure, it wouldn't be necessary to remove anything, just possible 😋 
But I like this idea as a way to create the index in one, separate place

**Comment by keithadams** [comment]
@SkepticMystic I'm glad you like the idea. Thanks for the consideration!

The idea came from trying to make sense of 70+ related links using an outline. Things went from a flat mess to a clear structure pretty quickly, especially using outline shortcuts. Immediately after, I wanted to use breadcrumbs (awesome plugin btw!) to take advantage of this structure. Even with automation and macros, updating each note manually felt slow. It's seems much more natural, simpler, and faster to define relationships in this way.

@BricoleurSoul As SkepticMystic said, I don't think this feature needs to take away existing functionality and could be implemented as an alternative.

**Comment by BricoleurSoul** [comment]
Just tossing this in the rising...

How about MOC?  - "Map of Concept" that is used in many, and somewhat different ways, but this proposed  outline of the topic structure feature seems to fit to me.

David

**Comment by SkepticMystic** [comment]
@BricoleurSoul I like this. I think I'd brand it specifically as "Breadcrumbs MOC", to avoid ambiguity.

Also, maybe "Reverse Index", "Auto Index", "Breadcrumbs TOC (Table of Contents)"

**Comment by keithadams** [comment]
> @keithadams what would you call this feature?

I like the suggestions so far. To add a few candidates:

- Hierarchy Note
- Note Hierarchy
- Hierarchy Outline
- Note Hierarchy Outline

**Comment by SkepticMystic** [comment]
@keithadams I'm almost done with this feature, I _think_. 
But one problem is, now that there are multiple hierarchies, which hierarchy do I add these links to?
For example, if I have two hierarchies: `↑: up, →: same, ↓: down` and `↑: parent, →: sibling, ↓: child`, which type of `↓` should these notes get added to?
I guess there could be a setting to specify which type they are. I think what would be easiest is to require that the type is one of the existing hierarchy's `↓` fields. So in this case, it would have to be down, or child. If you want it to be something else, then make a separate hierarchy for it.
What do you think?
@HEmile @BricoleurSoul your thoughts on this?

**Comment by BricoleurSoul** [comment]
I like the approach of choosing the down value for which hierarchy to use,  so  ->  and ^ automatically follow.

I am testing with four hierarchies now, I will  probably not go with one of them but already have another in mind so I think the flexibility of being able to define which used with this feature would be a must for widespread use - not just for me but for anyone who uses the multiple hierarchy feature.

David (aka Bricoleur Soul)

**Comment by SkepticMystic** [comment]
@BricoleurSoul just pushed the new release, will you work your testing magic and see how it works 😄 
So currently, it parses a Hierarchy Note of the form:

![image](https://user-images.githubusercontent.com/70717676/130281648-2305698a-1d1a-460e-b49c-e04fae38e6d1.png)

Every item has to be a list item `- [[Note]]`.
Use indentation to indicate depth in the hierarchy.
It doesn't matter how much indentation you use, as long as you use the same indentation for each depth. (Basically, try use only tabs, or the same number of spaces each time).

Also, be sure to update your settings for "Hierarchy Note" (the name I've gone with for now), before trying it.

Let me know if there are other things which are unclear

**Comment by SkepticMystic** [comment]
Darnit, push a silly bug. Gimme a sec

**Comment by BricoleurSoul** [comment]
Will gladly do - I just recovered from self inflicted error that broke indexing (so in testing mood now 😊) may be next day for you before I have meaningful feedback (grandkids are insisting on special birthday event and dinner out now as I won’t be here for the actual date in 3 months…)

I’ll try to figure what I did that broke indexing yesterday (as I didn’t have time to localize whether my fourth hierarchy was set up incorrectly, whether setting breadcrumbs incorrectly with admonition block, or bad inline yaml field) it is a pain trying to figure out using console for me given lack of knowledge - but if I only change one thing at a time I can muddle through! If it is a real issue I will let you know as well as a results of the near hierarchy index feature.

Cheers,

David

**Comment by SkepticMystic** [comment]
@BricoleurSoul _should_ be working in latest release 🤞🏼 (it works on my main vault)
One issue I know is that you can't have blank lines in between items, or at the end of the hierarchy... I thought I fixed this, but I guess not. It'll have to do for now.

Hopefully you can give it a small try before going 😅 
Enjoy the dinner though, sounds fun!

Also, do let me know if the issue persists. I hope, for my own sake, it is just an error with the fourth hierarchy 😋

**Comment by SkepticMystic** [comment]
Alright, blanks line should be allowed now :)

**Comment by keithadams** [comment]
Lightning fast delivery! Impressive! I'll be trying it very soon.

> But one problem is, now that there are multiple hierarchies, which hierarchy do I add these links to?
> For example, if I have two hierarchies: `↑: up, →: same, ↓: down` and `↑: parent, →: sibling, ↓: child`, which type of `↓` should these notes get added to?

Perhaps you could set the desired relationships in the frontmatter of the particular "Hierarchy Note":

<img width="344" alt="Screen Shot 2021-08-20 at 5 25 53 PM" src="https://user-images.githubusercontent.com/11220719/130304643-26c4a1e1-58f1-4680-94d4-365d7c0fa518.png">

And if I had another **Hierarchy Note** about say a Family Tree, I could specify different relationship labels:

<img width="425" alt="Screen Shot 2021-08-20 at 5 29 01 PM" src="https://user-images.githubusercontent.com/11220719/130304863-d4adc840-dee8-4e04-b70b-bd48498a8810.png">

**Comment by keithadams** [comment]
One more alternative, although I don't like this one as much. It seems error prone.

Use a default child relation similar to how you have it now, but user can override the default in the **Note Hierarchy** with a prefix.

## Example

<img width="362" alt="Screen Shot 2021-08-20 at 5 47 46 PM" src="https://user-images.githubusercontent.com/11220719/130305381-f3f712e4-8c04-491b-90dc-792f36fc069c.png">

### If no prefix, use default

<img width="362" alt="Screen Shot 2021-08-20 at 5 47 46 PM" src="https://user-images.githubusercontent.com/11220719/130305432-a025836a-96ec-48dc-b6a5-e0a6f441a7c1.png">

### Override default using a prefix

<img width="412" alt="Screen Shot 2021-08-20 at 5 46 08 PM" src="https://user-images.githubusercontent.com/11220719/130305416-75f88449-00d8-49a9-9f99-138b60011340.png">

**Comment by keithadams** [comment]
It seems only the first child is being connected to the parent. Using your example:

![simple test](https://user-images.githubusercontent.com/70717676/130281648-2305698a-1d1a-460e-b49c-e04fae38e6d1.png)

---

**A**
A.1 is a child
A.2 is not a child
A.3 is not a child

---

**A.2**
A.2.1 is a child
A.2.2 is not a child

---

**B**
B.1 is a child

**Comment by SkepticMystic** [comment]
@keithadams I like the frontmatter version best. It gives the user flexibility to have different hierarchy notes for different hierarchy fields. And because the second option seems complicated to put together :yum:

**Comment by SkepticMystic** [comment]
Gonna close this out. I'll open up another issue for the ability to put the desired relationship into the frontmatter
