### ISSUE TITLE
Provide more descriptive commit messages

### ISSUE THREAD

**Issue by swehba** [SkepticMystic/breadcrumbs#91]
Calling every commit a "chore" provides no clue as to what may have changed. In comparing some of the revisions, it's clear that some of the "chores" actually involved bug fixes and user-observable changes. It would be nice to know what is changing. It also helps build confidence that the code is well managed and the the plugin will continue to progress and be maintained — which all of us are hopeful for. Cheers.

**Comment by SkepticMystic** [comment]
Hey @swehba. I use a framework called Conventional Commits, you can google to find out more. This framework, along with the tool Standard Versioning, means I automatically create a changelog with every release. This changelog can be found in the root of the repo here: https://github.com/SkepticMystic/breadcrumbs/blob/master/CHANGELOG.md
The changelog only shows features and bug fixes, but if you click on the version number heading `# 0.10.32`, you can see a list of all changes made

**Comment by SkepticMystic** [comment]
Gonna close this out. I have added a link at the top of the readme pointing to the changelog

**Comment by swehba** [comment]
Thanks.
