### ISSUE TITLE
FR: Allow manual sorting of items in L/M View

### ISSUE THREAD

**Issue by SkepticMystic** [SkepticMystic/breadcrumbs#92]
1. Order alphabetically (Currently the breadcrumbs appear in the same order they appear in that file, I think)
2. Use a custom property of a file to sort the breadcrumbs in it. `sortorder`, for example.

**Comment by bodiequirk** [comment]
Looks like you beat me to the punch! Would love to see a consistent order in my Breadcrumbs hierarchy! Thanks Ross

**Comment by SkepticMystic** [comment]
@bodiequirk @veradrawer if you want to test out the beta version, I have added the ability to sort items in [1.2.0](https://github.com/SkepticMystic/breadcrumbs/releases/tag/1.2.0).
Note, if you are still on `0.11.x`, this _may_ be a breaking change. If you get any errors, first ping me here or (preferably) on Discord `@SkepticMystic`, and I can help troubleshoot it :)

**Comment by bodiequirk** [comment]
@SkepticMystic Ooh nice! I would be glad to help out. This is awesome. I have the beta running on my laptop anyways, so I will download the beta of Breadcrumbs and let you know how it works!

**Comment by bodiequirk** [comment]
I was able to utilize the custom order from the [beta 1.2 version](https://github.com/SkepticMystic/breadcrumbs/releases/tag/1.2.0), but I cannot get the `BC-order` field to override the alphabetical defaults in the current (2.4 build)
