### ISSUE TITLE
Hierarchy Note only detecting first child

### ISSUE THREAD

**Issue by keithadams** [SkepticMystic/breadcrumbs#94]
When using the Hierarchy Note feature, it seems only the first child is being connected to the parent. Using this example:

![simple test](https://user-images.githubusercontent.com/70717676/130281648-2305698a-1d1a-460e-b49c-e04fae38e6d1.png)

---

**A**
A.1 is a child
A.2 is not a child
A.3 is not a child

---

**A.2**
A.2.1 is a child
A.2.2 is not a child

---

**B**
B.1 is a child

_Originally posted by @keithadams in https://github.com/SkepticMystic/breadcrumbs/issues/90#issuecomment-903029400_

**Comment by SkepticMystic** [comment]
Hmmm ok, thanks for the bug issue.
Can you:
1. Send the md content on that note.
2. Enable debug mode, refresh index, and send thru the console logs that appear. Hopefully you can an error that makes it obvious what the problem is

**Comment by keithadams** [comment]
This one throws an error and prevents index from refreshing.

[Hierarchy Note.md](https://github.com/SkepticMystic/breadcrumbs/files/7024965/Hierarchy.Note.md)

[obsidian.md-1629524113300.log](https://github.com/SkepticMystic/breadcrumbs/files/7024968/obsidian.md-1629524113300.log)

**Comment by keithadams** [comment]
Also, I the same example using a new vault and the breadcrumbs worked properly.

![](https://user-images.githubusercontent.com/70717676/130281648-2305698a-1d1a-460e-b49c-e04fae38e6d1.png)

**Comment by SkepticMystic** [comment]
Ooooohh I think I see the error...
@keithadams can you try the same thing, but using tabs instead of spaces?
Just to confirm where the bug is

**Comment by keithadams** [comment]
Yes, It worked with tabs!

**Comment by SkepticMystic** [comment]
Alright, I'm currently working on a fix for the problem, you shouldn't have to use tabs anymore.

That's strange that you don't see any siblings... There obviously won't be real siblings (because the hierarchy note only creates a ↓ relation). So there will definitely be real children, implied parents, and there should be some implied siblings (notes with the same parents).
If this issue carries on, can you open up another issue for it

**Comment by keithadams** [comment]
Yeah, I'll open another issue if it persists. Thanks for fixing/implementing this!

**Comment by SkepticMystic** [comment]
Can you give it a try in 0.10.36
It's working on my two vaults.
Now you really can use any amount of indentation, as long as it is exactly the same for all lines. So if you use two spaces to indicate one level of depth, then use that amount everywhere. A depth 3 note would have 2 x 3 = 6 spaces.

**Comment by SkepticMystic** [comment]
And if the indentation isn't consistent, you should get a notice. It allows won't break everything else if the indentation isn't right 😅

**Comment by SkepticMystic** [comment]
Hmmmm no... there is an edge case I missed. I've got to try another way of fixing this. To Google!

**Comment by keithadams** [comment]
Yeah, I'm getting the notice that my indentation isn't consistent and the breadcrumbs stopped working. I checked that spacing was consistent and trimmed whitespace. Also, I'm using 4 spaces if that helps.

**Comment by SkepticMystic** [comment]
Ok, for realsies. Can you check on 0.10.37 in a couple minutes

**Comment by keithadams** [comment]
Yes, it's working 😄

**Comment by SkepticMystic** [comment]
Awesome 😄 
Thank you for finding these bugs! Please do let me know if you find any others.

This hierarchy note feature is an interesting problem :)
