### ISSUE TITLE
Breadcrumbs no longer detected when a Hierarchy Note is deleted

### ISSUE THREAD

**Issue by keithadams** [SkepticMystic/breadcrumbs#95]
If a note specified in the "Hierarchy Note(s)" setting is deleted or missing, then it seems to stop all breadcrumbs from working.

**Comment by SkepticMystic** [comment]
Interesting... I think I know what the error is, shouldn't be too hard to fix.
Can you check the console for any errors when this happens.

**Comment by keithadams** [comment]
[obsidian.md-1629524471109.log](https://github.com/SkepticMystic/breadcrumbs/files/7024978/obsidian.md-1629524471109.log)

**Comment by SkepticMystic** [comment]
Makes sense, let me fix that. Thank you for finding this!

**Comment by SkepticMystic** [comment]
Confirmed working on my test vault and main vault in 0.10.36
