### ISSUE TITLE
Sibling relationships missing from Matrix/List view when using a Hierarchy Note

### ISSUE THREAD

**Issue by keithadams** [SkepticMystic/breadcrumbs#96]
Siblings aren't displaying when using a **Hierarchy Note**. I'm testing it with a new vault and the following simple hierarchy.

<img width="305" alt="Screen Shot 2021-08-21 at 2 14 14 AM" src="https://user-images.githubusercontent.com/11220719/130317171-4c4754ed-9cae-49cf-b11b-0e4199e39421.png">

The following image is the Matrix for Parent 1. It should have Parent 2 and Parent 3 as siblings.

<img width="286" alt="Screen Shot 2021-08-21 at 2 14 32 AM" src="https://user-images.githubusercontent.com/11220719/130317202-c24ee1dd-add4-4166-baa5-5e136e8edb68.png">

### Hierarchy Note MD and Log

[Hierarchy.md](https://github.com/SkepticMystic/breadcrumbs/files/7025241/Hierarchy.md)
[obsidian.md-1629537117796.log](https://github.com/SkepticMystic/breadcrumbs/files/7025243/obsidian.md-1629537117796.log)

**Comment by SkepticMystic** [comment]
Hmmm this makes sense.
The Hierarchy Note is only filling in real children relations. So although the implied parent relations are there, that isn't enough to then imply a sibling.
Having the same _real_ parents will imply a sibling, but having the same _implied_ parents doesn't.
I guess the solution, then, is to make the hierarchy note fill in real children and real parents, which I think makes sense.

**Comment by SkepticMystic** [comment]
@keithadams in 0.10.43 (I should really role over to 0.11.0 at some point 😓), you can now give an ↑ relation for the hierarchy note to fill in as real. This will mean implied siblings get filled in too.
You can have a ↓ relation, and ↑ relation, neither, or both.

**Comment by keithadams** [comment]
Great solution, everything is working. Thanks again!

**Comment by keithadams** [comment]
Quick typo

<img width="621" alt="Screen Shot 2021-08-21 at 11 03 24 AM" src="https://user-images.githubusercontent.com/11220719/130331186-d86316a2-e495-409d-aca9-fc57661adeff.png">

**Comment by SkepticMystic** [comment]
Oooh thanks! Will change that typo

**Comment by SkepticMystic** [comment]
Gonna close this out
