### ISSUE TITLE
FR: Allow list items to use other list delimiters `*`, `+`

### ISSUE THREAD

**Issue by zcysxy** [SkepticMystic/breadcrumbs#97]
Currently a Hierarchy Note must be a pure list with the list identifier being `-`. I hope it can parse other Markdown list identifiers (`+`, `*`) as well.

Also I hope it can allow other content like yaml, comment, headings in the Hierarchy Note.

**Comment by SkepticMystic** [comment]
Should be fixed in 0.10.44
@zcysxy will you give it a try and let me know :)

**Comment by zcysxy** [comment]
@SkepticMystic Yeah it works now 🎉
