### ISSUE TITLE
Feature Request: Support for Obsidian Mobile and Publish

### ISSUE THREAD

**Issue by bodiequirk** [SkepticMystic/breadcrumbs#98]
I would love to be able to use Breadcrumbs as the complete navigation for my Obsidian vault, even on Mobile and Publish. Even if it was only the Trail feature at the top of the pages that would be enough. I love this plugin, and I want to use it everywhere! Thanks so much.

**Comment by SkepticMystic** [comment]
Just noting what was discussed on the Discord:
1. No plugins on Publish for now
2. Possibly working on mobile

**Comment by SkepticMystic** [comment]
Gonna close this. Awesome to hear it's working on mobile, and I will try get it working on Publish when that is possible
