### ISSUE TITLE
FR: Support `parent: 'no wikilinks'` syntax in yaml

### ISSUE THREAD

**Issue by veradrawer** [SkepticMystic/breadcrumbs#99]
Breadcrumbs 0.10.43

Currently when listing a note in the metadata to get it indexed it should be written in the following manner:

parent: [[note]]

_or_ 

parent:
- note

But, writing it as valid yaml gets breacrumbs not recognizing it:

parent: note

_or_

parent: "note"

I tag this as a bug because I do remember a time when this syntaxis was valid.

**Comment by SkepticMystic** [comment]
Hey veradrawer, thanks for the issue.
Currently, you have to wrap the note in wikilinks, I think.
So it needs to be:
```
---
parent: [[note]]
---
```
Did it used to work without wikilink brackets?
Do you have dataview enabled?
Do you get any console errors when refreshing the index?

**Comment by SkepticMystic** [comment]
It's possible some other new feature is causing bugs

**Comment by veradrawer** [comment]
Hi! Yes I have Dataview enabled, and it worked without wikilinks, unintended feature?

**Comment by veradrawer** [comment]
For example, the following YAML is a real case:

author:
  - "Karen Holtzblatt"
  - "Hugh Beyer"
publisher: "Elsevier"

Author is declared as a type of parent, and breacrumbs is indexing both both, yet publisher it's also another parent and Elsevier is no longer being indexed.

**Comment by SkepticMystic** [comment]
Hmmm weird... can you:
1. Run this in the console and send back the result: `app.plugins.plugins.dataview.api.page('<note name.md>')` for that note.

2. Enable superdebug, open up console, refresh index, see if you get any errors.

3. If no errors, look inside the `neighbourObjArr` and try find the values for that note. These are all the values for `Untitled Kanban`, for example:
![image](https://user-images.githubusercontent.com/70717676/130329125-d8d3d9ac-fc90-4c99-97ea-d4d19a712680.png)

**Comment by SkepticMystic** [comment]
@veradrawer  Wait, I see where the problem is...
I suppose this can be changed to work in your case, but I don't want to potentially introduce a bunch of unforeseen consequences...
Basically, if you use a list of breadcrumbs `parent: ['a', 'b']`, then you don't have to wrap each one in wikilinks. But if you only have a single link in the field: `parent: 'a'`, then it has to have wikilinks.

**Comment by SkepticMystic** [comment]
Yeah, I can see a bunch of changes that would need to be made if I allowed it to work in this case `parent: 'a'`... Perhaps there is a simpler solution I'm not considering, but for now I don't think I'll extend it to do that.
This did used to work before multiple hierarchies, but I completely redid the metadata parsing since then

**Comment by SkepticMystic** [comment]
It _should_ work if you wrap it in single square brackets `parent: ['a']`

**Comment by veradrawer** [comment]
> 
> 
> It _should_ work if you wrap it in single square brackets `parent: ['a']`

It works, thank you!

**Comment by SkepticMystic** [comment]
I'll keep this open for now to remind myself to try think of a simpler solution, but this is the fix for now

**Comment by SkepticMystic** [comment]
Also, this syntax is how Licat intends to add support for links in yaml `parent: ['a']`, so I think it is enough that this works

**Comment by veradrawer** [comment]
> I'll keep this open for now to remind myself to try think of a simpler solution, but this is the fix for now

Thank you for caring

**Comment by SkepticMystic** [comment]
@veradrawer after going over the code again, and considering the standards that Licat intends to implement, I don't think I'll add support for this syntax. There are alot of edge cases, and it will slow things down alot to now check for so many more possibilities in every file.
Also, I'd prefer to promote the `parent: ['Note']` syntax Licat wants to use
